// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module FIR_HLS_INTERPOLATOR (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_r_TDATA,
        output_r_TVALID,
        output_r_TREADY,
        kernel_out_dout,
        kernel_out_empty_n,
        kernel_out_read,
        grp_FIR_filter_1_fu_747_p_din1,
        grp_FIR_filter_1_fu_747_p_din2,
        grp_FIR_filter_1_fu_747_p_din3,
        grp_FIR_filter_1_fu_747_p_din4,
        grp_FIR_filter_1_fu_747_p_din5,
        grp_FIR_filter_1_fu_747_p_din6,
        grp_FIR_filter_1_fu_747_p_din7,
        grp_FIR_filter_1_fu_747_p_din8,
        grp_FIR_filter_1_fu_747_p_din9,
        grp_FIR_filter_1_fu_747_p_din10,
        grp_FIR_filter_1_fu_747_p_dout0_0,
        grp_FIR_filter_1_fu_747_p_dout0_1,
        grp_FIR_filter_1_fu_747_p_dout0_2,
        grp_FIR_filter_1_fu_747_p_dout0_3,
        grp_FIR_filter_1_fu_747_p_dout0_4,
        grp_FIR_filter_1_fu_747_p_ce,
        grp_FIR_filter_1_fu_747_p_start,
        grp_FIR_filter_1_fu_747_p_ready,
        grp_FIR_filter_1_fu_747_p_done,
        grp_FIR_filter_1_fu_747_p_idle,
        grp_FIR_filter_2_fu_760_p_din1,
        grp_FIR_filter_2_fu_760_p_din2,
        grp_FIR_filter_2_fu_760_p_din3,
        grp_FIR_filter_2_fu_760_p_din4,
        grp_FIR_filter_2_fu_760_p_din5,
        grp_FIR_filter_2_fu_760_p_din6,
        grp_FIR_filter_2_fu_760_p_dout0_0,
        grp_FIR_filter_2_fu_760_p_dout0_1,
        grp_FIR_filter_2_fu_760_p_dout0_2,
        grp_FIR_filter_2_fu_760_p_dout0_3,
        grp_FIR_filter_2_fu_760_p_dout0_4,
        grp_FIR_filter_2_fu_760_p_dout0_5,
        grp_FIR_filter_2_fu_760_p_start,
        grp_FIR_filter_2_fu_760_p_ready,
        grp_FIR_filter_2_fu_760_p_done,
        grp_FIR_filter_2_fu_760_p_idle
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] output_r_TDATA;
output   output_r_TVALID;
input   output_r_TREADY;
input  [15:0] kernel_out_dout;
input   kernel_out_empty_n;
output   kernel_out_read;
output  [31:0] grp_FIR_filter_1_fu_747_p_din1;
output  [31:0] grp_FIR_filter_1_fu_747_p_din2;
output  [31:0] grp_FIR_filter_1_fu_747_p_din3;
output  [31:0] grp_FIR_filter_1_fu_747_p_din4;
output  [9:0] grp_FIR_filter_1_fu_747_p_din5;
output  [12:0] grp_FIR_filter_1_fu_747_p_din6;
output  [13:0] grp_FIR_filter_1_fu_747_p_din7;
output  [12:0] grp_FIR_filter_1_fu_747_p_din8;
output  [9:0] grp_FIR_filter_1_fu_747_p_din9;
output  [15:0] grp_FIR_filter_1_fu_747_p_din10;
input  [15:0] grp_FIR_filter_1_fu_747_p_dout0_0;
input  [31:0] grp_FIR_filter_1_fu_747_p_dout0_1;
input  [31:0] grp_FIR_filter_1_fu_747_p_dout0_2;
input  [31:0] grp_FIR_filter_1_fu_747_p_dout0_3;
input  [31:0] grp_FIR_filter_1_fu_747_p_dout0_4;
output   grp_FIR_filter_1_fu_747_p_ce;
output   grp_FIR_filter_1_fu_747_p_start;
input   grp_FIR_filter_1_fu_747_p_ready;
input   grp_FIR_filter_1_fu_747_p_done;
input   grp_FIR_filter_1_fu_747_p_idle;
output  [31:0] grp_FIR_filter_2_fu_760_p_din1;
output  [31:0] grp_FIR_filter_2_fu_760_p_din2;
output  [31:0] grp_FIR_filter_2_fu_760_p_din3;
output  [31:0] grp_FIR_filter_2_fu_760_p_din4;
output  [31:0] grp_FIR_filter_2_fu_760_p_din5;
output  [15:0] grp_FIR_filter_2_fu_760_p_din6;
input  [15:0] grp_FIR_filter_2_fu_760_p_dout0_0;
input  [31:0] grp_FIR_filter_2_fu_760_p_dout0_1;
input  [31:0] grp_FIR_filter_2_fu_760_p_dout0_2;
input  [31:0] grp_FIR_filter_2_fu_760_p_dout0_3;
input  [31:0] grp_FIR_filter_2_fu_760_p_dout0_4;
input  [31:0] grp_FIR_filter_2_fu_760_p_dout0_5;
output   grp_FIR_filter_2_fu_760_p_start;
input   grp_FIR_filter_2_fu_760_p_ready;
input   grp_FIR_filter_2_fu_760_p_done;
input   grp_FIR_filter_2_fu_760_p_idle;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] output_r_TDATA;
reg output_r_TVALID;
reg kernel_out_read;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [1:0] mod_value;
reg   [15:0] y2;
reg   [31:0] p_ZL19H_filter_FIR_int_40_0;
reg   [31:0] p_ZL19H_filter_FIR_int_40_1;
reg   [31:0] p_ZL19H_filter_FIR_int_40_2;
reg   [31:0] p_ZL19H_filter_FIR_int_40_3;
reg   [31:0] p_ZL19H_filter_FIR_int_40_4;
reg   [31:0] p_ZL19H_filter_FIR_int_41_0;
reg   [31:0] p_ZL19H_filter_FIR_int_41_1;
reg   [31:0] p_ZL19H_filter_FIR_int_41_2;
reg   [31:0] p_ZL19H_filter_FIR_int_41_3;
reg   [31:0] p_ZL19H_filter_FIR_int_42_0;
reg   [31:0] p_ZL19H_filter_FIR_int_42_1;
reg   [31:0] p_ZL19H_filter_FIR_int_42_2;
reg   [31:0] p_ZL19H_filter_FIR_int_42_3;
reg   [31:0] p_ZL19H_filter_FIR_int_43_0;
reg   [31:0] p_ZL19H_filter_FIR_int_43_1;
reg   [31:0] p_ZL19H_filter_FIR_int_43_2;
reg   [31:0] p_ZL19H_filter_FIR_int_43_3;
reg    output_r_TDATA_blk_n;
wire    ap_CS_fsm_state3;
reg   [1:0] mod_value_load_reg_443;
reg    kernel_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [1:0] mod_value_load_load_fu_183_p1;
wire    grp_FIR_filter_1_fu_124_ap_ready;
reg    grp_FIR_filter_1_fu_124_ap_ce;
reg   [31:0] grp_FIR_filter_1_fu_124_FIR_delays_read;
reg   [31:0] grp_FIR_filter_1_fu_124_FIR_delays_read_25;
reg   [31:0] grp_FIR_filter_1_fu_124_FIR_delays_read_26;
reg   [31:0] grp_FIR_filter_1_fu_124_FIR_delays_read_27;
reg   [9:0] grp_FIR_filter_1_fu_124_FIR_coe_read;
reg   [12:0] grp_FIR_filter_1_fu_124_FIR_coe_read_14;
reg   [13:0] grp_FIR_filter_1_fu_124_FIR_coe_read_15;
reg   [12:0] grp_FIR_filter_1_fu_124_FIR_coe_read_16;
reg   [9:0] grp_FIR_filter_1_fu_124_FIR_coe_read_17;
reg    ap_block_state2_ignore_call4;
reg    ap_block_state3_ignore_call4;
wire    grp_FIR_filter_2_fu_152_ap_ready;
reg   [1:0] storemerge2_i_reg_103;
reg    ap_block_state3;
reg    grp_FIR_filter_1_fu_124_ap_start_reg;
reg   [3:0] ap_NS_fsm;
wire    ap_NS_fsm_state2;
reg    grp_FIR_filter_2_fu_152_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    ap_block_state2;
wire   [15:0] shl_ln102_fu_307_p2;
wire   [15:0] shl_ln98_fu_338_p2;
wire   [15:0] shl_ln94_fu_399_p2;
wire   [15:0] shl_ln107_fu_430_p2;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 mod_value = 2'd0;
#0 y2 = 16'd0;
#0 p_ZL19H_filter_FIR_int_40_0 = 32'd0;
#0 p_ZL19H_filter_FIR_int_40_1 = 32'd0;
#0 p_ZL19H_filter_FIR_int_40_2 = 32'd0;
#0 p_ZL19H_filter_FIR_int_40_3 = 32'd0;
#0 p_ZL19H_filter_FIR_int_40_4 = 32'd0;
#0 p_ZL19H_filter_FIR_int_41_0 = 32'd0;
#0 p_ZL19H_filter_FIR_int_41_1 = 32'd0;
#0 p_ZL19H_filter_FIR_int_41_2 = 32'd0;
#0 p_ZL19H_filter_FIR_int_41_3 = 32'd0;
#0 p_ZL19H_filter_FIR_int_42_0 = 32'd0;
#0 p_ZL19H_filter_FIR_int_42_1 = 32'd0;
#0 p_ZL19H_filter_FIR_int_42_2 = 32'd0;
#0 p_ZL19H_filter_FIR_int_42_3 = 32'd0;
#0 p_ZL19H_filter_FIR_int_43_0 = 32'd0;
#0 p_ZL19H_filter_FIR_int_43_1 = 32'd0;
#0 p_ZL19H_filter_FIR_int_43_2 = 32'd0;
#0 p_ZL19H_filter_FIR_int_43_3 = 32'd0;
#0 grp_FIR_filter_1_fu_124_ap_start_reg = 1'b0;
#0 grp_FIR_filter_2_fu_152_ap_start_reg = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_FIR_filter_1_fu_124_ap_start_reg <= 1'b0;
    end else begin
        if ((((mod_value_load_load_fu_183_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_NS_fsm_state2)) | ((mod_value_load_load_fu_183_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_NS_fsm_state2)) | ((mod_value_load_load_fu_183_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_NS_fsm_state2)))) begin
            grp_FIR_filter_1_fu_124_ap_start_reg <= 1'b1;
        end else if ((grp_FIR_filter_1_fu_124_ap_ready == 1'b1)) begin
            grp_FIR_filter_1_fu_124_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_FIR_filter_2_fu_152_ap_start_reg <= 1'b0;
    end else begin
        if (((mod_value_load_load_fu_183_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_NS_fsm_state2))) begin
            grp_FIR_filter_2_fu_152_ap_start_reg <= 1'b1;
        end else if ((grp_FIR_filter_2_fu_152_ap_ready == 1'b1)) begin
            grp_FIR_filter_2_fu_152_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3))) begin
        if ((mod_value_load_reg_443 == 2'd2)) begin
            storemerge2_i_reg_103 <= 2'd3;
        end else if ((mod_value_load_reg_443 == 2'd3)) begin
            storemerge2_i_reg_103 <= 2'd0;
        end else if ((mod_value_load_reg_443 == 2'd1)) begin
            storemerge2_i_reg_103 <= 2'd2;
        end else if ((mod_value_load_reg_443 == 2'd0)) begin
            storemerge2_i_reg_103 <= 2'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mod_value <= storemerge2_i_reg_103;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        mod_value_load_reg_443 <= mod_value;
    end
end

always @ (posedge ap_clk) begin
    if (((mod_value_load_reg_443 == 2'd0) & (1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3))) begin
        p_ZL19H_filter_FIR_int_40_0 <= grp_FIR_filter_2_fu_760_p_dout0_1;
        p_ZL19H_filter_FIR_int_40_1 <= grp_FIR_filter_2_fu_760_p_dout0_2;
        p_ZL19H_filter_FIR_int_40_2 <= grp_FIR_filter_2_fu_760_p_dout0_3;
        p_ZL19H_filter_FIR_int_40_3 <= grp_FIR_filter_2_fu_760_p_dout0_4;
        p_ZL19H_filter_FIR_int_40_4 <= grp_FIR_filter_2_fu_760_p_dout0_5;
    end
end

always @ (posedge ap_clk) begin
    if (((mod_value_load_reg_443 == 2'd1) & (1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3))) begin
        p_ZL19H_filter_FIR_int_41_0 <= grp_FIR_filter_1_fu_747_p_dout0_1;
        p_ZL19H_filter_FIR_int_41_1 <= grp_FIR_filter_1_fu_747_p_dout0_2;
        p_ZL19H_filter_FIR_int_41_2 <= grp_FIR_filter_1_fu_747_p_dout0_3;
        p_ZL19H_filter_FIR_int_41_3 <= grp_FIR_filter_1_fu_747_p_dout0_4;
    end
end

always @ (posedge ap_clk) begin
    if (((mod_value_load_reg_443 == 2'd2) & (1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3))) begin
        p_ZL19H_filter_FIR_int_42_0 <= grp_FIR_filter_1_fu_747_p_dout0_1;
        p_ZL19H_filter_FIR_int_42_1 <= grp_FIR_filter_1_fu_747_p_dout0_2;
        p_ZL19H_filter_FIR_int_42_2 <= grp_FIR_filter_1_fu_747_p_dout0_3;
        p_ZL19H_filter_FIR_int_42_3 <= grp_FIR_filter_1_fu_747_p_dout0_4;
    end
end

always @ (posedge ap_clk) begin
    if (((mod_value_load_reg_443 == 2'd3) & (1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3))) begin
        p_ZL19H_filter_FIR_int_43_0 <= grp_FIR_filter_1_fu_747_p_dout0_1;
        p_ZL19H_filter_FIR_int_43_1 <= grp_FIR_filter_1_fu_747_p_dout0_2;
        p_ZL19H_filter_FIR_int_43_2 <= grp_FIR_filter_1_fu_747_p_dout0_3;
        p_ZL19H_filter_FIR_int_43_3 <= grp_FIR_filter_1_fu_747_p_dout0_4;
    end
end

always @ (posedge ap_clk) begin
    if (((mod_value_load_reg_443 == 2'd0) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        y2 <= kernel_out_dout;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((mod_value_load_reg_443 == 2'd3)) begin
            grp_FIR_filter_1_fu_124_FIR_coe_read = 10'd562;
        end else if ((mod_value_load_reg_443 == 2'd1)) begin
            grp_FIR_filter_1_fu_124_FIR_coe_read = 10'd247;
        end else if ((mod_value_load_reg_443 == 2'd2)) begin
            grp_FIR_filter_1_fu_124_FIR_coe_read = 10'd50;
        end else begin
            grp_FIR_filter_1_fu_124_FIR_coe_read = 'bx;
        end
    end else begin
        grp_FIR_filter_1_fu_124_FIR_coe_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((mod_value_load_reg_443 == 2'd3)) begin
            grp_FIR_filter_1_fu_124_FIR_coe_read_14 = 13'd2100;
        end else if ((mod_value_load_reg_443 == 2'd1)) begin
            grp_FIR_filter_1_fu_124_FIR_coe_read_14 = 13'd7105;
        end else if ((mod_value_load_reg_443 == 2'd2)) begin
            grp_FIR_filter_1_fu_124_FIR_coe_read_14 = 13'd8105;
        end else begin
            grp_FIR_filter_1_fu_124_FIR_coe_read_14 = 'bx;
        end
    end else begin
        grp_FIR_filter_1_fu_124_FIR_coe_read_14 = 'bx;
    end
end

always @ (*) begin
    if ((((mod_value_load_reg_443 == 2'd3) & (1'b1 == ap_CS_fsm_state2)) | ((mod_value_load_reg_443 == 2'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        grp_FIR_filter_1_fu_124_FIR_coe_read_15 = 14'd7338;
    end else if (((mod_value_load_reg_443 == 2'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        grp_FIR_filter_1_fu_124_FIR_coe_read_15 = 14'd8285;
    end else begin
        grp_FIR_filter_1_fu_124_FIR_coe_read_15 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((mod_value_load_reg_443 == 2'd3)) begin
            grp_FIR_filter_1_fu_124_FIR_coe_read_16 = 13'd7105;
        end else if ((mod_value_load_reg_443 == 2'd1)) begin
            grp_FIR_filter_1_fu_124_FIR_coe_read_16 = 13'd2100;
        end else if ((mod_value_load_reg_443 == 2'd2)) begin
            grp_FIR_filter_1_fu_124_FIR_coe_read_16 = 13'd8105;
        end else begin
            grp_FIR_filter_1_fu_124_FIR_coe_read_16 = 'bx;
        end
    end else begin
        grp_FIR_filter_1_fu_124_FIR_coe_read_16 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((mod_value_load_reg_443 == 2'd3)) begin
            grp_FIR_filter_1_fu_124_FIR_coe_read_17 = 10'd247;
        end else if ((mod_value_load_reg_443 == 2'd1)) begin
            grp_FIR_filter_1_fu_124_FIR_coe_read_17 = 10'd562;
        end else if ((mod_value_load_reg_443 == 2'd2)) begin
            grp_FIR_filter_1_fu_124_FIR_coe_read_17 = 10'd50;
        end else begin
            grp_FIR_filter_1_fu_124_FIR_coe_read_17 = 'bx;
        end
    end else begin
        grp_FIR_filter_1_fu_124_FIR_coe_read_17 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((mod_value_load_reg_443 == 2'd3)) begin
            grp_FIR_filter_1_fu_124_FIR_delays_read = p_ZL19H_filter_FIR_int_43_0;
        end else if ((mod_value_load_reg_443 == 2'd1)) begin
            grp_FIR_filter_1_fu_124_FIR_delays_read = p_ZL19H_filter_FIR_int_41_0;
        end else if ((mod_value_load_reg_443 == 2'd2)) begin
            grp_FIR_filter_1_fu_124_FIR_delays_read = p_ZL19H_filter_FIR_int_42_0;
        end else begin
            grp_FIR_filter_1_fu_124_FIR_delays_read = 'bx;
        end
    end else begin
        grp_FIR_filter_1_fu_124_FIR_delays_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((mod_value_load_reg_443 == 2'd3)) begin
            grp_FIR_filter_1_fu_124_FIR_delays_read_25 = p_ZL19H_filter_FIR_int_43_1;
        end else if ((mod_value_load_reg_443 == 2'd1)) begin
            grp_FIR_filter_1_fu_124_FIR_delays_read_25 = p_ZL19H_filter_FIR_int_41_1;
        end else if ((mod_value_load_reg_443 == 2'd2)) begin
            grp_FIR_filter_1_fu_124_FIR_delays_read_25 = p_ZL19H_filter_FIR_int_42_1;
        end else begin
            grp_FIR_filter_1_fu_124_FIR_delays_read_25 = 'bx;
        end
    end else begin
        grp_FIR_filter_1_fu_124_FIR_delays_read_25 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((mod_value_load_reg_443 == 2'd3)) begin
            grp_FIR_filter_1_fu_124_FIR_delays_read_26 = p_ZL19H_filter_FIR_int_43_2;
        end else if ((mod_value_load_reg_443 == 2'd1)) begin
            grp_FIR_filter_1_fu_124_FIR_delays_read_26 = p_ZL19H_filter_FIR_int_41_2;
        end else if ((mod_value_load_reg_443 == 2'd2)) begin
            grp_FIR_filter_1_fu_124_FIR_delays_read_26 = p_ZL19H_filter_FIR_int_42_2;
        end else begin
            grp_FIR_filter_1_fu_124_FIR_delays_read_26 = 'bx;
        end
    end else begin
        grp_FIR_filter_1_fu_124_FIR_delays_read_26 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((mod_value_load_reg_443 == 2'd3)) begin
            grp_FIR_filter_1_fu_124_FIR_delays_read_27 = p_ZL19H_filter_FIR_int_43_3;
        end else if ((mod_value_load_reg_443 == 2'd1)) begin
            grp_FIR_filter_1_fu_124_FIR_delays_read_27 = p_ZL19H_filter_FIR_int_41_3;
        end else if ((mod_value_load_reg_443 == 2'd2)) begin
            grp_FIR_filter_1_fu_124_FIR_delays_read_27 = p_ZL19H_filter_FIR_int_42_3;
        end else begin
            grp_FIR_filter_1_fu_124_FIR_delays_read_27 = 'bx;
        end
    end else begin
        grp_FIR_filter_1_fu_124_FIR_delays_read_27 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_ignore_call4)) | ((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_ignore_call4)))) begin
        grp_FIR_filter_1_fu_124_ap_ce = 1'b1;
    end else begin
        grp_FIR_filter_1_fu_124_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((mod_value_load_reg_443 == 2'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        kernel_out_blk_n = kernel_out_empty_n;
    end else begin
        kernel_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((mod_value_load_reg_443 == 2'd0) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        kernel_out_read = 1'b1;
    end else begin
        kernel_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3))) begin
        if ((mod_value_load_reg_443 == 2'd3)) begin
            output_r_TDATA = shl_ln107_fu_430_p2;
        end else if ((mod_value_load_reg_443 == 2'd0)) begin
            output_r_TDATA = shl_ln94_fu_399_p2;
        end else if ((mod_value_load_reg_443 == 2'd1)) begin
            output_r_TDATA = shl_ln98_fu_338_p2;
        end else if ((mod_value_load_reg_443 == 2'd2)) begin
            output_r_TDATA = shl_ln102_fu_307_p2;
        end else begin
            output_r_TDATA = 'bx;
        end
    end else begin
        output_r_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((mod_value_load_reg_443 == 2'd3) & (1'b1 == ap_CS_fsm_state3)) | ((mod_value_load_reg_443 == 2'd2) & (1'b1 == ap_CS_fsm_state3)) | ((mod_value_load_reg_443 == 2'd1) & (1'b1 == ap_CS_fsm_state3)) | ((mod_value_load_reg_443 == 2'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        output_r_TDATA_blk_n = output_r_TREADY;
    end else begin
        output_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((mod_value_load_reg_443 == 2'd3) & (1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3)) | ((mod_value_load_reg_443 == 2'd2) & (1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3)) | ((mod_value_load_reg_443 == 2'd1) & (1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3)) | ((mod_value_load_reg_443 == 2'd0) & (1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3)))) begin
        output_r_TVALID = 1'b1;
    end else begin
        output_r_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_NS_fsm_state2 = ap_NS_fsm[32'd1];

always @ (*) begin
    ap_block_state2 = ((mod_value_load_reg_443 == 2'd0) & (kernel_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_ignore_call4 = ((mod_value_load_reg_443 == 2'd0) & (kernel_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3 = (((mod_value_load_reg_443 == 2'd3) & (output_r_TREADY == 1'b0)) | ((mod_value_load_reg_443 == 2'd2) & (output_r_TREADY == 1'b0)) | ((mod_value_load_reg_443 == 2'd1) & (output_r_TREADY == 1'b0)) | ((mod_value_load_reg_443 == 2'd0) & (output_r_TREADY == 1'b0)));
end

always @ (*) begin
    ap_block_state3_ignore_call4 = (((mod_value_load_reg_443 == 2'd3) & (output_r_TREADY == 1'b0)) | ((mod_value_load_reg_443 == 2'd2) & (output_r_TREADY == 1'b0)) | ((mod_value_load_reg_443 == 2'd1) & (output_r_TREADY == 1'b0)) | ((mod_value_load_reg_443 == 2'd0) & (output_r_TREADY == 1'b0)));
end

assign grp_FIR_filter_1_fu_124_ap_ready = grp_FIR_filter_1_fu_747_p_ready;

assign grp_FIR_filter_1_fu_747_p_ce = grp_FIR_filter_1_fu_124_ap_ce;

assign grp_FIR_filter_1_fu_747_p_din1 = grp_FIR_filter_1_fu_124_FIR_delays_read;

assign grp_FIR_filter_1_fu_747_p_din10 = y2;

assign grp_FIR_filter_1_fu_747_p_din2 = grp_FIR_filter_1_fu_124_FIR_delays_read_25;

assign grp_FIR_filter_1_fu_747_p_din3 = grp_FIR_filter_1_fu_124_FIR_delays_read_26;

assign grp_FIR_filter_1_fu_747_p_din4 = grp_FIR_filter_1_fu_124_FIR_delays_read_27;

assign grp_FIR_filter_1_fu_747_p_din5 = grp_FIR_filter_1_fu_124_FIR_coe_read;

assign grp_FIR_filter_1_fu_747_p_din6 = grp_FIR_filter_1_fu_124_FIR_coe_read_14;

assign grp_FIR_filter_1_fu_747_p_din7 = grp_FIR_filter_1_fu_124_FIR_coe_read_15;

assign grp_FIR_filter_1_fu_747_p_din8 = grp_FIR_filter_1_fu_124_FIR_coe_read_16;

assign grp_FIR_filter_1_fu_747_p_din9 = grp_FIR_filter_1_fu_124_FIR_coe_read_17;

assign grp_FIR_filter_1_fu_747_p_start = grp_FIR_filter_1_fu_124_ap_start_reg;

assign grp_FIR_filter_2_fu_152_ap_ready = grp_FIR_filter_2_fu_760_p_ready;

assign grp_FIR_filter_2_fu_760_p_din1 = p_ZL19H_filter_FIR_int_40_0;

assign grp_FIR_filter_2_fu_760_p_din2 = p_ZL19H_filter_FIR_int_40_1;

assign grp_FIR_filter_2_fu_760_p_din3 = p_ZL19H_filter_FIR_int_40_2;

assign grp_FIR_filter_2_fu_760_p_din4 = p_ZL19H_filter_FIR_int_40_3;

assign grp_FIR_filter_2_fu_760_p_din5 = p_ZL19H_filter_FIR_int_40_4;

assign grp_FIR_filter_2_fu_760_p_din6 = kernel_out_dout;

assign grp_FIR_filter_2_fu_760_p_start = grp_FIR_filter_2_fu_152_ap_start_reg;

assign mod_value_load_load_fu_183_p1 = mod_value;

assign shl_ln102_fu_307_p2 = grp_FIR_filter_1_fu_747_p_dout0_0 << 16'd2;

assign shl_ln107_fu_430_p2 = grp_FIR_filter_1_fu_747_p_dout0_0 << 16'd2;

assign shl_ln94_fu_399_p2 = grp_FIR_filter_2_fu_760_p_dout0_0 << 16'd2;

assign shl_ln98_fu_338_p2 = grp_FIR_filter_1_fu_747_p_dout0_0 << 16'd2;

endmodule //FIR_HLS_INTERPOLATOR
