// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module FIR_HLS_FIR_filter_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        FIR_delays_read,
        FIR_delays_read_14,
        FIR_delays_read_15,
        FIR_delays_read_16,
        FIR_delays_read_17,
        x_n,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] FIR_delays_read;
input  [31:0] FIR_delays_read_14;
input  [31:0] FIR_delays_read_15;
input  [31:0] FIR_delays_read_16;
input  [31:0] FIR_delays_read_17;
input  [15:0] x_n;
output  [15:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
reg   [15:0] x_n_read_reg_637;
wire    ap_block_pp0_stage0_11001;
reg  signed [31:0] FIR_delays_read_1_reg_642;
reg   [31:0] FIR_delays_read_2_reg_647;
reg   [31:0] FIR_delays_read_3_reg_657;
reg  signed [31:0] FIR_delays_read_4_reg_667;
reg   [31:0] FIR_delays_read_9_reg_673;
reg   [27:0] tmp_8_reg_681;
wire  signed [11:0] mul_ln45_fu_140_p1;
wire    ap_block_pp0_stage0;
wire  signed [11:0] mul_ln45_1_fu_145_p1;
wire   [39:0] tmp_1_fu_150_p3;
wire   [36:0] tmp_2_fu_162_p3;
wire  signed [40:0] sext_ln45_fu_158_p1;
wire  signed [40:0] sext_ln45_1_fu_170_p1;
wire   [34:0] tmp_3_fu_180_p3;
wire   [40:0] sub_ln45_fu_174_p2;
wire  signed [40:0] sext_ln45_3_fu_188_p1;
wire   [32:0] tmp_4_fu_198_p3;
wire   [40:0] sub_ln45_1_fu_192_p2;
wire  signed [40:0] sext_ln45_4_fu_206_p1;
wire   [40:0] add_ln45_5_fu_210_p2;
wire   [25:0] FIR_accu32_fu_216_p4;
wire   [40:0] tmp_fu_226_p3;
wire  signed [31:0] sext_ln45_2_fu_238_p0;
wire  signed [42:0] sext_ln45_6_fu_234_p1;
wire   [42:0] mul_ln45_fu_140_p2;
wire   [42:0] add_ln45_fu_243_p2;
wire   [42:0] tmp_9_fu_266_p3;
wire   [43:0] tmp_10_fu_277_p3;
wire   [41:0] tmp_11_fu_288_p3;
wire  signed [45:0] sext_ln45_12_fu_284_p1;
wire  signed [45:0] sext_ln45_13_fu_295_p1;
wire   [39:0] tmp_12_fu_305_p3;
wire   [45:0] add_ln45_6_fu_299_p2;
wire  signed [45:0] sext_ln45_14_fu_312_p1;
wire   [37:0] tmp_13_fu_322_p3;
wire   [45:0] sub_ln45_2_fu_316_p2;
wire  signed [45:0] sext_ln45_15_fu_329_p1;
wire   [32:0] tmp_14_fu_339_p3;
wire   [45:0] add_ln45_7_fu_333_p2;
wire  signed [45:0] sext_ln45_16_fu_346_p1;
wire   [45:0] add_ln45_8_fu_350_p2;
wire  signed [46:0] sext_ln45_10_fu_273_p1;
wire  signed [46:0] sext_ln45_5_fu_356_p1;
wire   [46:0] add_ln45_1_fu_360_p2;
wire   [31:0] tmp_5_fu_366_p4;
wire   [43:0] tmp_15_fu_384_p3;
wire   [41:0] tmp_16_fu_395_p3;
wire  signed [45:0] sext_ln45_17_fu_391_p1;
wire  signed [45:0] sext_ln45_18_fu_402_p1;
wire   [39:0] tmp_17_fu_412_p3;
wire   [45:0] add_ln45_9_fu_406_p2;
wire  signed [45:0] sext_ln45_19_fu_419_p1;
wire   [37:0] tmp_18_fu_429_p3;
wire   [45:0] sub_ln45_3_fu_423_p2;
wire  signed [45:0] sext_ln45_20_fu_436_p1;
wire   [32:0] tmp_19_fu_446_p3;
wire   [45:0] add_ln45_10_fu_440_p2;
wire  signed [45:0] sext_ln45_21_fu_453_p1;
wire   [45:0] add_ln45_11_fu_457_p2;
wire   [46:0] and_ln45_1_fu_376_p3;
wire  signed [46:0] sext_ln45_7_fu_463_p1;
wire   [46:0] add_ln45_2_fu_467_p2;
wire   [31:0] tmp_6_fu_473_p4;
wire   [43:0] mul_ln45_1_fu_145_p2;
wire   [46:0] and_ln45_2_fu_483_p3;
wire  signed [46:0] sext_ln45_9_fu_495_p1;
wire   [46:0] add_ln45_3_fu_499_p2;
wire   [31:0] tmp_7_fu_505_p4;
wire   [39:0] tmp_20_fu_523_p3;
wire   [36:0] tmp_21_fu_534_p3;
wire  signed [40:0] sext_ln45_22_fu_530_p1;
wire  signed [40:0] sext_ln45_23_fu_541_p1;
wire   [34:0] tmp_22_fu_551_p3;
wire   [40:0] sub_ln45_4_fu_545_p2;
wire  signed [40:0] sext_ln45_24_fu_558_p1;
wire   [32:0] tmp_23_fu_568_p3;
wire   [40:0] sub_ln45_5_fu_562_p2;
wire  signed [40:0] sext_ln45_25_fu_575_p1;
wire   [40:0] add_ln45_12_fu_579_p2;
wire   [46:0] and_ln45_3_fu_515_p3;
wire  signed [46:0] sext_ln45_11_fu_585_p1;
wire   [46:0] add_ln45_4_fu_589_p2;
wire   [31:0] FIR_delays_write_assign_fu_259_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

FIR_HLS_mul_32s_12s_43_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 43 ))
mul_32s_12s_43_1_1_U20(
    .din0(sext_ln45_2_fu_238_p0),
    .din1(mul_ln45_fu_140_p1),
    .dout(mul_ln45_fu_140_p2)
);

FIR_HLS_mul_32s_12s_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 44 ))
mul_32s_12s_44_1_1_U21(
    .din0(FIR_delays_read_4_reg_667),
    .din1(mul_ln45_1_fu_145_p1),
    .dout(mul_ln45_1_fu_145_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        FIR_delays_read_1_reg_642 <= FIR_delays_read_17;
        FIR_delays_read_2_reg_647 <= FIR_delays_read_16;
        FIR_delays_read_3_reg_657 <= FIR_delays_read_15;
        FIR_delays_read_4_reg_667 <= FIR_delays_read_14;
        FIR_delays_read_9_reg_673 <= FIR_delays_read;
        tmp_8_reg_681 <= {{add_ln45_fu_243_p2[42:15]}};
        x_n_read_reg_637 <= x_n;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign FIR_accu32_fu_216_p4 = {{add_ln45_5_fu_210_p2[40:15]}};

assign FIR_delays_write_assign_fu_259_p3 = {{x_n_read_reg_637}, {16'd0}};

assign add_ln45_10_fu_440_p2 = ($signed(sub_ln45_3_fu_423_p2) + $signed(sext_ln45_20_fu_436_p1));

assign add_ln45_11_fu_457_p2 = ($signed(add_ln45_10_fu_440_p2) + $signed(sext_ln45_21_fu_453_p1));

assign add_ln45_12_fu_579_p2 = ($signed(sub_ln45_5_fu_562_p2) + $signed(sext_ln45_25_fu_575_p1));

assign add_ln45_1_fu_360_p2 = ($signed(sext_ln45_10_fu_273_p1) + $signed(sext_ln45_5_fu_356_p1));

assign add_ln45_2_fu_467_p2 = ($signed(and_ln45_1_fu_376_p3) + $signed(sext_ln45_7_fu_463_p1));

assign add_ln45_3_fu_499_p2 = ($signed(and_ln45_2_fu_483_p3) + $signed(sext_ln45_9_fu_495_p1));

assign add_ln45_4_fu_589_p2 = ($signed(and_ln45_3_fu_515_p3) + $signed(sext_ln45_11_fu_585_p1));

assign add_ln45_5_fu_210_p2 = ($signed(sub_ln45_1_fu_192_p2) + $signed(sext_ln45_4_fu_206_p1));

assign add_ln45_6_fu_299_p2 = ($signed(sext_ln45_12_fu_284_p1) + $signed(sext_ln45_13_fu_295_p1));

assign add_ln45_7_fu_333_p2 = ($signed(sub_ln45_2_fu_316_p2) + $signed(sext_ln45_15_fu_329_p1));

assign add_ln45_8_fu_350_p2 = ($signed(add_ln45_7_fu_333_p2) + $signed(sext_ln45_16_fu_346_p1));

assign add_ln45_9_fu_406_p2 = ($signed(sext_ln45_17_fu_391_p1) + $signed(sext_ln45_18_fu_402_p1));

assign add_ln45_fu_243_p2 = ($signed(sext_ln45_6_fu_234_p1) + $signed(mul_ln45_fu_140_p2));

assign and_ln45_1_fu_376_p3 = {{tmp_5_fu_366_p4}, {15'd0}};

assign and_ln45_2_fu_483_p3 = {{tmp_6_fu_473_p4}, {15'd0}};

assign and_ln45_3_fu_515_p3 = {{tmp_7_fu_505_p4}, {15'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = {{add_ln45_4_fu_589_p2[46:31]}};

assign ap_return_1 = FIR_delays_read_4_reg_667;

assign ap_return_2 = FIR_delays_read_3_reg_657;

assign ap_return_3 = FIR_delays_read_2_reg_647;

assign ap_return_4 = FIR_delays_read_1_reg_642;

assign ap_return_5 = FIR_delays_write_assign_fu_259_p3;

assign mul_ln45_1_fu_145_p1 = 44'd17592186043389;

assign mul_ln45_fu_140_p1 = 43'd8796093021181;

assign sext_ln45_10_fu_273_p1 = $signed(tmp_9_fu_266_p3);

assign sext_ln45_11_fu_585_p1 = $signed(add_ln45_12_fu_579_p2);

assign sext_ln45_12_fu_284_p1 = $signed(tmp_10_fu_277_p3);

assign sext_ln45_13_fu_295_p1 = $signed(tmp_11_fu_288_p3);

assign sext_ln45_14_fu_312_p1 = $signed(tmp_12_fu_305_p3);

assign sext_ln45_15_fu_329_p1 = $signed(tmp_13_fu_322_p3);

assign sext_ln45_16_fu_346_p1 = $signed(tmp_14_fu_339_p3);

assign sext_ln45_17_fu_391_p1 = $signed(tmp_15_fu_384_p3);

assign sext_ln45_18_fu_402_p1 = $signed(tmp_16_fu_395_p3);

assign sext_ln45_19_fu_419_p1 = $signed(tmp_17_fu_412_p3);

assign sext_ln45_1_fu_170_p1 = $signed(tmp_2_fu_162_p3);

assign sext_ln45_20_fu_436_p1 = $signed(tmp_18_fu_429_p3);

assign sext_ln45_21_fu_453_p1 = $signed(tmp_19_fu_446_p3);

assign sext_ln45_22_fu_530_p1 = $signed(tmp_20_fu_523_p3);

assign sext_ln45_23_fu_541_p1 = $signed(tmp_21_fu_534_p3);

assign sext_ln45_24_fu_558_p1 = $signed(tmp_22_fu_551_p3);

assign sext_ln45_25_fu_575_p1 = $signed(tmp_23_fu_568_p3);

assign sext_ln45_2_fu_238_p0 = FIR_delays_read_17;

assign sext_ln45_3_fu_188_p1 = $signed(tmp_3_fu_180_p3);

assign sext_ln45_4_fu_206_p1 = $signed(tmp_4_fu_198_p3);

assign sext_ln45_5_fu_356_p1 = $signed(add_ln45_8_fu_350_p2);

assign sext_ln45_6_fu_234_p1 = $signed(tmp_fu_226_p3);

assign sext_ln45_7_fu_463_p1 = $signed(add_ln45_11_fu_457_p2);

assign sext_ln45_9_fu_495_p1 = $signed(mul_ln45_1_fu_145_p2);

assign sext_ln45_fu_158_p1 = $signed(tmp_1_fu_150_p3);

assign sub_ln45_1_fu_192_p2 = ($signed(sub_ln45_fu_174_p2) - $signed(sext_ln45_3_fu_188_p1));

assign sub_ln45_2_fu_316_p2 = ($signed(add_ln45_6_fu_299_p2) - $signed(sext_ln45_14_fu_312_p1));

assign sub_ln45_3_fu_423_p2 = ($signed(add_ln45_9_fu_406_p2) - $signed(sext_ln45_19_fu_419_p1));

assign sub_ln45_4_fu_545_p2 = ($signed(sext_ln45_22_fu_530_p1) - $signed(sext_ln45_23_fu_541_p1));

assign sub_ln45_5_fu_562_p2 = ($signed(sub_ln45_4_fu_545_p2) - $signed(sext_ln45_24_fu_558_p1));

assign sub_ln45_fu_174_p2 = ($signed(sext_ln45_fu_158_p1) - $signed(sext_ln45_1_fu_170_p1));

assign tmp_10_fu_277_p3 = {{FIR_delays_read_2_reg_647}, {12'd0}};

assign tmp_11_fu_288_p3 = {{FIR_delays_read_2_reg_647}, {10'd0}};

assign tmp_12_fu_305_p3 = {{FIR_delays_read_2_reg_647}, {8'd0}};

assign tmp_13_fu_322_p3 = {{FIR_delays_read_2_reg_647}, {6'd0}};

assign tmp_14_fu_339_p3 = {{FIR_delays_read_2_reg_647}, {1'd0}};

assign tmp_15_fu_384_p3 = {{FIR_delays_read_3_reg_657}, {12'd0}};

assign tmp_16_fu_395_p3 = {{FIR_delays_read_3_reg_657}, {10'd0}};

assign tmp_17_fu_412_p3 = {{FIR_delays_read_3_reg_657}, {8'd0}};

assign tmp_18_fu_429_p3 = {{FIR_delays_read_3_reg_657}, {6'd0}};

assign tmp_19_fu_446_p3 = {{FIR_delays_read_3_reg_657}, {1'd0}};

assign tmp_1_fu_150_p3 = {{x_n}, {24'd0}};

assign tmp_20_fu_523_p3 = {{FIR_delays_read_9_reg_673}, {8'd0}};

assign tmp_21_fu_534_p3 = {{FIR_delays_read_9_reg_673}, {5'd0}};

assign tmp_22_fu_551_p3 = {{FIR_delays_read_9_reg_673}, {3'd0}};

assign tmp_23_fu_568_p3 = {{FIR_delays_read_9_reg_673}, {1'd0}};

assign tmp_2_fu_162_p3 = {{x_n}, {21'd0}};

assign tmp_3_fu_180_p3 = {{x_n}, {19'd0}};

assign tmp_4_fu_198_p3 = {{x_n}, {17'd0}};

assign tmp_5_fu_366_p4 = {{add_ln45_1_fu_360_p2[46:15]}};

assign tmp_6_fu_473_p4 = {{add_ln45_2_fu_467_p2[46:15]}};

assign tmp_7_fu_505_p4 = {{add_ln45_3_fu_499_p2[46:15]}};

assign tmp_9_fu_266_p3 = {{tmp_8_reg_681}, {15'd0}};

assign tmp_fu_226_p3 = {{FIR_accu32_fu_216_p4}, {15'd0}};

endmodule //FIR_HLS_FIR_filter_2
