// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_26_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        FIR_accu32_out,
        FIR_accu32_out_ap_vld,
        H_filter_FIR_address0,
        H_filter_FIR_ce0,
        H_filter_FIR_q0,
        H_filter_FIR_address1,
        H_filter_FIR_ce1,
        H_filter_FIR_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] FIR_accu32_out;
output   FIR_accu32_out_ap_vld;
output  [8:0] H_filter_FIR_address0;
output   H_filter_FIR_ce0;
input  [15:0] H_filter_FIR_q0;
output  [8:0] H_filter_FIR_address1;
output   H_filter_FIR_ce1;
input  [15:0] H_filter_FIR_q1;

reg ap_idle;
reg FIR_accu32_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln26_fu_106_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [8:0] b_FIR_address0;
wire  signed [13:0] b_FIR_q0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln26_reg_205;
reg   [0:0] icmp_ln26_reg_205_pp0_iter1_reg;
reg   [0:0] icmp_ln26_reg_205_pp0_iter2_reg;
wire   [63:0] zext_ln26_fu_118_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln27_fu_134_p1;
reg   [31:0] FIR_accu32_fu_40;
wire   [31:0] FIR_accu32_1_fu_166_p2;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [7:0] i_fu_44;
wire   [7:0] add_ln26_fu_112_p2;
reg   [7:0] ap_sig_allocacmp_i_2;
wire    ap_block_pp0_stage0_01001;
reg    H_filter_FIR_ce1_local;
reg    H_filter_FIR_ce0_local;
reg    b_FIR_ce0_local;
wire   [8:0] zext_ln26_1_fu_124_p1;
wire   [8:0] sub_ln27_fu_128_p2;
wire  signed [30:0] grp_fu_181_p3;
wire   [31:0] shl_ln_fu_159_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 FIR_accu32_fu_40 = 32'd0;
#0 i_fu_44 = 8'd0;
#0 ap_done_reg = 1'b0;
end

FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_26_1_b_FIR_ROM_AUTO_1R #(
    .DataWidth( 14 ),
    .AddressRange( 392 ),
    .AddressWidth( 9 ))
b_FIR_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b_FIR_address0),
    .ce0(b_FIR_ce0_local),
    .q0(b_FIR_q0)
);

FIR_HLS_am_addmul_16s_16s_14s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 31 ))
am_addmul_16s_16s_14s_31_4_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(H_filter_FIR_q0),
    .din1(H_filter_FIR_q1),
    .din2(b_FIR_q0),
    .ce(1'b1),
    .dout(grp_fu_181_p3)
);

FIR_HLS_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            FIR_accu32_fu_40 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            FIR_accu32_fu_40 <= FIR_accu32_1_fu_166_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln26_fu_106_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_44 <= add_ln26_fu_112_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_44 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln26_reg_205 <= icmp_ln26_fu_106_p2;
        icmp_ln26_reg_205_pp0_iter1_reg <= icmp_ln26_reg_205;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln26_reg_205_pp0_iter2_reg <= icmp_ln26_reg_205_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((icmp_ln26_reg_205_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        FIR_accu32_out_ap_vld = 1'b1;
    end else begin
        FIR_accu32_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        H_filter_FIR_ce0_local = 1'b1;
    end else begin
        H_filter_FIR_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        H_filter_FIR_ce1_local = 1'b1;
    end else begin
        H_filter_FIR_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln26_fu_106_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_44;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_FIR_ce0_local = 1'b1;
    end else begin
        b_FIR_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign FIR_accu32_1_fu_166_p2 = (shl_ln_fu_159_p3 + FIR_accu32_fu_40);

assign FIR_accu32_out = FIR_accu32_fu_40;

assign H_filter_FIR_address0 = zext_ln27_fu_134_p1;

assign H_filter_FIR_address1 = zext_ln26_fu_118_p1;

assign H_filter_FIR_ce0 = H_filter_FIR_ce0_local;

assign H_filter_FIR_ce1 = H_filter_FIR_ce1_local;

assign add_ln26_fu_112_p2 = (ap_sig_allocacmp_i_2 + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b_FIR_address0 = zext_ln26_fu_118_p1;

assign icmp_ln26_fu_106_p2 = ((ap_sig_allocacmp_i_2 == 8'd195) ? 1'b1 : 1'b0);

assign shl_ln_fu_159_p3 = {{grp_fu_181_p3}, {1'd0}};

assign sub_ln27_fu_128_p2 = ($signed(9'd391) - $signed(zext_ln26_1_fu_124_p1));

assign zext_ln26_1_fu_124_p1 = ap_sig_allocacmp_i_2;

assign zext_ln26_fu_118_p1 = ap_sig_allocacmp_i_2;

assign zext_ln27_fu_134_p1 = sub_ln27_fu_128_p2;

endmodule //FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_26_1
