set SynModuleInfo {
  {SRCNAME FIR_filter.2_Pipeline_VITIS_LOOP_65_1 MODELNAME FIR_filter_2_Pipeline_VITIS_LOOP_65_1 RTLNAME FIR_HLS_FIR_filter_2_Pipeline_VITIS_LOOP_65_1
    SUBMODULES {
      {MODELNAME FIR_HLS_mac_muladd_16s_15s_32s_32_4_1 RTLNAME FIR_HLS_mac_muladd_16s_15s_32s_32_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME FIR_HLS_flow_control_loop_pipe_sequential_init RTLNAME FIR_HLS_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME FIR_HLS_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME FIR_filter.2_Pipeline_VITIS_LOOP_69_2 MODELNAME FIR_filter_2_Pipeline_VITIS_LOOP_69_2 RTLNAME FIR_HLS_FIR_filter_2_Pipeline_VITIS_LOOP_69_2}
  {SRCNAME FIR_filter.2 MODELNAME FIR_filter_2 RTLNAME FIR_HLS_FIR_filter_2}
  {SRCNAME FIR_filter_Pipeline_VITIS_LOOP_65_1 MODELNAME FIR_filter_Pipeline_VITIS_LOOP_65_1 RTLNAME FIR_HLS_FIR_filter_Pipeline_VITIS_LOOP_65_1
    SUBMODULES {
      {MODELNAME FIR_HLS_mac_muladd_16s_14s_31s_31_4_1 RTLNAME FIR_HLS_mac_muladd_16s_14s_31s_31_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME FIR_HLS_FIR_filter_Pipeline_VITIS_LOOP_65_1_b_FIR_dec_int_40_ROM_AUTO_1R RTLNAME FIR_HLS_FIR_filter_Pipeline_VITIS_LOOP_65_1_b_FIR_dec_int_40_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME FIR_filter_Pipeline_VITIS_LOOP_69_2 MODELNAME FIR_filter_Pipeline_VITIS_LOOP_69_2 RTLNAME FIR_HLS_FIR_filter_Pipeline_VITIS_LOOP_69_2}
  {SRCNAME FIR_filter MODELNAME FIR_filter RTLNAME FIR_HLS_FIR_filter}
  {SRCNAME FIR_HLS_Pipeline_VITIS_LOOP_65_1 MODELNAME FIR_HLS_Pipeline_VITIS_LOOP_65_1 RTLNAME FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_65_1
    SUBMODULES {
      {MODELNAME FIR_HLS_mac_muladd_16s_16s_32ns_32_4_1 RTLNAME FIR_HLS_mac_muladd_16s_16s_32ns_32_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_65_1_b_FIR_kernel_ROM_AUTO_1R RTLNAME FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_65_1_b_FIR_kernel_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME FIR_HLS_Pipeline_VITIS_LOOP_69_2 MODELNAME FIR_HLS_Pipeline_VITIS_LOOP_69_2 RTLNAME FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_69_2}
  {SRCNAME FIR_HLS MODELNAME FIR_HLS RTLNAME FIR_HLS IS_TOP 1
    SUBMODULES {
      {MODELNAME FIR_HLS_H_filter_FIR_dec_40_RAM_AUTO_1R1W RTLNAME FIR_HLS_H_filter_FIR_dec_40_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_H_filter_FIR_kernel_RAM_AUTO_1R1W RTLNAME FIR_HLS_H_filter_FIR_kernel_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_H_filter_FIR_dec_43_RAM_AUTO_1R1W RTLNAME FIR_HLS_H_filter_FIR_dec_43_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_b_FIR_dec_int_43_ROM_AUTO_1R RTLNAME FIR_HLS_b_FIR_dec_int_43_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_b_FIR_dec_int_41_ROM_AUTO_1R RTLNAME FIR_HLS_b_FIR_dec_int_41_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_b_FIR_dec_int_42_ROM_AUTO_1R RTLNAME FIR_HLS_b_FIR_dec_int_42_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_regslice_both RTLNAME FIR_HLS_regslice_both BINDTYPE interface TYPE adapter IMPL reg_slice}
    }
  }
}
