// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module FIR_HLS_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        input_r_TDATA,
        input_r_TVALID,
        input_r_TREADY,
        output_r_TDATA,
        output_r_TVALID,
        output_r_TREADY,
        dec_out_dout,
        dec_out_empty_n,
        dec_out_read,
        dec_out_din,
        dec_out_full_n,
        dec_out_write,
        kernel_out_dout,
        kernel_out_empty_n,
        kernel_out_read,
        kernel_out_din,
        kernel_out_full_n,
        kernel_out_write
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] input_r_TDATA;
input   input_r_TVALID;
output   input_r_TREADY;
output  [15:0] output_r_TDATA;
output   output_r_TVALID;
input   output_r_TREADY;
input  [15:0] dec_out_dout;
input   dec_out_empty_n;
output   dec_out_read;
output  [15:0] dec_out_din;
input   dec_out_full_n;
output   dec_out_write;
input  [15:0] kernel_out_dout;
input   kernel_out_empty_n;
output   kernel_out_read;
output  [15:0] kernel_out_din;
input   kernel_out_full_n;
output   kernel_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg dec_out_read;
reg dec_out_write;
reg kernel_out_read;
reg kernel_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] mod_value_1;
reg   [6:0] H_accu_FIR_kernel_address0;
reg    H_accu_FIR_kernel_ce0;
wire   [31:0] H_accu_FIR_kernel_q0;
wire   [31:0] H_accu_FIR_kernel_q1;
reg    dec_out_i_blk_n;
wire    ap_CS_fsm_state4;
reg    kernel_out_o_blk_n;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln19_fu_211_p2;
reg   [0:0] icmp_ln19_reg_287;
wire    ap_CS_fsm_state3;
wire    grp_DECIMATOR_fu_138_ap_done;
wire   [15:0] add_ln24_fu_217_p2;
reg   [15:0] x_n_reg_296;
reg   [15:0] y_reg_301;
wire    grp_DECIMATOR_fu_138_ap_start;
wire    grp_DECIMATOR_fu_138_ap_idle;
wire    grp_DECIMATOR_fu_138_ap_ready;
wire    grp_DECIMATOR_fu_138_input_r_TREADY;
wire   [15:0] grp_DECIMATOR_fu_138_dec_out_din;
wire    grp_DECIMATOR_fu_138_dec_out_write;
wire    grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_start;
wire    grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_done;
wire    grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_idle;
wire    grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_ready;
wire   [6:0] grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_address0;
wire    grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_ce0;
wire    grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_we0;
wire   [31:0] grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_d0;
wire   [6:0] grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_address1;
wire    grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_ce1;
wire    grp_INTERPOLATOR_fu_179_ap_start;
wire    grp_INTERPOLATOR_fu_179_ap_done;
wire    grp_INTERPOLATOR_fu_179_ap_idle;
wire    grp_INTERPOLATOR_fu_179_ap_ready;
wire   [15:0] grp_INTERPOLATOR_fu_179_output_r_TDATA;
wire    grp_INTERPOLATOR_fu_179_output_r_TVALID;
wire    grp_INTERPOLATOR_fu_179_output_r_TREADY;
wire    grp_INTERPOLATOR_fu_179_kernel_out_read;
reg   [15:0] storemerge_i_i_reg_127;
wire    ap_CS_fsm_state6;
reg    ap_block_state6_on_subcall_done;
reg    grp_DECIMATOR_fu_138_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_start_reg;
reg    grp_INTERPOLATOR_fu_179_ap_start_reg;
reg   [15:0] output_r_TDATA_reg;
wire    ap_CS_fsm_state7;
reg    H_accu_FIR_kernel_ce0_local;
wire   [17:0] tmp_fu_231_p3;
wire   [22:0] p_shl_fu_223_p3;
wire  signed [22:0] sext_ln39_fu_239_p1;
wire   [22:0] sub_ln39_fu_243_p2;
wire  signed [31:0] sext_ln39_4_fu_249_p1;
wire   [31:0] add_ln39_fu_253_p2;
wire    ap_CS_fsm_state8;
wire    regslice_both_output_r_U_apdone_blk;
reg   [7:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    regslice_both_input_r_U_apdone_blk;
wire   [15:0] input_r_TDATA_int_regslice;
wire    input_r_TVALID_int_regslice;
reg    input_r_TREADY_int_regslice;
wire    regslice_both_input_r_U_ack_in;
reg   [15:0] output_r_TDATA_int_regslice;
wire    output_r_TREADY_int_regslice;
wire    regslice_both_output_r_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 mod_value_1 = 16'd0;
#0 grp_DECIMATOR_fu_138_ap_start_reg = 1'b0;
#0 grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_start_reg = 1'b0;
#0 grp_INTERPOLATOR_fu_179_ap_start_reg = 1'b0;
end

FIR_HLS_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_H_accu_FIR_kernel_RAM_AUTO_cud #(
    .DataWidth( 32 ),
    .AddressRange( 117 ),
    .AddressWidth( 7 ))
H_accu_FIR_kernel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(H_accu_FIR_kernel_address0),
    .ce0(H_accu_FIR_kernel_ce0),
    .we0(grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_we0),
    .d0(grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_d0),
    .q0(H_accu_FIR_kernel_q0),
    .address1(grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_address1),
    .ce1(grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_ce1),
    .q1(H_accu_FIR_kernel_q1)
);

FIR_HLS_DECIMATOR grp_DECIMATOR_fu_138(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DECIMATOR_fu_138_ap_start),
    .ap_done(grp_DECIMATOR_fu_138_ap_done),
    .ap_idle(grp_DECIMATOR_fu_138_ap_idle),
    .ap_ready(grp_DECIMATOR_fu_138_ap_ready),
    .input_r_TDATA(input_r_TDATA_int_regslice),
    .input_r_TVALID(input_r_TVALID_int_regslice),
    .input_r_TREADY(grp_DECIMATOR_fu_138_input_r_TREADY),
    .dec_out_din(grp_DECIMATOR_fu_138_dec_out_din),
    .dec_out_full_n(dec_out_full_n),
    .dec_out_write(grp_DECIMATOR_fu_138_dec_out_write)
);

FIR_HLS_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1 grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_start),
    .ap_done(grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_done),
    .ap_idle(grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_idle),
    .ap_ready(grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_ready),
    .sext_ln42(x_n_reg_296),
    .H_accu_FIR_kernel_address0(grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_address0),
    .H_accu_FIR_kernel_ce0(grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_ce0),
    .H_accu_FIR_kernel_we0(grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_we0),
    .H_accu_FIR_kernel_d0(grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_d0),
    .H_accu_FIR_kernel_address1(grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_address1),
    .H_accu_FIR_kernel_ce1(grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_ce1),
    .H_accu_FIR_kernel_q1(H_accu_FIR_kernel_q1)
);

FIR_HLS_INTERPOLATOR grp_INTERPOLATOR_fu_179(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_INTERPOLATOR_fu_179_ap_start),
    .ap_done(grp_INTERPOLATOR_fu_179_ap_done),
    .ap_idle(grp_INTERPOLATOR_fu_179_ap_idle),
    .ap_ready(grp_INTERPOLATOR_fu_179_ap_ready),
    .output_r_TDATA(grp_INTERPOLATOR_fu_179_output_r_TDATA),
    .output_r_TVALID(grp_INTERPOLATOR_fu_179_output_r_TVALID),
    .output_r_TREADY(grp_INTERPOLATOR_fu_179_output_r_TREADY),
    .kernel_out_dout(kernel_out_dout),
    .kernel_out_empty_n(kernel_out_empty_n),
    .kernel_out_read(grp_INTERPOLATOR_fu_179_kernel_out_read)
);

FIR_HLS_regslice_both #(
    .DataWidth( 16 ))
regslice_both_input_r_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(input_r_TDATA),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_U_ack_in),
    .data_out(input_r_TDATA_int_regslice),
    .vld_out(input_r_TVALID_int_regslice),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_U_apdone_blk)
);

FIR_HLS_regslice_both #(
    .DataWidth( 16 ))
regslice_both_output_r_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(output_r_TDATA_int_regslice),
    .vld_in(grp_INTERPOLATOR_fu_179_output_r_TVALID),
    .ack_in(output_r_TREADY_int_regslice),
    .data_out(output_r_TDATA),
    .vld_out(regslice_both_output_r_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((regslice_both_output_r_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_start_reg <= 1'b0;
    end else begin
        if (((kernel_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_start_reg <= 1'b1;
        end else if ((grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_ready == 1'b1)) begin
            grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DECIMATOR_fu_138_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_DECIMATOR_fu_138_ap_start_reg <= 1'b1;
        end else if ((grp_DECIMATOR_fu_138_ap_ready == 1'b1)) begin
            grp_DECIMATOR_fu_138_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_INTERPOLATOR_fu_179_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
            grp_INTERPOLATOR_fu_179_ap_start_reg <= 1'b1;
        end else if ((grp_INTERPOLATOR_fu_179_ap_ready == 1'b1)) begin
            grp_INTERPOLATOR_fu_179_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln19_reg_287 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
        storemerge_i_i_reg_127 <= 16'd3;
    end else if (((grp_DECIMATOR_fu_138_ap_done == 1'b1) & (icmp_ln19_fu_211_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        storemerge_i_i_reg_127 <= add_ln24_fu_217_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DECIMATOR_fu_138_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_ln19_reg_287 <= icmp_ln19_fu_211_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_INTERPOLATOR_fu_179_ap_done == 1'b1))) begin
        mod_value_1 <= storemerge_i_i_reg_127;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_INTERPOLATOR_fu_179_output_r_TVALID == 1'b1))) begin
        output_r_TDATA_reg <= grp_INTERPOLATOR_fu_179_output_r_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((dec_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        x_n_reg_296 <= dec_out_dout;
        y_reg_301 <= {{add_ln39_fu_253_p2[31:16]}};
    end
end

always @ (*) begin
    if (((icmp_ln19_reg_287 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        H_accu_FIR_kernel_address0 = grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_address0;
    end else begin
        H_accu_FIR_kernel_address0 = 7'd0;
    end
end

always @ (*) begin
    if (((icmp_ln19_reg_287 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        H_accu_FIR_kernel_ce0 = grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_H_accu_FIR_kernel_ce0;
    end else begin
        H_accu_FIR_kernel_ce0 = H_accu_FIR_kernel_ce0_local;
    end
end

always @ (*) begin
    if (((grp_DECIMATOR_fu_138_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        H_accu_FIR_kernel_ce0_local = 1'b1;
    end else begin
        H_accu_FIR_kernel_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_DECIMATOR_fu_138_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((dec_out_empty_n == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((kernel_out_full_n == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state6_on_subcall_done)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_INTERPOLATOR_fu_179_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_output_r_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_output_r_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_output_r_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dec_out_i_blk_n = dec_out_empty_n;
    end else begin
        dec_out_i_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((dec_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        dec_out_read = 1'b1;
    end else begin
        dec_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        dec_out_write = grp_DECIMATOR_fu_138_dec_out_write;
    end else begin
        dec_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_TREADY_int_regslice = grp_DECIMATOR_fu_138_input_r_TREADY;
    end else begin
        input_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        kernel_out_o_blk_n = kernel_out_full_n;
    end else begin
        kernel_out_o_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        kernel_out_read = grp_INTERPOLATOR_fu_179_kernel_out_read;
    end else begin
        kernel_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((kernel_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        kernel_out_write = 1'b1;
    end else begin
        kernel_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_INTERPOLATOR_fu_179_output_r_TVALID == 1'b1))) begin
        output_r_TDATA_int_regslice = grp_INTERPOLATOR_fu_179_output_r_TDATA;
    end else begin
        output_r_TDATA_int_regslice = output_r_TDATA_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_DECIMATOR_fu_138_ap_done == 1'b1) & (icmp_ln19_fu_211_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((grp_DECIMATOR_fu_138_ap_done == 1'b1) & (icmp_ln19_fu_211_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((dec_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((kernel_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_INTERPOLATOR_fu_179_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((regslice_both_output_r_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln24_fu_217_p2 = ($signed(mod_value_1) + $signed(16'd65535));

assign add_ln39_fu_253_p2 = ($signed(H_accu_FIR_kernel_q0) + $signed(sext_ln39_4_fu_249_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state6_on_subcall_done = ((icmp_ln19_reg_287 == 1'd1) & (grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_done == 1'b0));
end

assign dec_out_din = grp_DECIMATOR_fu_138_dec_out_din;

assign grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_start = grp_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_fu_170_ap_start_reg;

assign grp_DECIMATOR_fu_138_ap_start = grp_DECIMATOR_fu_138_ap_start_reg;

assign grp_INTERPOLATOR_fu_179_ap_start = grp_INTERPOLATOR_fu_179_ap_start_reg;

assign grp_INTERPOLATOR_fu_179_output_r_TREADY = (output_r_TREADY_int_regslice & ap_CS_fsm_state7);

assign icmp_ln19_fu_211_p2 = ((mod_value_1 == 16'd0) ? 1'b1 : 1'b0);

assign input_r_TREADY = regslice_both_input_r_U_ack_in;

assign kernel_out_din = y_reg_301;

assign output_r_TVALID = regslice_both_output_r_U_vld_out;

assign p_shl_fu_223_p3 = {{dec_out_dout}, {7'd0}};

assign sext_ln39_4_fu_249_p1 = $signed(sub_ln39_fu_243_p2);

assign sext_ln39_fu_239_p1 = $signed(tmp_fu_231_p3);

assign sub_ln39_fu_243_p2 = ($signed(p_shl_fu_223_p3) - $signed(sext_ln39_fu_239_p1));

assign tmp_fu_231_p3 = {{dec_out_dout}, {2'd0}};

endmodule //FIR_HLS_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc
