// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module FIR_HLS_DECIMATOR (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_TDATA,
        input_r_TVALID,
        input_r_TREADY,
        dec_out_din,
        dec_out_full_n,
        dec_out_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] input_r_TDATA;
input   input_r_TVALID;
output   input_r_TREADY;
output  [15:0] dec_out_din;
input   dec_out_full_n;
output   dec_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_TREADY;
reg dec_out_write;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [1:0] mod_value_2;
reg   [2:0] H_accu_FIR_dec_40_address0;
reg    H_accu_FIR_dec_40_ce0;
wire   [31:0] H_accu_FIR_dec_40_q0;
wire   [31:0] H_accu_FIR_dec_40_q1;
reg   [15:0] y1_phase1;
reg   [15:0] y1_phase2;
reg   [15:0] y1_phase3;
reg    H_accu_FIR_dec_43_ce0;
reg    H_accu_FIR_dec_43_we0;
wire   [31:0] H_accu_FIR_dec_43_q0;
reg    H_accu_FIR_dec_43_ce1;
wire   [31:0] H_accu_FIR_dec_43_q1;
reg    b_FIR_dec_int_43_ce0;
wire   [14:0] b_FIR_dec_int_43_q0;
reg    H_accu_FIR_dec_42_ce0;
reg    H_accu_FIR_dec_42_we0;
wire   [31:0] H_accu_FIR_dec_42_q0;
reg    H_accu_FIR_dec_42_ce1;
wire   [31:0] H_accu_FIR_dec_42_q1;
reg    b_FIR_dec_int_42_ce0;
wire   [14:0] b_FIR_dec_int_42_q0;
reg    H_accu_FIR_dec_41_ce0;
reg    H_accu_FIR_dec_41_we0;
wire   [31:0] H_accu_FIR_dec_41_q0;
reg    H_accu_FIR_dec_41_ce1;
wire   [31:0] H_accu_FIR_dec_41_q1;
reg    b_FIR_dec_int_41_ce0;
wire   [14:0] b_FIR_dec_int_41_q0;
reg    input_r_TDATA_blk_n;
reg    dec_out_blk_n;
wire    ap_CS_fsm_state5;
reg   [1:0] mod_value_2_load_reg_228;
reg   [15:0] reg_132;
reg  signed [31:0] H_accu_FIR_dec_40_load_reg_237;
wire    ap_CS_fsm_state3;
wire    grp_FIR_filter_2_fu_109_ap_start;
wire    grp_FIR_filter_2_fu_109_ap_done;
wire    grp_FIR_filter_2_fu_109_ap_idle;
wire    grp_FIR_filter_2_fu_109_ap_ready;
wire   [2:0] grp_FIR_filter_2_fu_109_FIR_delays_address0;
wire    grp_FIR_filter_2_fu_109_FIR_delays_ce0;
wire    grp_FIR_filter_2_fu_109_FIR_delays_we0;
wire   [31:0] grp_FIR_filter_2_fu_109_FIR_delays_d0;
reg   [31:0] grp_FIR_filter_2_fu_109_FIR_delays_q0;
wire   [2:0] grp_FIR_filter_2_fu_109_FIR_delays_address1;
wire    grp_FIR_filter_2_fu_109_FIR_delays_ce1;
reg   [31:0] grp_FIR_filter_2_fu_109_FIR_delays_q1;
wire   [2:0] grp_FIR_filter_2_fu_109_FIR_coe_address0;
wire    grp_FIR_filter_2_fu_109_FIR_coe_ce0;
reg   [14:0] grp_FIR_filter_2_fu_109_FIR_coe_q0;
wire   [15:0] grp_FIR_filter_2_fu_109_ap_return;
wire    grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start;
wire    grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_done;
wire    grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_idle;
wire    grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_ready;
wire   [2:0] grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_address0;
wire    grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_ce0;
wire    grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_we0;
wire   [31:0] grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_d0;
wire   [2:0] grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_address1;
wire    grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_ce1;
reg   [1:0] ap_phi_mux_storemerge2_i_phi_fu_95_p8;
reg   [1:0] storemerge2_i_reg_89;
reg    ap_block_state5;
reg    ap_block_state5_on_subcall_done;
wire    ap_CS_fsm_state2;
reg    ap_block_state2_on_subcall_done;
wire    ap_CS_fsm_state6;
reg    grp_FIR_filter_2_fu_109_ap_start_reg;
reg    ap_block_state1_ignore_call1;
reg    grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    ap_block_state1;
reg    H_accu_FIR_dec_40_ce0_local;
wire  signed [15:0] sext_ln39_fu_142_p0;
wire  signed [31:0] grp_fu_220_p3;
wire   [15:0] y_fu_168_p4;
wire   [15:0] add_ln60_1_fu_195_p2;
wire   [15:0] add_ln60_fu_189_p2;
wire   [8:0] grp_fu_220_p1;
reg    grp_fu_220_ce;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 mod_value_2 = 2'd0;
#0 y1_phase1 = 16'd0;
#0 y1_phase2 = 16'd0;
#0 y1_phase3 = 16'd0;
#0 grp_FIR_filter_2_fu_109_ap_start_reg = 1'b0;
#0 grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start_reg = 1'b0;
end

FIR_HLS_DECIMATOR_H_accu_FIR_dec_40_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
H_accu_FIR_dec_40_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(H_accu_FIR_dec_40_address0),
    .ce0(H_accu_FIR_dec_40_ce0),
    .we0(grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_we0),
    .d0(grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_d0),
    .q0(H_accu_FIR_dec_40_q0),
    .address1(grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_address1),
    .ce1(grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_ce1),
    .q1(H_accu_FIR_dec_40_q1)
);

FIR_HLS_DECIMATOR_H_accu_FIR_dec_43_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
H_accu_FIR_dec_43_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_FIR_filter_2_fu_109_FIR_delays_address0),
    .ce0(H_accu_FIR_dec_43_ce0),
    .we0(H_accu_FIR_dec_43_we0),
    .d0(grp_FIR_filter_2_fu_109_FIR_delays_d0),
    .q0(H_accu_FIR_dec_43_q0),
    .address1(grp_FIR_filter_2_fu_109_FIR_delays_address1),
    .ce1(H_accu_FIR_dec_43_ce1),
    .q1(H_accu_FIR_dec_43_q1)
);

FIR_HLS_DECIMATOR_b_FIR_dec_int_43_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
b_FIR_dec_int_43_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_FIR_filter_2_fu_109_FIR_coe_address0),
    .ce0(b_FIR_dec_int_43_ce0),
    .q0(b_FIR_dec_int_43_q0)
);

FIR_HLS_DECIMATOR_H_accu_FIR_dec_43_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
H_accu_FIR_dec_42_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_FIR_filter_2_fu_109_FIR_delays_address0),
    .ce0(H_accu_FIR_dec_42_ce0),
    .we0(H_accu_FIR_dec_42_we0),
    .d0(grp_FIR_filter_2_fu_109_FIR_delays_d0),
    .q0(H_accu_FIR_dec_42_q0),
    .address1(grp_FIR_filter_2_fu_109_FIR_delays_address1),
    .ce1(H_accu_FIR_dec_42_ce1),
    .q1(H_accu_FIR_dec_42_q1)
);

FIR_HLS_DECIMATOR_b_FIR_dec_int_42_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
b_FIR_dec_int_42_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_FIR_filter_2_fu_109_FIR_coe_address0),
    .ce0(b_FIR_dec_int_42_ce0),
    .q0(b_FIR_dec_int_42_q0)
);

FIR_HLS_DECIMATOR_H_accu_FIR_dec_43_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
H_accu_FIR_dec_41_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_FIR_filter_2_fu_109_FIR_delays_address0),
    .ce0(H_accu_FIR_dec_41_ce0),
    .we0(H_accu_FIR_dec_41_we0),
    .d0(grp_FIR_filter_2_fu_109_FIR_delays_d0),
    .q0(H_accu_FIR_dec_41_q0),
    .address1(grp_FIR_filter_2_fu_109_FIR_delays_address1),
    .ce1(H_accu_FIR_dec_41_ce1),
    .q1(H_accu_FIR_dec_41_q1)
);

FIR_HLS_DECIMATOR_b_FIR_dec_int_41_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
b_FIR_dec_int_41_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_FIR_filter_2_fu_109_FIR_coe_address0),
    .ce0(b_FIR_dec_int_41_ce0),
    .q0(b_FIR_dec_int_41_q0)
);

FIR_HLS_FIR_filter_2 grp_FIR_filter_2_fu_109(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_FIR_filter_2_fu_109_ap_start),
    .ap_done(grp_FIR_filter_2_fu_109_ap_done),
    .ap_idle(grp_FIR_filter_2_fu_109_ap_idle),
    .ap_ready(grp_FIR_filter_2_fu_109_ap_ready),
    .FIR_delays_address0(grp_FIR_filter_2_fu_109_FIR_delays_address0),
    .FIR_delays_ce0(grp_FIR_filter_2_fu_109_FIR_delays_ce0),
    .FIR_delays_we0(grp_FIR_filter_2_fu_109_FIR_delays_we0),
    .FIR_delays_d0(grp_FIR_filter_2_fu_109_FIR_delays_d0),
    .FIR_delays_q0(grp_FIR_filter_2_fu_109_FIR_delays_q0),
    .FIR_delays_address1(grp_FIR_filter_2_fu_109_FIR_delays_address1),
    .FIR_delays_ce1(grp_FIR_filter_2_fu_109_FIR_delays_ce1),
    .FIR_delays_q1(grp_FIR_filter_2_fu_109_FIR_delays_q1),
    .FIR_coe_address0(grp_FIR_filter_2_fu_109_FIR_coe_address0),
    .FIR_coe_ce0(grp_FIR_filter_2_fu_109_FIR_coe_ce0),
    .FIR_coe_q0(grp_FIR_filter_2_fu_109_FIR_coe_q0),
    .x_n(reg_132),
    .ap_return(grp_FIR_filter_2_fu_109_ap_return)
);

FIR_HLS_DECIMATOR_Pipeline_VITIS_LOOP_41_1 grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start),
    .ap_done(grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_done),
    .ap_idle(grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_idle),
    .ap_ready(grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_ready),
    .sext_ln42(reg_132),
    .H_accu_FIR_dec_40_address0(grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_address0),
    .H_accu_FIR_dec_40_ce0(grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_ce0),
    .H_accu_FIR_dec_40_we0(grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_we0),
    .H_accu_FIR_dec_40_d0(grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_d0),
    .H_accu_FIR_dec_40_address1(grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_address1),
    .H_accu_FIR_dec_40_ce1(grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_ce1),
    .H_accu_FIR_dec_40_q1(H_accu_FIR_dec_40_q1)
);

FIR_HLS_mac_muladd_16s_9ns_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_9ns_32s_32_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln39_fu_142_p0),
    .din1(grp_fu_220_p1),
    .din2(H_accu_FIR_dec_40_load_reg_237),
    .ce(grp_fu_220_ce),
    .dout(grp_fu_220_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start_reg <= 1'b1;
        end else if ((grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_ready == 1'b1)) begin
            grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_FIR_filter_2_fu_109_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_state1_ignore_call1) & (1'b1 == ap_CS_fsm_state1) & (mod_value_2 == 2'd3)) | ((1'b0 == ap_block_state1_ignore_call1) & (1'b1 == ap_CS_fsm_state1) & (mod_value_2 == 2'd2)) | ((1'b0 == ap_block_state1_ignore_call1) & (1'b1 == ap_CS_fsm_state1) & (mod_value_2 == 2'd1)))) begin
            grp_FIR_filter_2_fu_109_ap_start_reg <= 1'b1;
        end else if ((grp_FIR_filter_2_fu_109_ap_ready == 1'b1)) begin
            grp_FIR_filter_2_fu_109_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd2))) begin
        storemerge2_i_reg_89 <= 2'd3;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_FIR_filter_2_fu_109_ap_done == 1'b1))) begin
        storemerge2_i_reg_89 <= 2'd0;
    end else if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd1))) begin
        storemerge2_i_reg_89 <= 2'd2;
    end else if ((~((1'b1 == ap_block_state5_on_subcall_done) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5) & (mod_value_2_load_reg_228 == 2'd0))) begin
        storemerge2_i_reg_89 <= 2'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        H_accu_FIR_dec_40_load_reg_237 <= H_accu_FIR_dec_40_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state5_on_subcall_done) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5))) begin
        mod_value_2 <= ap_phi_mux_storemerge2_i_phi_fu_95_p8;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        mod_value_2_load_reg_228 <= mod_value_2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (mod_value_2 == 2'd3)) | ((1'b1 == ap_CS_fsm_state1) & (mod_value_2 == 2'd2)) | ((1'b1 == ap_CS_fsm_state1) & (mod_value_2 == 2'd1)) | ((1'b1 == ap_CS_fsm_state1) & (mod_value_2 == 2'd0)))) begin
        reg_132 <= input_r_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd1))) begin
        y1_phase1 <= grp_FIR_filter_2_fu_109_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd2))) begin
        y1_phase2 <= grp_FIR_filter_2_fu_109_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_FIR_filter_2_fu_109_ap_done == 1'b1))) begin
        y1_phase3 <= grp_FIR_filter_2_fu_109_ap_return;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (mod_value_2_load_reg_228 == 2'd0))) begin
        H_accu_FIR_dec_40_address0 = grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_address0;
    end else begin
        H_accu_FIR_dec_40_address0 = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (mod_value_2_load_reg_228 == 2'd0))) begin
        H_accu_FIR_dec_40_ce0 = grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_ce0;
    end else begin
        H_accu_FIR_dec_40_ce0 = H_accu_FIR_dec_40_ce0_local;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        H_accu_FIR_dec_40_ce0_local = 1'b1;
    end else begin
        H_accu_FIR_dec_40_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_accu_FIR_dec_41_ce0 = grp_FIR_filter_2_fu_109_FIR_delays_ce0;
    end else begin
        H_accu_FIR_dec_41_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_accu_FIR_dec_41_ce1 = grp_FIR_filter_2_fu_109_FIR_delays_ce1;
    end else begin
        H_accu_FIR_dec_41_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_accu_FIR_dec_41_we0 = grp_FIR_filter_2_fu_109_FIR_delays_we0;
    end else begin
        H_accu_FIR_dec_41_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd2))) begin
        H_accu_FIR_dec_42_ce0 = grp_FIR_filter_2_fu_109_FIR_delays_ce0;
    end else begin
        H_accu_FIR_dec_42_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd2))) begin
        H_accu_FIR_dec_42_ce1 = grp_FIR_filter_2_fu_109_FIR_delays_ce1;
    end else begin
        H_accu_FIR_dec_42_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd2))) begin
        H_accu_FIR_dec_42_we0 = grp_FIR_filter_2_fu_109_FIR_delays_we0;
    end else begin
        H_accu_FIR_dec_42_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd1))) begin
        H_accu_FIR_dec_43_ce0 = grp_FIR_filter_2_fu_109_FIR_delays_ce0;
    end else begin
        H_accu_FIR_dec_43_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd1))) begin
        H_accu_FIR_dec_43_ce1 = grp_FIR_filter_2_fu_109_FIR_delays_ce1;
    end else begin
        H_accu_FIR_dec_43_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd1))) begin
        H_accu_FIR_dec_43_we0 = grp_FIR_filter_2_fu_109_FIR_delays_we0;
    end else begin
        H_accu_FIR_dec_43_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state5_on_subcall_done) | (1'b1 == ap_block_state5))) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_FIR_filter_2_fu_109_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | (~((1'b1 == ap_block_state5_on_subcall_done) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (mod_value_2_load_reg_228 == 2'd0))) begin
        ap_phi_mux_storemerge2_i_phi_fu_95_p8 = 2'd1;
    end else begin
        ap_phi_mux_storemerge2_i_phi_fu_95_p8 = storemerge2_i_reg_89;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state5_on_subcall_done) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        b_FIR_dec_int_41_ce0 = grp_FIR_filter_2_fu_109_FIR_coe_ce0;
    end else begin
        b_FIR_dec_int_41_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd2))) begin
        b_FIR_dec_int_42_ce0 = grp_FIR_filter_2_fu_109_FIR_coe_ce0;
    end else begin
        b_FIR_dec_int_42_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd1))) begin
        b_FIR_dec_int_43_ce0 = grp_FIR_filter_2_fu_109_FIR_coe_ce0;
    end else begin
        b_FIR_dec_int_43_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (mod_value_2_load_reg_228 == 2'd0))) begin
        dec_out_blk_n = dec_out_full_n;
    end else begin
        dec_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state5_on_subcall_done) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5) & (mod_value_2_load_reg_228 == 2'd0))) begin
        dec_out_write = 1'b1;
    end else begin
        dec_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_FIR_filter_2_fu_109_FIR_coe_q0 = b_FIR_dec_int_41_q0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd1))) begin
        grp_FIR_filter_2_fu_109_FIR_coe_q0 = b_FIR_dec_int_43_q0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd2))) begin
        grp_FIR_filter_2_fu_109_FIR_coe_q0 = b_FIR_dec_int_42_q0;
    end else begin
        grp_FIR_filter_2_fu_109_FIR_coe_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_FIR_filter_2_fu_109_FIR_delays_q0 = H_accu_FIR_dec_41_q0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd1))) begin
        grp_FIR_filter_2_fu_109_FIR_delays_q0 = H_accu_FIR_dec_43_q0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd2))) begin
        grp_FIR_filter_2_fu_109_FIR_delays_q0 = H_accu_FIR_dec_42_q0;
    end else begin
        grp_FIR_filter_2_fu_109_FIR_delays_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_FIR_filter_2_fu_109_FIR_delays_q1 = H_accu_FIR_dec_41_q1;
    end else if (((1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd1))) begin
        grp_FIR_filter_2_fu_109_FIR_delays_q1 = H_accu_FIR_dec_43_q1;
    end else if (((1'b1 == ap_CS_fsm_state2) & (mod_value_2_load_reg_228 == 2'd2))) begin
        grp_FIR_filter_2_fu_109_FIR_delays_q1 = H_accu_FIR_dec_42_q1;
    end else begin
        grp_FIR_filter_2_fu_109_FIR_delays_q1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)) | (~((1'b1 == ap_block_state5_on_subcall_done) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5)))) begin
        grp_fu_220_ce = 1'b1;
    end else begin
        grp_fu_220_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (mod_value_2 == 2'd3)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (mod_value_2 == 2'd2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (mod_value_2 == 2'd1)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (mod_value_2 == 2'd0)))) begin
        input_r_TDATA_blk_n = input_r_TVALID;
    end else begin
        input_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1) & (mod_value_2 == 2'd3)) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1) & (mod_value_2 == 2'd2)) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1) & (mod_value_2 == 2'd1)) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1) & (mod_value_2 == 2'd0)))) begin
        input_r_TREADY = 1'b1;
    end else begin
        input_r_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1) & (mod_value_2 == 2'd3))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1) & (mod_value_2 == 2'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1) & ((mod_value_2 == 2'd2) | (mod_value_2 == 2'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & ((mod_value_2_load_reg_228 == 2'd2) | (mod_value_2_load_reg_228 == 2'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if ((~((1'b1 == ap_block_state5_on_subcall_done) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_FIR_filter_2_fu_109_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln60_1_fu_195_p2 = (y1_phase3 + y_fu_168_p4);

assign add_ln60_fu_189_p2 = (y1_phase1 + y1_phase2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | ((input_r_TVALID == 1'b0) & (mod_value_2 == 2'd3)) | ((input_r_TVALID == 1'b0) & (mod_value_2 == 2'd2)) | ((input_r_TVALID == 1'b0) & (mod_value_2 == 2'd1)) | ((input_r_TVALID == 1'b0) & (mod_value_2 == 2'd0)));
end

always @ (*) begin
    ap_block_state1_ignore_call1 = ((ap_start == 1'b0) | ((input_r_TVALID == 1'b0) & (mod_value_2 == 2'd3)) | ((input_r_TVALID == 1'b0) & (mod_value_2 == 2'd2)) | ((input_r_TVALID == 1'b0) & (mod_value_2 == 2'd1)) | ((input_r_TVALID == 1'b0) & (mod_value_2 == 2'd0)));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = (((grp_FIR_filter_2_fu_109_ap_done == 1'b0) & (mod_value_2_load_reg_228 == 2'd2)) | ((grp_FIR_filter_2_fu_109_ap_done == 1'b0) & (mod_value_2_load_reg_228 == 2'd1)));
end

always @ (*) begin
    ap_block_state5 = ((dec_out_full_n == 1'b0) & (mod_value_2_load_reg_228 == 2'd0));
end

always @ (*) begin
    ap_block_state5_on_subcall_done = ((grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_done == 1'b0) & (mod_value_2_load_reg_228 == 2'd0));
end

assign dec_out_din = (add_ln60_1_fu_195_p2 + add_ln60_fu_189_p2);

assign grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start = grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start_reg;

assign grp_FIR_filter_2_fu_109_ap_start = grp_FIR_filter_2_fu_109_ap_start_reg;

assign grp_fu_220_p1 = 25'd436;

assign sext_ln39_fu_142_p0 = input_r_TDATA;

assign y_fu_168_p4 = {{grp_fu_220_p3[31:16]}};

endmodule //FIR_HLS_DECIMATOR
