set SynModuleInfo {
  {SRCNAME FIR_filter.1 MODELNAME FIR_filter_1 RTLNAME FIR_HLS_FIR_filter_1
    SUBMODULES {
      {MODELNAME FIR_HLS_mul_32s_10s_42_1_1 RTLNAME FIR_HLS_mul_32s_10s_42_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_mul_32s_13s_44_1_1 RTLNAME FIR_HLS_mul_32s_13s_44_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_mul_32s_13s_45_1_1 RTLNAME FIR_HLS_mul_32s_13s_45_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_mul_32s_14ns_46_1_1 RTLNAME FIR_HLS_mul_32s_14ns_46_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME FIR_filter.2 MODELNAME FIR_filter_2 RTLNAME FIR_HLS_FIR_filter_2
    SUBMODULES {
      {MODELNAME FIR_HLS_mul_32s_12s_43_1_1 RTLNAME FIR_HLS_mul_32s_12s_43_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_mul_32s_12s_44_1_1 RTLNAME FIR_HLS_mul_32s_12s_44_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME DECIMATOR MODELNAME DECIMATOR RTLNAME FIR_HLS_DECIMATOR}
  {SRCNAME FIR_filter MODELNAME FIR_filter RTLNAME FIR_HLS_FIR_filter
    SUBMODULES {
      {MODELNAME FIR_HLS_mul_32s_6s_38_1_1 RTLNAME FIR_HLS_mul_32s_6s_38_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_mul_32s_7s_39_1_1 RTLNAME FIR_HLS_mul_32s_7s_39_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_mul_32s_8s_40_1_1 RTLNAME FIR_HLS_mul_32s_8s_40_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_mul_32s_9s_41_1_1 RTLNAME FIR_HLS_mul_32s_9s_41_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_mul_32s_11s_43_1_1 RTLNAME FIR_HLS_mul_32s_11s_43_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME INTERPOLATOR MODELNAME INTERPOLATOR RTLNAME FIR_HLS_INTERPOLATOR}
  {SRCNAME Block_entry__ZL16b_FIR_dec_int_43_0_rd_mod_value_fb_proc MODELNAME Block_entry_ZL16b_FIR_dec_int_43_0_rd_mod_value_fb_proc RTLNAME FIR_HLS_Block_entry_ZL16b_FIR_dec_int_43_0_rd_mod_value_fb_proc
    SUBMODULES {
      {MODELNAME FIR_HLS_regslice_both RTLNAME FIR_HLS_regslice_both BINDTYPE interface TYPE adapter IMPL reg_slice}
    }
  }
  {SRCNAME FIR_HLS MODELNAME FIR_HLS RTLNAME FIR_HLS IS_TOP 1}
}
