set SynModuleInfo {
  {SRCNAME HLS_FIR_Pipeline_VITIS_LOOP_30_1 MODELNAME HLS_FIR_Pipeline_VITIS_LOOP_30_1 RTLNAME HLS_FIR_HLS_FIR_Pipeline_VITIS_LOOP_30_1
    SUBMODULES {
      {MODELNAME HLS_FIR_mac_muladd_16s_14s_32s_32_4_1 RTLNAME HLS_FIR_mac_muladd_16s_14s_32s_32_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME HLS_FIR_HLS_FIR_Pipeline_VITIS_LOOP_30_1_b_FIR_ROM_AUTO_1R RTLNAME HLS_FIR_HLS_FIR_Pipeline_VITIS_LOOP_30_1_b_FIR_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME HLS_FIR_flow_control_loop_pipe_sequential_init RTLNAME HLS_FIR_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME HLS_FIR_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME HLS_FIR_Pipeline_VITIS_LOOP_36_2 MODELNAME HLS_FIR_Pipeline_VITIS_LOOP_36_2 RTLNAME HLS_FIR_HLS_FIR_Pipeline_VITIS_LOOP_36_2}
  {SRCNAME HLS_FIR MODELNAME HLS_FIR RTLNAME HLS_FIR IS_TOP 1
    SUBMODULES {
      {MODELNAME HLS_FIR_H_filt_FIR_RAM_AUTO_1R1W RTLNAME HLS_FIR_H_filt_FIR_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME HLS_FIR_regslice_both RTLNAME HLS_FIR_regslice_both BINDTYPE interface TYPE adapter IMPL reg_slice}
    }
  }
}
