set SynModuleInfo {
  {SRCNAME FIR_filter.2_Pipeline_VITIS_LOOP_41_1 MODELNAME FIR_filter_2_Pipeline_VITIS_LOOP_41_1 RTLNAME FIR_HLS_FIR_filter_2_Pipeline_VITIS_LOOP_41_1
    SUBMODULES {
      {MODELNAME FIR_HLS_mul_16s_15s_31_1_1 RTLNAME FIR_HLS_mul_16s_15s_31_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_flow_control_loop_pipe_sequential_init RTLNAME FIR_HLS_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME FIR_HLS_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME FIR_filter.2 MODELNAME FIR_filter_2 RTLNAME FIR_HLS_FIR_filter_2}
  {SRCNAME DECIMATOR_Pipeline_VITIS_LOOP_41_1 MODELNAME DECIMATOR_Pipeline_VITIS_LOOP_41_1 RTLNAME FIR_HLS_DECIMATOR_Pipeline_VITIS_LOOP_41_1
    SUBMODULES {
      {MODELNAME FIR_HLS_mul_16s_14s_30_1_1 RTLNAME FIR_HLS_mul_16s_14s_30_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_DECIMATOR_Pipeline_VITIS_LOOP_41_1_b_FIR_dec_int_40_ROM_AUTO_1R RTLNAME FIR_HLS_DECIMATOR_Pipeline_VITIS_LOOP_41_1_b_FIR_dec_int_40_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME DECIMATOR MODELNAME DECIMATOR RTLNAME FIR_HLS_DECIMATOR
    SUBMODULES {
      {MODELNAME FIR_HLS_mac_muladd_16s_9ns_32s_32_4_1 RTLNAME FIR_HLS_mac_muladd_16s_9ns_32s_32_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME FIR_HLS_DECIMATOR_H_accu_FIR_dec_40_RAM_AUTO_1R1W RTLNAME FIR_HLS_DECIMATOR_H_accu_FIR_dec_40_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_DECIMATOR_H_accu_FIR_dec_43_RAM_AUTO_1R1W RTLNAME FIR_HLS_DECIMATOR_H_accu_FIR_dec_43_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_DECIMATOR_b_FIR_dec_int_43_ROM_AUTO_1R RTLNAME FIR_HLS_DECIMATOR_b_FIR_dec_int_43_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_DECIMATOR_b_FIR_dec_int_42_ROM_AUTO_1R RTLNAME FIR_HLS_DECIMATOR_b_FIR_dec_int_42_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_DECIMATOR_b_FIR_dec_int_41_ROM_AUTO_1R RTLNAME FIR_HLS_DECIMATOR_b_FIR_dec_int_41_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1 MODELNAME Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1 RTLNAME FIR_HLS_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1
    SUBMODULES {
      {MODELNAME FIR_HLS_mul_16s_16s_31_1_1 RTLNAME FIR_HLS_mul_16s_16s_31_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_b_bkb RTLNAME FIR_HLS_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_Pipeline_VITIS_LOOP_41_1_b_bkb BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME INTERPOLATOR_Pipeline_VITIS_LOOP_41_1 MODELNAME INTERPOLATOR_Pipeline_VITIS_LOOP_41_1 RTLNAME FIR_HLS_INTERPOLATOR_Pipeline_VITIS_LOOP_41_1}
  {SRCNAME INTERPOLATOR MODELNAME INTERPOLATOR RTLNAME FIR_HLS_INTERPOLATOR
    SUBMODULES {
      {MODELNAME FIR_HLS_mac_muladd_16s_9ns_30s_30_4_1 RTLNAME FIR_HLS_mac_muladd_16s_9ns_30s_30_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME FIR_HLS_INTERPOLATOR_H_accu_FIR_int_41_RAM_AUTO_1R1W RTLNAME FIR_HLS_INTERPOLATOR_H_accu_FIR_int_41_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_INTERPOLATOR_b_FIR_dec_int_418_ROM_AUTO_1R RTLNAME FIR_HLS_INTERPOLATOR_b_FIR_dec_int_418_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_INTERPOLATOR_b_FIR_dec_int_429_ROM_AUTO_1R RTLNAME FIR_HLS_INTERPOLATOR_b_FIR_dec_int_429_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_INTERPOLATOR_b_FIR_dec_int_4310_ROM_AUTO_1R RTLNAME FIR_HLS_INTERPOLATOR_b_FIR_dec_int_4310_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc MODELNAME Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc RTLNAME FIR_HLS_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc
    SUBMODULES {
      {MODELNAME FIR_HLS_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_H_accu_FIR_kernel_RAM_AUTO_cud RTLNAME FIR_HLS_Block_entry_b_FIR_dec_int_43_rd_mod_value_fb_proc_H_accu_FIR_kernel_RAM_AUTO_cud BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_regslice_both RTLNAME FIR_HLS_regslice_both BINDTYPE interface TYPE adapter IMPL reg_slice}
    }
  }
  {SRCNAME FIR_HLS MODELNAME FIR_HLS RTLNAME FIR_HLS IS_TOP 1}
}
