-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FIR_HLS_FIR_filter is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    FIR_delays_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    FIR_delays_ce0 : OUT STD_LOGIC;
    FIR_delays_we0 : OUT STD_LOGIC;
    FIR_delays_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    FIR_delays_ce1 : OUT STD_LOGIC;
    FIR_delays_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    x_n : IN STD_LOGIC_VECTOR (15 downto 0);
    shift : IN STD_LOGIC_VECTOR (2 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of FIR_HLS_FIR_filter is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_start : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_done : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_idle : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_ready : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_FIR_delays_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_FIR_delays_ce0 : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_FIR_accu32_out : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_FIR_accu32_out_ap_vld : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_start : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_done : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_idle : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_ready : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_ce0 : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_we0 : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_ce1 : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal FIR_delays_we0_out : STD_LOGIC;
    signal FIR_delays_we0_local : STD_LOGIC;
    signal FIR_delays_ce0_local : STD_LOGIC;
    signal sext_ln57_fu_68_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln57_fu_72_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal ashr_ln73_fu_79_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal y_fu_85_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component FIR_HLS_FIR_filter_Pipeline_VITIS_LOOP_65_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        FIR_delays_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        FIR_delays_ce0 : OUT STD_LOGIC;
        FIR_delays_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        FIR_accu32_out : OUT STD_LOGIC_VECTOR (30 downto 0);
        FIR_accu32_out_ap_vld : OUT STD_LOGIC );
    end component;


    component FIR_HLS_FIR_filter_Pipeline_VITIS_LOOP_69_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        FIR_delays_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        FIR_delays_ce0 : OUT STD_LOGIC;
        FIR_delays_we0 : OUT STD_LOGIC;
        FIR_delays_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        FIR_delays_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        FIR_delays_ce1 : OUT STD_LOGIC;
        FIR_delays_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53 : component FIR_HLS_FIR_filter_Pipeline_VITIS_LOOP_65_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_start,
        ap_done => grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_done,
        ap_idle => grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_idle,
        ap_ready => grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_ready,
        FIR_delays_address0 => grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_FIR_delays_address0,
        FIR_delays_ce0 => grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_FIR_delays_ce0,
        FIR_delays_q0 => FIR_delays_q0,
        FIR_accu32_out => grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_FIR_accu32_out,
        FIR_accu32_out_ap_vld => grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_FIR_accu32_out_ap_vld);

    grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62 : component FIR_HLS_FIR_filter_Pipeline_VITIS_LOOP_69_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_start,
        ap_done => grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_done,
        ap_idle => grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_idle,
        ap_ready => grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_ready,
        FIR_delays_address0 => grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_address0,
        FIR_delays_ce0 => grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_ce0,
        FIR_delays_we0 => grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_we0,
        FIR_delays_d0 => grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_d0,
        FIR_delays_address1 => grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_address1,
        FIR_delays_ce1 => grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_ce1,
        FIR_delays_q1 => FIR_delays_q1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv16_0;
            else
                if (((grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_return_preg <= y_fu_85_p1;
                end if; 
            end if;
        end if;
    end process;


    grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_ready = ap_const_logic_1)) then 
                    grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_ready = ap_const_logic_1)) then 
                    grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_done, grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;

    FIR_delays_address0_assign_proc : process(grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_FIR_delays_address0, grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            FIR_delays_address0 <= grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            FIR_delays_address0 <= grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_FIR_delays_address0;
        else 
            FIR_delays_address0 <= ap_const_lv64_5(3 - 1 downto 0);
        end if; 
    end process;

    FIR_delays_address1 <= grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_address1;

    FIR_delays_ce0_assign_proc : process(grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_FIR_delays_ce0, grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5, FIR_delays_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            FIR_delays_ce0 <= grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            FIR_delays_ce0 <= grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_FIR_delays_ce0;
        else 
            FIR_delays_ce0 <= FIR_delays_ce0_local;
        end if; 
    end process;


    FIR_delays_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            FIR_delays_ce0_local <= ap_const_logic_1;
        else 
            FIR_delays_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    FIR_delays_ce1_assign_proc : process(grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            FIR_delays_ce1 <= grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_ce1;
        else 
            FIR_delays_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    FIR_delays_d0_assign_proc : process(x_n, grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_d0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            FIR_delays_d0 <= grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_d0;
        else 
            FIR_delays_d0 <= x_n;
        end if; 
    end process;


    FIR_delays_we0_assign_proc : process(grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_we0, ap_CS_fsm_state5, FIR_delays_we0_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            FIR_delays_we0 <= grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_FIR_delays_we0;
        else 
            FIR_delays_we0 <= (ap_const_logic_0 or FIR_delays_we0_out);
        end if; 
    end process;


    FIR_delays_we0_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            FIR_delays_we0_local <= ap_const_logic_1;
        else 
            FIR_delays_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    FIR_delays_we0_out <= FIR_delays_we0_local;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_done)
    begin
        if ((grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_done)
    begin
        if ((grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_done, ap_CS_fsm_state5)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_done, ap_CS_fsm_state5)
    begin
        if (((grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_done, ap_CS_fsm_state5, y_fu_85_p1, ap_return_preg)
    begin
        if (((grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_return <= y_fu_85_p1;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    ashr_ln73_fu_79_p2 <= std_logic_vector(shift_right(signed(grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_FIR_accu32_out),to_integer(unsigned('0' & zext_ln57_fu_72_p1(31-1 downto 0)))));
    grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_start <= grp_FIR_filter_Pipeline_VITIS_LOOP_65_1_fu_53_ap_start_reg;
    grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_start <= grp_FIR_filter_Pipeline_VITIS_LOOP_69_2_fu_62_ap_start_reg;
        sext_ln57_fu_68_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shift),4));

    y_fu_85_p1 <= ashr_ln73_fu_79_p2(16 - 1 downto 0);
    zext_ln57_fu_72_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln57_fu_68_p1),31));
end behav;
