-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FIR_HLS_DECIMATOR is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    input_r_TVALID : IN STD_LOGIC;
    input_r_TREADY : OUT STD_LOGIC;
    dec_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    dec_out_full_n : IN STD_LOGIC;
    dec_out_write : OUT STD_LOGIC );
end;


architecture behav of FIR_HLS_DECIMATOR is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv25_1B4 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000110110100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal mod_value_2 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal H_accu_FIR_dec_40_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal H_accu_FIR_dec_40_ce0 : STD_LOGIC;
    signal H_accu_FIR_dec_40_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_accu_FIR_dec_40_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal y1_phase1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal y1_phase2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal y1_phase3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal H_accu_FIR_dec_43_ce0 : STD_LOGIC;
    signal H_accu_FIR_dec_43_we0 : STD_LOGIC;
    signal H_accu_FIR_dec_43_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_accu_FIR_dec_43_ce1 : STD_LOGIC;
    signal H_accu_FIR_dec_43_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_FIR_dec_int_43_ce0 : STD_LOGIC;
    signal b_FIR_dec_int_43_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal H_accu_FIR_dec_42_ce0 : STD_LOGIC;
    signal H_accu_FIR_dec_42_we0 : STD_LOGIC;
    signal H_accu_FIR_dec_42_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_accu_FIR_dec_42_ce1 : STD_LOGIC;
    signal H_accu_FIR_dec_42_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_FIR_dec_int_42_ce0 : STD_LOGIC;
    signal b_FIR_dec_int_42_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal H_accu_FIR_dec_41_ce0 : STD_LOGIC;
    signal H_accu_FIR_dec_41_we0 : STD_LOGIC;
    signal H_accu_FIR_dec_41_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_accu_FIR_dec_41_ce1 : STD_LOGIC;
    signal H_accu_FIR_dec_41_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_FIR_dec_int_41_ce0 : STD_LOGIC;
    signal b_FIR_dec_int_41_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal input_r_TDATA_blk_n : STD_LOGIC;
    signal dec_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal mod_value_2_load_reg_228 : STD_LOGIC_VECTOR (1 downto 0);
    signal reg_132 : STD_LOGIC_VECTOR (15 downto 0);
    signal H_accu_FIR_dec_40_load_reg_237 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_FIR_filter_2_fu_109_ap_start : STD_LOGIC;
    signal grp_FIR_filter_2_fu_109_ap_done : STD_LOGIC;
    signal grp_FIR_filter_2_fu_109_ap_idle : STD_LOGIC;
    signal grp_FIR_filter_2_fu_109_ap_ready : STD_LOGIC;
    signal grp_FIR_filter_2_fu_109_FIR_delays_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_filter_2_fu_109_FIR_delays_ce0 : STD_LOGIC;
    signal grp_FIR_filter_2_fu_109_FIR_delays_we0 : STD_LOGIC;
    signal grp_FIR_filter_2_fu_109_FIR_delays_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FIR_filter_2_fu_109_FIR_delays_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FIR_filter_2_fu_109_FIR_delays_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_filter_2_fu_109_FIR_delays_ce1 : STD_LOGIC;
    signal grp_FIR_filter_2_fu_109_FIR_delays_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FIR_filter_2_fu_109_FIR_coe_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_filter_2_fu_109_FIR_coe_ce0 : STD_LOGIC;
    signal grp_FIR_filter_2_fu_109_FIR_coe_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_FIR_filter_2_fu_109_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start : STD_LOGIC;
    signal grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_done : STD_LOGIC;
    signal grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_idle : STD_LOGIC;
    signal grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_ready : STD_LOGIC;
    signal grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_ce0 : STD_LOGIC;
    signal grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_we0 : STD_LOGIC;
    signal grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_ce1 : STD_LOGIC;
    signal ap_phi_mux_storemerge2_i_phi_fu_95_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal storemerge2_i_reg_89 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state5 : BOOLEAN;
    signal ap_block_state5_on_subcall_done : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_FIR_filter_2_fu_109_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call1 : BOOLEAN;
    signal grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal H_accu_FIR_dec_40_ce0_local : STD_LOGIC;
    signal sext_ln39_fu_142_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_220_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_fu_168_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln60_1_fu_195_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln60_fu_189_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_220_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_220_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component FIR_HLS_FIR_filter_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        FIR_delays_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        FIR_delays_ce0 : OUT STD_LOGIC;
        FIR_delays_we0 : OUT STD_LOGIC;
        FIR_delays_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        FIR_delays_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        FIR_delays_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        FIR_delays_ce1 : OUT STD_LOGIC;
        FIR_delays_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        FIR_coe_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        FIR_coe_ce0 : OUT STD_LOGIC;
        FIR_coe_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        x_n : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component FIR_HLS_DECIMATOR_Pipeline_VITIS_LOOP_41_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sext_ln42 : IN STD_LOGIC_VECTOR (15 downto 0);
        H_accu_FIR_dec_40_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        H_accu_FIR_dec_40_ce0 : OUT STD_LOGIC;
        H_accu_FIR_dec_40_we0 : OUT STD_LOGIC;
        H_accu_FIR_dec_40_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        H_accu_FIR_dec_40_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        H_accu_FIR_dec_40_ce1 : OUT STD_LOGIC;
        H_accu_FIR_dec_40_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_HLS_mac_muladd_16s_9ns_32s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_HLS_DECIMATOR_H_accu_FIR_dec_40_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_HLS_DECIMATOR_H_accu_FIR_dec_43_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_HLS_DECIMATOR_b_FIR_dec_int_43_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component FIR_HLS_DECIMATOR_b_FIR_dec_int_42_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component FIR_HLS_DECIMATOR_b_FIR_dec_int_41_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;



begin
    H_accu_FIR_dec_40_U : component FIR_HLS_DECIMATOR_H_accu_FIR_dec_40_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 6,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => H_accu_FIR_dec_40_address0,
        ce0 => H_accu_FIR_dec_40_ce0,
        we0 => grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_we0,
        d0 => grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_d0,
        q0 => H_accu_FIR_dec_40_q0,
        address1 => grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_address1,
        ce1 => grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_ce1,
        q1 => H_accu_FIR_dec_40_q1);

    H_accu_FIR_dec_43_U : component FIR_HLS_DECIMATOR_H_accu_FIR_dec_43_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_FIR_filter_2_fu_109_FIR_delays_address0,
        ce0 => H_accu_FIR_dec_43_ce0,
        we0 => H_accu_FIR_dec_43_we0,
        d0 => grp_FIR_filter_2_fu_109_FIR_delays_d0,
        q0 => H_accu_FIR_dec_43_q0,
        address1 => grp_FIR_filter_2_fu_109_FIR_delays_address1,
        ce1 => H_accu_FIR_dec_43_ce1,
        q1 => H_accu_FIR_dec_43_q1);

    b_FIR_dec_int_43_U : component FIR_HLS_DECIMATOR_b_FIR_dec_int_43_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_FIR_filter_2_fu_109_FIR_coe_address0,
        ce0 => b_FIR_dec_int_43_ce0,
        q0 => b_FIR_dec_int_43_q0);

    H_accu_FIR_dec_42_U : component FIR_HLS_DECIMATOR_H_accu_FIR_dec_43_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_FIR_filter_2_fu_109_FIR_delays_address0,
        ce0 => H_accu_FIR_dec_42_ce0,
        we0 => H_accu_FIR_dec_42_we0,
        d0 => grp_FIR_filter_2_fu_109_FIR_delays_d0,
        q0 => H_accu_FIR_dec_42_q0,
        address1 => grp_FIR_filter_2_fu_109_FIR_delays_address1,
        ce1 => H_accu_FIR_dec_42_ce1,
        q1 => H_accu_FIR_dec_42_q1);

    b_FIR_dec_int_42_U : component FIR_HLS_DECIMATOR_b_FIR_dec_int_42_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_FIR_filter_2_fu_109_FIR_coe_address0,
        ce0 => b_FIR_dec_int_42_ce0,
        q0 => b_FIR_dec_int_42_q0);

    H_accu_FIR_dec_41_U : component FIR_HLS_DECIMATOR_H_accu_FIR_dec_43_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_FIR_filter_2_fu_109_FIR_delays_address0,
        ce0 => H_accu_FIR_dec_41_ce0,
        we0 => H_accu_FIR_dec_41_we0,
        d0 => grp_FIR_filter_2_fu_109_FIR_delays_d0,
        q0 => H_accu_FIR_dec_41_q0,
        address1 => grp_FIR_filter_2_fu_109_FIR_delays_address1,
        ce1 => H_accu_FIR_dec_41_ce1,
        q1 => H_accu_FIR_dec_41_q1);

    b_FIR_dec_int_41_U : component FIR_HLS_DECIMATOR_b_FIR_dec_int_41_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_FIR_filter_2_fu_109_FIR_coe_address0,
        ce0 => b_FIR_dec_int_41_ce0,
        q0 => b_FIR_dec_int_41_q0);

    grp_FIR_filter_2_fu_109 : component FIR_HLS_FIR_filter_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_FIR_filter_2_fu_109_ap_start,
        ap_done => grp_FIR_filter_2_fu_109_ap_done,
        ap_idle => grp_FIR_filter_2_fu_109_ap_idle,
        ap_ready => grp_FIR_filter_2_fu_109_ap_ready,
        FIR_delays_address0 => grp_FIR_filter_2_fu_109_FIR_delays_address0,
        FIR_delays_ce0 => grp_FIR_filter_2_fu_109_FIR_delays_ce0,
        FIR_delays_we0 => grp_FIR_filter_2_fu_109_FIR_delays_we0,
        FIR_delays_d0 => grp_FIR_filter_2_fu_109_FIR_delays_d0,
        FIR_delays_q0 => grp_FIR_filter_2_fu_109_FIR_delays_q0,
        FIR_delays_address1 => grp_FIR_filter_2_fu_109_FIR_delays_address1,
        FIR_delays_ce1 => grp_FIR_filter_2_fu_109_FIR_delays_ce1,
        FIR_delays_q1 => grp_FIR_filter_2_fu_109_FIR_delays_q1,
        FIR_coe_address0 => grp_FIR_filter_2_fu_109_FIR_coe_address0,
        FIR_coe_ce0 => grp_FIR_filter_2_fu_109_FIR_coe_ce0,
        FIR_coe_q0 => grp_FIR_filter_2_fu_109_FIR_coe_q0,
        x_n => reg_132,
        ap_return => grp_FIR_filter_2_fu_109_ap_return);

    grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123 : component FIR_HLS_DECIMATOR_Pipeline_VITIS_LOOP_41_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start,
        ap_done => grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_done,
        ap_idle => grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_idle,
        ap_ready => grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_ready,
        sext_ln42 => reg_132,
        H_accu_FIR_dec_40_address0 => grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_address0,
        H_accu_FIR_dec_40_ce0 => grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_ce0,
        H_accu_FIR_dec_40_we0 => grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_we0,
        H_accu_FIR_dec_40_d0 => grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_d0,
        H_accu_FIR_dec_40_address1 => grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_address1,
        H_accu_FIR_dec_40_ce1 => grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_ce1,
        H_accu_FIR_dec_40_q1 => H_accu_FIR_dec_40_q1);

    mac_muladd_16s_9ns_32s_32_4_1_U15 : component FIR_HLS_mac_muladd_16s_9ns_32s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sext_ln39_fu_142_p0,
        din1 => grp_fu_220_p1,
        din2 => H_accu_FIR_dec_40_load_reg_237,
        ce => grp_fu_220_ce,
        dout => grp_fu_220_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_ready = ap_const_logic_1)) then 
                    grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_FIR_filter_2_fu_109_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_FIR_filter_2_fu_109_ap_start_reg <= ap_const_logic_0;
            else
                if ((((ap_const_boolean_0 = ap_block_state1_ignore_call1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value_2 = ap_const_lv2_3)) or ((ap_const_boolean_0 = ap_block_state1_ignore_call1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value_2 = ap_const_lv2_2)) or ((ap_const_boolean_0 = ap_block_state1_ignore_call1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value_2 = ap_const_lv2_1)))) then 
                    grp_FIR_filter_2_fu_109_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FIR_filter_2_fu_109_ap_ready = ap_const_logic_1)) then 
                    grp_FIR_filter_2_fu_109_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    storemerge2_i_reg_89_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_2))) then 
                storemerge2_i_reg_89 <= ap_const_lv2_3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_FIR_filter_2_fu_109_ap_done = ap_const_logic_1))) then 
                storemerge2_i_reg_89 <= ap_const_lv2_0;
            elsif (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_1))) then 
                storemerge2_i_reg_89 <= ap_const_lv2_2;
            elsif ((not(((ap_const_boolean_1 = ap_block_state5_on_subcall_done) or (ap_const_boolean_1 = ap_block_state5))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (mod_value_2_load_reg_228 = ap_const_lv2_0))) then 
                storemerge2_i_reg_89 <= ap_const_lv2_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                H_accu_FIR_dec_40_load_reg_237 <= H_accu_FIR_dec_40_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state5_on_subcall_done) or (ap_const_boolean_1 = ap_block_state5))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                mod_value_2 <= ap_phi_mux_storemerge2_i_phi_fu_95_p8;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                mod_value_2_load_reg_228 <= mod_value_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value_2 = ap_const_lv2_3)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value_2 = ap_const_lv2_2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value_2 = ap_const_lv2_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value_2 = ap_const_lv2_0)))) then
                reg_132 <= input_r_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_1))) then
                y1_phase1 <= grp_FIR_filter_2_fu_109_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_2))) then
                y1_phase2 <= grp_FIR_filter_2_fu_109_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_FIR_filter_2_fu_109_ap_done = ap_const_logic_1))) then
                y1_phase3 <= grp_FIR_filter_2_fu_109_ap_return;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, mod_value_2, ap_CS_fsm_state5, mod_value_2_load_reg_228, grp_FIR_filter_2_fu_109_ap_done, ap_block_state5, ap_block_state5_on_subcall_done, ap_CS_fsm_state2, ap_block_state2_on_subcall_done, ap_CS_fsm_state6, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value_2 = ap_const_lv2_3))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value_2 = ap_const_lv2_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1) and ((mod_value_2 = ap_const_lv2_2) or (mod_value_2 = ap_const_lv2_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2) and ((mod_value_2_load_reg_228 = ap_const_lv2_2) or (mod_value_2_load_reg_228 = ap_const_lv2_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if ((not(((ap_const_boolean_1 = ap_block_state5_on_subcall_done) or (ap_const_boolean_1 = ap_block_state5))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_FIR_filter_2_fu_109_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;

    H_accu_FIR_dec_40_address0_assign_proc : process(ap_CS_fsm_state5, mod_value_2_load_reg_228, grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_address0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (mod_value_2_load_reg_228 = ap_const_lv2_0))) then 
            H_accu_FIR_dec_40_address0 <= grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_address0;
        else 
            H_accu_FIR_dec_40_address0 <= ap_const_lv3_0;
        end if; 
    end process;


    H_accu_FIR_dec_40_ce0_assign_proc : process(ap_CS_fsm_state5, mod_value_2_load_reg_228, grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_ce0, H_accu_FIR_dec_40_ce0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (mod_value_2_load_reg_228 = ap_const_lv2_0))) then 
            H_accu_FIR_dec_40_ce0 <= grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_H_accu_FIR_dec_40_ce0;
        else 
            H_accu_FIR_dec_40_ce0 <= H_accu_FIR_dec_40_ce0_local;
        end if; 
    end process;


    H_accu_FIR_dec_40_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            H_accu_FIR_dec_40_ce0_local <= ap_const_logic_1;
        else 
            H_accu_FIR_dec_40_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    H_accu_FIR_dec_41_ce0_assign_proc : process(grp_FIR_filter_2_fu_109_FIR_delays_ce0, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            H_accu_FIR_dec_41_ce0 <= grp_FIR_filter_2_fu_109_FIR_delays_ce0;
        else 
            H_accu_FIR_dec_41_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    H_accu_FIR_dec_41_ce1_assign_proc : process(grp_FIR_filter_2_fu_109_FIR_delays_ce1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            H_accu_FIR_dec_41_ce1 <= grp_FIR_filter_2_fu_109_FIR_delays_ce1;
        else 
            H_accu_FIR_dec_41_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    H_accu_FIR_dec_41_we0_assign_proc : process(grp_FIR_filter_2_fu_109_FIR_delays_we0, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            H_accu_FIR_dec_41_we0 <= grp_FIR_filter_2_fu_109_FIR_delays_we0;
        else 
            H_accu_FIR_dec_41_we0 <= ap_const_logic_0;
        end if; 
    end process;


    H_accu_FIR_dec_42_ce0_assign_proc : process(mod_value_2_load_reg_228, grp_FIR_filter_2_fu_109_FIR_delays_ce0, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_2))) then 
            H_accu_FIR_dec_42_ce0 <= grp_FIR_filter_2_fu_109_FIR_delays_ce0;
        else 
            H_accu_FIR_dec_42_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    H_accu_FIR_dec_42_ce1_assign_proc : process(mod_value_2_load_reg_228, grp_FIR_filter_2_fu_109_FIR_delays_ce1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_2))) then 
            H_accu_FIR_dec_42_ce1 <= grp_FIR_filter_2_fu_109_FIR_delays_ce1;
        else 
            H_accu_FIR_dec_42_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    H_accu_FIR_dec_42_we0_assign_proc : process(mod_value_2_load_reg_228, grp_FIR_filter_2_fu_109_FIR_delays_we0, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_2))) then 
            H_accu_FIR_dec_42_we0 <= grp_FIR_filter_2_fu_109_FIR_delays_we0;
        else 
            H_accu_FIR_dec_42_we0 <= ap_const_logic_0;
        end if; 
    end process;


    H_accu_FIR_dec_43_ce0_assign_proc : process(mod_value_2_load_reg_228, grp_FIR_filter_2_fu_109_FIR_delays_ce0, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_1))) then 
            H_accu_FIR_dec_43_ce0 <= grp_FIR_filter_2_fu_109_FIR_delays_ce0;
        else 
            H_accu_FIR_dec_43_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    H_accu_FIR_dec_43_ce1_assign_proc : process(mod_value_2_load_reg_228, grp_FIR_filter_2_fu_109_FIR_delays_ce1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_1))) then 
            H_accu_FIR_dec_43_ce1 <= grp_FIR_filter_2_fu_109_FIR_delays_ce1;
        else 
            H_accu_FIR_dec_43_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    H_accu_FIR_dec_43_we0_assign_proc : process(mod_value_2_load_reg_228, grp_FIR_filter_2_fu_109_FIR_delays_we0, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_1))) then 
            H_accu_FIR_dec_43_we0 <= grp_FIR_filter_2_fu_109_FIR_delays_we0;
        else 
            H_accu_FIR_dec_43_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln60_1_fu_195_p2 <= std_logic_vector(unsigned(y1_phase3) + unsigned(y_fu_168_p4));
    add_ln60_fu_189_p2 <= std_logic_vector(unsigned(y1_phase1) + unsigned(y1_phase2));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5, ap_block_state5_on_subcall_done)
    begin
        if (((ap_const_boolean_1 = ap_block_state5_on_subcall_done) or (ap_const_boolean_1 = ap_block_state5))) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(grp_FIR_filter_2_fu_109_ap_done)
    begin
        if ((grp_FIR_filter_2_fu_109_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, input_r_TVALID, mod_value_2)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or ((input_r_TVALID = ap_const_logic_0) and (mod_value_2 = ap_const_lv2_3)) or ((input_r_TVALID = ap_const_logic_0) and (mod_value_2 = ap_const_lv2_2)) or ((input_r_TVALID = ap_const_logic_0) and (mod_value_2 = ap_const_lv2_1)) or ((input_r_TVALID = ap_const_logic_0) and (mod_value_2 = ap_const_lv2_0)));
    end process;


    ap_block_state1_ignore_call1_assign_proc : process(ap_start, input_r_TVALID, mod_value_2)
    begin
                ap_block_state1_ignore_call1 <= ((ap_start = ap_const_logic_0) or ((input_r_TVALID = ap_const_logic_0) and (mod_value_2 = ap_const_lv2_3)) or ((input_r_TVALID = ap_const_logic_0) and (mod_value_2 = ap_const_lv2_2)) or ((input_r_TVALID = ap_const_logic_0) and (mod_value_2 = ap_const_lv2_1)) or ((input_r_TVALID = ap_const_logic_0) and (mod_value_2 = ap_const_lv2_0)));
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(mod_value_2_load_reg_228, grp_FIR_filter_2_fu_109_ap_done)
    begin
                ap_block_state2_on_subcall_done <= (((grp_FIR_filter_2_fu_109_ap_done = ap_const_logic_0) and (mod_value_2_load_reg_228 = ap_const_lv2_2)) or ((grp_FIR_filter_2_fu_109_ap_done = ap_const_logic_0) and (mod_value_2_load_reg_228 = ap_const_lv2_1)));
    end process;


    ap_block_state5_assign_proc : process(dec_out_full_n, mod_value_2_load_reg_228)
    begin
                ap_block_state5 <= ((dec_out_full_n = ap_const_logic_0) and (mod_value_2_load_reg_228 = ap_const_lv2_0));
    end process;


    ap_block_state5_on_subcall_done_assign_proc : process(mod_value_2_load_reg_228, grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_done)
    begin
                ap_block_state5_on_subcall_done <= ((grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_done = ap_const_logic_0) and (mod_value_2_load_reg_228 = ap_const_lv2_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5, ap_block_state5, ap_block_state5_on_subcall_done)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or (not(((ap_const_boolean_1 = ap_block_state5_on_subcall_done) or (ap_const_boolean_1 = ap_block_state5))) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_storemerge2_i_phi_fu_95_p8_assign_proc : process(ap_CS_fsm_state5, mod_value_2_load_reg_228, storemerge2_i_reg_89)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (mod_value_2_load_reg_228 = ap_const_lv2_0))) then 
            ap_phi_mux_storemerge2_i_phi_fu_95_p8 <= ap_const_lv2_1;
        else 
            ap_phi_mux_storemerge2_i_phi_fu_95_p8 <= storemerge2_i_reg_89;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, ap_block_state5, ap_block_state5_on_subcall_done)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state5_on_subcall_done) or (ap_const_boolean_1 = ap_block_state5))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    b_FIR_dec_int_41_ce0_assign_proc : process(grp_FIR_filter_2_fu_109_FIR_coe_ce0, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            b_FIR_dec_int_41_ce0 <= grp_FIR_filter_2_fu_109_FIR_coe_ce0;
        else 
            b_FIR_dec_int_41_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    b_FIR_dec_int_42_ce0_assign_proc : process(mod_value_2_load_reg_228, grp_FIR_filter_2_fu_109_FIR_coe_ce0, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_2))) then 
            b_FIR_dec_int_42_ce0 <= grp_FIR_filter_2_fu_109_FIR_coe_ce0;
        else 
            b_FIR_dec_int_42_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    b_FIR_dec_int_43_ce0_assign_proc : process(mod_value_2_load_reg_228, grp_FIR_filter_2_fu_109_FIR_coe_ce0, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_1))) then 
            b_FIR_dec_int_43_ce0 <= grp_FIR_filter_2_fu_109_FIR_coe_ce0;
        else 
            b_FIR_dec_int_43_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dec_out_blk_n_assign_proc : process(dec_out_full_n, ap_CS_fsm_state5, mod_value_2_load_reg_228)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (mod_value_2_load_reg_228 = ap_const_lv2_0))) then 
            dec_out_blk_n <= dec_out_full_n;
        else 
            dec_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dec_out_din <= std_logic_vector(unsigned(add_ln60_1_fu_195_p2) + unsigned(add_ln60_fu_189_p2));

    dec_out_write_assign_proc : process(ap_CS_fsm_state5, mod_value_2_load_reg_228, ap_block_state5, ap_block_state5_on_subcall_done)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state5_on_subcall_done) or (ap_const_boolean_1 = ap_block_state5))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (mod_value_2_load_reg_228 = ap_const_lv2_0))) then 
            dec_out_write <= ap_const_logic_1;
        else 
            dec_out_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start <= grp_DECIMATOR_Pipeline_VITIS_LOOP_41_1_fu_123_ap_start_reg;

    grp_FIR_filter_2_fu_109_FIR_coe_q0_assign_proc : process(b_FIR_dec_int_43_q0, b_FIR_dec_int_42_q0, b_FIR_dec_int_41_q0, mod_value_2_load_reg_228, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_FIR_filter_2_fu_109_FIR_coe_q0 <= b_FIR_dec_int_41_q0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_1))) then 
            grp_FIR_filter_2_fu_109_FIR_coe_q0 <= b_FIR_dec_int_43_q0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_2))) then 
            grp_FIR_filter_2_fu_109_FIR_coe_q0 <= b_FIR_dec_int_42_q0;
        else 
            grp_FIR_filter_2_fu_109_FIR_coe_q0 <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_FIR_filter_2_fu_109_FIR_delays_q0_assign_proc : process(H_accu_FIR_dec_43_q0, H_accu_FIR_dec_42_q0, H_accu_FIR_dec_41_q0, mod_value_2_load_reg_228, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_FIR_filter_2_fu_109_FIR_delays_q0 <= H_accu_FIR_dec_41_q0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_1))) then 
            grp_FIR_filter_2_fu_109_FIR_delays_q0 <= H_accu_FIR_dec_43_q0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_2))) then 
            grp_FIR_filter_2_fu_109_FIR_delays_q0 <= H_accu_FIR_dec_42_q0;
        else 
            grp_FIR_filter_2_fu_109_FIR_delays_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_FIR_filter_2_fu_109_FIR_delays_q1_assign_proc : process(H_accu_FIR_dec_43_q1, H_accu_FIR_dec_42_q1, H_accu_FIR_dec_41_q1, mod_value_2_load_reg_228, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_FIR_filter_2_fu_109_FIR_delays_q1 <= H_accu_FIR_dec_41_q1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_1))) then 
            grp_FIR_filter_2_fu_109_FIR_delays_q1 <= H_accu_FIR_dec_43_q1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (mod_value_2_load_reg_228 = ap_const_lv2_2))) then 
            grp_FIR_filter_2_fu_109_FIR_delays_q1 <= H_accu_FIR_dec_42_q1;
        else 
            grp_FIR_filter_2_fu_109_FIR_delays_q1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_FIR_filter_2_fu_109_ap_start <= grp_FIR_filter_2_fu_109_ap_start_reg;

    grp_fu_220_ce_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state5, ap_CS_fsm_state3, ap_block_state5, ap_block_state5_on_subcall_done, ap_CS_fsm_state4, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not(((ap_const_boolean_1 = ap_block_state5_on_subcall_done) or (ap_const_boolean_1 = ap_block_state5))) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            grp_fu_220_ce <= ap_const_logic_1;
        else 
            grp_fu_220_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_220_p1 <= ap_const_lv25_1B4(9 - 1 downto 0);

    input_r_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, input_r_TVALID, mod_value_2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (mod_value_2 = ap_const_lv2_3)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (mod_value_2 = ap_const_lv2_2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (mod_value_2 = ap_const_lv2_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (mod_value_2 = ap_const_lv2_0)))) then 
            input_r_TDATA_blk_n <= input_r_TVALID;
        else 
            input_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    input_r_TREADY_assign_proc : process(ap_CS_fsm_state1, mod_value_2, ap_block_state1)
    begin
        if ((((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value_2 = ap_const_lv2_3)) or ((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value_2 = ap_const_lv2_2)) or ((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value_2 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value_2 = ap_const_lv2_0)))) then 
            input_r_TREADY <= ap_const_logic_1;
        else 
            input_r_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    sext_ln39_fu_142_p0 <= input_r_TDATA;
    y_fu_168_p4 <= grp_fu_220_p3(31 downto 16);
end behav;
