// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="FIR_HLS_FIR_HLS,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.870000,HLS_SYN_LAT=51,HLS_SYN_TPT=none,HLS_SYN_MEM=3,HLS_SYN_DSP=0,HLS_SYN_FF=1034,HLS_SYN_LUT=1561,HLS_VERSION=2024_2}" *)

module FIR_HLS (
        ap_clk,
        ap_rst_n,
        input_r_TDATA,
        input_r_TVALID,
        input_r_TREADY,
        output_r_TDATA,
        output_r_TVALID,
        output_r_TREADY
);

parameter    ap_ST_fsm_state1 = 19'd1;
parameter    ap_ST_fsm_state2 = 19'd2;
parameter    ap_ST_fsm_state3 = 19'd4;
parameter    ap_ST_fsm_state4 = 19'd8;
parameter    ap_ST_fsm_state5 = 19'd16;
parameter    ap_ST_fsm_state6 = 19'd32;
parameter    ap_ST_fsm_state7 = 19'd64;
parameter    ap_ST_fsm_state8 = 19'd128;
parameter    ap_ST_fsm_state9 = 19'd256;
parameter    ap_ST_fsm_state10 = 19'd512;
parameter    ap_ST_fsm_state11 = 19'd1024;
parameter    ap_ST_fsm_state12 = 19'd2048;
parameter    ap_ST_fsm_state13 = 19'd4096;
parameter    ap_ST_fsm_state14 = 19'd8192;
parameter    ap_ST_fsm_state15 = 19'd16384;
parameter    ap_ST_fsm_state16 = 19'd32768;
parameter    ap_ST_fsm_state17 = 19'd65536;
parameter    ap_ST_fsm_state18 = 19'd131072;
parameter    ap_ST_fsm_state19 = 19'd262144;

input   ap_clk;
input   ap_rst_n;
input  [15:0] input_r_TDATA;
input   input_r_TVALID;
output   input_r_TREADY;
output  [15:0] output_r_TDATA;
output   output_r_TVALID;
input   output_r_TREADY;

 reg    ap_rst_n_inv;
reg   [1:0] mod_value;
reg   [15:0] y2;
reg   [2:0] b_FIR_dec_int_40_address0;
reg    b_FIR_dec_int_40_ce0;
wire   [13:0] b_FIR_dec_int_40_q0;
reg   [2:0] H_filter_FIR_dec_40_address0;
reg    H_filter_FIR_dec_40_ce0;
wire  signed [31:0] H_filter_FIR_dec_40_q0;
wire   [31:0] H_filter_FIR_dec_40_q1;
reg   [15:0] y1_phase1;
reg   [15:0] y1_phase2;
reg   [15:0] y1_phase3;
reg   [6:0] H_filter_FIR_kernel_address0;
reg    H_filter_FIR_kernel_ce0;
wire   [31:0] H_filter_FIR_kernel_q0;
wire   [31:0] H_filter_FIR_kernel_q1;
reg   [2:0] H_filter_FIR_int_40_address0;
reg    H_filter_FIR_int_40_ce0;
wire   [31:0] H_filter_FIR_int_40_q0;
wire   [31:0] H_filter_FIR_int_40_q1;
reg    H_filter_FIR_dec_43_ce0;
reg    H_filter_FIR_dec_43_we0;
wire   [31:0] H_filter_FIR_dec_43_q0;
reg    H_filter_FIR_dec_43_ce1;
wire   [31:0] H_filter_FIR_dec_43_q1;
reg    b_FIR_dec_int_43_ce0;
wire   [14:0] b_FIR_dec_int_43_q0;
reg   [2:0] H_filter_FIR_int_41_address0;
reg    H_filter_FIR_int_41_ce0;
reg    H_filter_FIR_int_41_we0;
reg   [31:0] H_filter_FIR_int_41_d0;
wire   [31:0] H_filter_FIR_int_41_q0;
reg    H_filter_FIR_int_41_ce1;
wire   [31:0] H_filter_FIR_int_41_q1;
reg   [2:0] b_FIR_dec_int_41_address0;
reg    b_FIR_dec_int_41_ce0;
wire   [14:0] b_FIR_dec_int_41_q0;
reg    H_filter_FIR_dec_42_ce0;
reg    H_filter_FIR_dec_42_we0;
wire   [31:0] H_filter_FIR_dec_42_q0;
reg    H_filter_FIR_dec_42_ce1;
wire   [31:0] H_filter_FIR_dec_42_q1;
reg    b_FIR_dec_int_42_ce0;
wire   [14:0] b_FIR_dec_int_42_q0;
reg    H_filter_FIR_int_42_ce0;
reg    H_filter_FIR_int_42_we0;
wire   [31:0] H_filter_FIR_int_42_q0;
reg    H_filter_FIR_int_42_ce1;
wire   [31:0] H_filter_FIR_int_42_q1;
reg    H_filter_FIR_dec_41_ce0;
reg    H_filter_FIR_dec_41_we0;
wire   [31:0] H_filter_FIR_dec_41_q0;
reg    H_filter_FIR_dec_41_ce1;
wire   [31:0] H_filter_FIR_dec_41_q1;
reg    H_filter_FIR_int_43_ce0;
reg    H_filter_FIR_int_43_we0;
wire   [31:0] H_filter_FIR_int_43_q0;
reg    H_filter_FIR_int_43_ce1;
wire   [31:0] H_filter_FIR_int_43_q1;
reg    input_r_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [18:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    output_r_TDATA_blk_n;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
reg   [15:0] x_n_1_reg_447;
wire   [1:0] mod_value_load_load_fu_233_p1;
reg   [1:0] mod_value_load_reg_453;
wire   [13:0] trunc_ln39_fu_251_p1;
wire    ap_CS_fsm_state4;
wire   [13:0] trunc_ln45_fu_290_p1;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state14;
reg   [31:0] H_filter_FIR_kernel_load_reg_483;
wire   [15:0] x_n_fu_333_p2;
reg   [15:0] x_n_reg_488;
wire    ap_CS_fsm_state15;
wire  signed [15:0] y_3_fu_375_p4;
reg   [15:0] y_3_reg_493;
wire   [29:0] trunc_ln81_fu_395_p1;
reg  signed [29:0] trunc_ln81_reg_503;
wire    ap_CS_fsm_state16;
wire    grp_FIR_filtertest_2_fu_176_ap_start;
wire    grp_FIR_filtertest_2_fu_176_ap_done;
wire    grp_FIR_filtertest_2_fu_176_ap_idle;
wire    grp_FIR_filtertest_2_fu_176_ap_ready;
wire   [2:0] grp_FIR_filtertest_2_fu_176_FIR_delays_address0;
wire    grp_FIR_filtertest_2_fu_176_FIR_delays_ce0;
wire    grp_FIR_filtertest_2_fu_176_FIR_delays_we0;
wire   [31:0] grp_FIR_filtertest_2_fu_176_FIR_delays_d0;
reg   [31:0] grp_FIR_filtertest_2_fu_176_FIR_delays_q0;
wire   [2:0] grp_FIR_filtertest_2_fu_176_FIR_delays_address1;
wire    grp_FIR_filtertest_2_fu_176_FIR_delays_ce1;
reg   [31:0] grp_FIR_filtertest_2_fu_176_FIR_delays_q1;
wire   [2:0] grp_FIR_filtertest_2_fu_176_FIR_coe_address0;
wire    grp_FIR_filtertest_2_fu_176_FIR_coe_ce0;
reg   [14:0] grp_FIR_filtertest_2_fu_176_FIR_coe_q0;
reg   [15:0] grp_FIR_filtertest_2_fu_176_x_n;
wire   [15:0] grp_FIR_filtertest_2_fu_176_ap_return;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_done;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_idle;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_ready;
wire   [13:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_y_3_out;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_y_3_out_ap_vld;
wire   [2:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_H_filter_FIR_int_41_address0;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_H_filter_FIR_int_41_ce0;
wire   [2:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_b_FIR_dec_int_41_address0;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_b_FIR_dec_int_41_ce0;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_done;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_idle;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_ready;
wire   [2:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_address0;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_ce0;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_we0;
wire   [31:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_d0;
wire   [2:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_address1;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_ce1;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_done;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_idle;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_ready;
wire   [2:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_b_FIR_dec_int_40_address0;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_b_FIR_dec_int_40_ce0;
wire   [2:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_address0;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_ce0;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_we0;
wire   [31:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_d0;
wire   [2:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_address1;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_ce1;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_done;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_idle;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_ready;
wire   [6:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_address0;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_ce0;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_we0;
wire   [31:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_d0;
wire   [6:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_address1;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_ce1;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_done;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_idle;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_ready;
wire   [2:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_b_FIR_dec_int_40_address0;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_b_FIR_dec_int_40_ce0;
wire   [2:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_address0;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_ce0;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_we0;
wire   [31:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_d0;
wire   [2:0] grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_address1;
wire    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_ce1;
reg   [13:0] ap_phi_mux_data_out_load_phi_fu_166_p8;
reg   [13:0] data_out_load_reg_163;
wire    ap_CS_fsm_state9;
reg    ap_block_state18_on_subcall_done;
reg    grp_FIR_filtertest_2_fu_176_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state7;
reg    grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start_reg;
reg    grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    H_filter_FIR_int_41_we0_out;
reg    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start_reg;
reg    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start_reg;
reg    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start_reg;
wire    ap_CS_fsm_state17;
reg    ap_block_state7_on_subcall_done;
reg    H_filter_FIR_int_41_we0_local;
wire    ap_CS_fsm_state5;
wire   [31:0] shl_ln_fu_261_p3;
reg    H_filter_FIR_int_41_ce0_local;
reg    H_filter_FIR_dec_40_ce0_local;
wire    ap_CS_fsm_state13;
reg    H_filter_FIR_kernel_ce0_local;
reg    H_filter_FIR_int_40_ce0_local;
wire  signed [15:0] sext_ln81_fu_241_p0;
wire  signed [31:0] grp_fu_424_p3;
wire   [15:0] y_1_fu_300_p4;
wire   [15:0] add_ln24_1_fu_327_p2;
wire   [15:0] add_ln24_fu_321_p2;
wire   [17:0] tmp_fu_348_p3;
wire   [22:0] p_shl_fu_340_p3;
wire  signed [22:0] sext_ln81_3_fu_356_p1;
wire   [22:0] sub_ln81_fu_360_p2;
wire  signed [31:0] sext_ln81_4_fu_366_p1;
wire   [31:0] add_ln81_fu_370_p2;
wire  signed [29:0] grp_fu_433_p3;
wire   [8:0] grp_fu_424_p1;
wire   [8:0] grp_fu_433_p1;
reg    grp_fu_424_ce;
reg    grp_fu_433_ce;
reg    ap_block_state16_on_subcall_done;
reg   [18:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    regslice_both_output_r_U_apdone_blk;
reg    ap_block_state19;
wire    regslice_both_input_r_U_apdone_blk;
wire   [15:0] input_r_TDATA_int_regslice;
wire    input_r_TVALID_int_regslice;
reg    input_r_TREADY_int_regslice;
wire    regslice_both_input_r_U_ack_in;
wire   [15:0] output_r_TDATA_int_regslice;
reg    output_r_TVALID_int_regslice;
wire    output_r_TREADY_int_regslice;
wire    regslice_both_output_r_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 mod_value = 2'd0;
#0 y2 = 16'd0;
#0 y1_phase1 = 16'd0;
#0 y1_phase2 = 16'd0;
#0 y1_phase3 = 16'd0;
#0 ap_CS_fsm = 19'd1;
#0 grp_FIR_filtertest_2_fu_176_ap_start_reg = 1'b0;
#0 grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start_reg = 1'b0;
#0 grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start_reg = 1'b0;
#0 grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start_reg = 1'b0;
#0 grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start_reg = 1'b0;
#0 grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start_reg = 1'b0;
end

FIR_HLS_b_FIR_dec_int_40_ROM_AUTO_1R #(
    .DataWidth( 14 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
b_FIR_dec_int_40_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(b_FIR_dec_int_40_address0),
    .ce0(b_FIR_dec_int_40_ce0),
    .q0(b_FIR_dec_int_40_q0)
);

FIR_HLS_H_filter_FIR_dec_40_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
H_filter_FIR_dec_40_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(H_filter_FIR_dec_40_address0),
    .ce0(H_filter_FIR_dec_40_ce0),
    .we0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_we0),
    .d0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_d0),
    .q0(H_filter_FIR_dec_40_q0),
    .address1(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_address1),
    .ce1(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_ce1),
    .q1(H_filter_FIR_dec_40_q1)
);

FIR_HLS_H_filter_FIR_kernel_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 117 ),
    .AddressWidth( 7 ))
H_filter_FIR_kernel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(H_filter_FIR_kernel_address0),
    .ce0(H_filter_FIR_kernel_ce0),
    .we0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_we0),
    .d0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_d0),
    .q0(H_filter_FIR_kernel_q0),
    .address1(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_address1),
    .ce1(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_ce1),
    .q1(H_filter_FIR_kernel_q1)
);

FIR_HLS_H_filter_FIR_dec_40_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
H_filter_FIR_int_40_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(H_filter_FIR_int_40_address0),
    .ce0(H_filter_FIR_int_40_ce0),
    .we0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_we0),
    .d0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_d0),
    .q0(H_filter_FIR_int_40_q0),
    .address1(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_address1),
    .ce1(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_ce1),
    .q1(H_filter_FIR_int_40_q1)
);

FIR_HLS_H_filter_FIR_dec_43_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
H_filter_FIR_dec_43_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_FIR_filtertest_2_fu_176_FIR_delays_address0),
    .ce0(H_filter_FIR_dec_43_ce0),
    .we0(H_filter_FIR_dec_43_we0),
    .d0(grp_FIR_filtertest_2_fu_176_FIR_delays_d0),
    .q0(H_filter_FIR_dec_43_q0),
    .address1(grp_FIR_filtertest_2_fu_176_FIR_delays_address1),
    .ce1(H_filter_FIR_dec_43_ce1),
    .q1(H_filter_FIR_dec_43_q1)
);

FIR_HLS_b_FIR_dec_int_43_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
b_FIR_dec_int_43_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_FIR_filtertest_2_fu_176_FIR_coe_address0),
    .ce0(b_FIR_dec_int_43_ce0),
    .q0(b_FIR_dec_int_43_q0)
);

FIR_HLS_H_filter_FIR_dec_43_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
H_filter_FIR_int_41_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(H_filter_FIR_int_41_address0),
    .ce0(H_filter_FIR_int_41_ce0),
    .we0(H_filter_FIR_int_41_we0),
    .d0(H_filter_FIR_int_41_d0),
    .q0(H_filter_FIR_int_41_q0),
    .address1(grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_address1),
    .ce1(H_filter_FIR_int_41_ce1),
    .q1(H_filter_FIR_int_41_q1)
);

FIR_HLS_b_FIR_dec_int_41_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
b_FIR_dec_int_41_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(b_FIR_dec_int_41_address0),
    .ce0(b_FIR_dec_int_41_ce0),
    .q0(b_FIR_dec_int_41_q0)
);

FIR_HLS_H_filter_FIR_dec_43_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
H_filter_FIR_dec_42_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_FIR_filtertest_2_fu_176_FIR_delays_address0),
    .ce0(H_filter_FIR_dec_42_ce0),
    .we0(H_filter_FIR_dec_42_we0),
    .d0(grp_FIR_filtertest_2_fu_176_FIR_delays_d0),
    .q0(H_filter_FIR_dec_42_q0),
    .address1(grp_FIR_filtertest_2_fu_176_FIR_delays_address1),
    .ce1(H_filter_FIR_dec_42_ce1),
    .q1(H_filter_FIR_dec_42_q1)
);

FIR_HLS_b_FIR_dec_int_42_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
b_FIR_dec_int_42_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_FIR_filtertest_2_fu_176_FIR_coe_address0),
    .ce0(b_FIR_dec_int_42_ce0),
    .q0(b_FIR_dec_int_42_q0)
);

FIR_HLS_H_filter_FIR_dec_43_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
H_filter_FIR_int_42_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_FIR_filtertest_2_fu_176_FIR_delays_address0),
    .ce0(H_filter_FIR_int_42_ce0),
    .we0(H_filter_FIR_int_42_we0),
    .d0(grp_FIR_filtertest_2_fu_176_FIR_delays_d0),
    .q0(H_filter_FIR_int_42_q0),
    .address1(grp_FIR_filtertest_2_fu_176_FIR_delays_address1),
    .ce1(H_filter_FIR_int_42_ce1),
    .q1(H_filter_FIR_int_42_q1)
);

FIR_HLS_H_filter_FIR_dec_43_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
H_filter_FIR_dec_41_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_FIR_filtertest_2_fu_176_FIR_delays_address0),
    .ce0(H_filter_FIR_dec_41_ce0),
    .we0(H_filter_FIR_dec_41_we0),
    .d0(grp_FIR_filtertest_2_fu_176_FIR_delays_d0),
    .q0(H_filter_FIR_dec_41_q0),
    .address1(grp_FIR_filtertest_2_fu_176_FIR_delays_address1),
    .ce1(H_filter_FIR_dec_41_ce1),
    .q1(H_filter_FIR_dec_41_q1)
);

FIR_HLS_H_filter_FIR_dec_43_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
H_filter_FIR_int_43_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_FIR_filtertest_2_fu_176_FIR_delays_address0),
    .ce0(H_filter_FIR_int_43_ce0),
    .we0(H_filter_FIR_int_43_we0),
    .d0(grp_FIR_filtertest_2_fu_176_FIR_delays_d0),
    .q0(H_filter_FIR_int_43_q0),
    .address1(grp_FIR_filtertest_2_fu_176_FIR_delays_address1),
    .ce1(H_filter_FIR_int_43_ce1),
    .q1(H_filter_FIR_int_43_q1)
);

FIR_HLS_FIR_filtertest_2 grp_FIR_filtertest_2_fu_176(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_FIR_filtertest_2_fu_176_ap_start),
    .ap_done(grp_FIR_filtertest_2_fu_176_ap_done),
    .ap_idle(grp_FIR_filtertest_2_fu_176_ap_idle),
    .ap_ready(grp_FIR_filtertest_2_fu_176_ap_ready),
    .FIR_delays_address0(grp_FIR_filtertest_2_fu_176_FIR_delays_address0),
    .FIR_delays_ce0(grp_FIR_filtertest_2_fu_176_FIR_delays_ce0),
    .FIR_delays_we0(grp_FIR_filtertest_2_fu_176_FIR_delays_we0),
    .FIR_delays_d0(grp_FIR_filtertest_2_fu_176_FIR_delays_d0),
    .FIR_delays_q0(grp_FIR_filtertest_2_fu_176_FIR_delays_q0),
    .FIR_delays_address1(grp_FIR_filtertest_2_fu_176_FIR_delays_address1),
    .FIR_delays_ce1(grp_FIR_filtertest_2_fu_176_FIR_delays_ce1),
    .FIR_delays_q1(grp_FIR_filtertest_2_fu_176_FIR_delays_q1),
    .FIR_coe_address0(grp_FIR_filtertest_2_fu_176_FIR_coe_address0),
    .FIR_coe_ce0(grp_FIR_filtertest_2_fu_176_FIR_coe_ce0),
    .FIR_coe_q0(grp_FIR_filtertest_2_fu_176_FIR_coe_q0),
    .x_n(grp_FIR_filtertest_2_fu_176_x_n),
    .ap_return(grp_FIR_filtertest_2_fu_176_ap_return)
);

FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_65_1 grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start),
    .ap_done(grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_done),
    .ap_idle(grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_idle),
    .ap_ready(grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_ready),
    .y_3_out(grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_y_3_out),
    .y_3_out_ap_vld(grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_y_3_out_ap_vld),
    .H_filter_FIR_int_41_address0(grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_H_filter_FIR_int_41_address0),
    .H_filter_FIR_int_41_ce0(grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_H_filter_FIR_int_41_ce0),
    .H_filter_FIR_int_41_q0(H_filter_FIR_int_41_q0),
    .b_FIR_dec_int_41_address0(grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_b_FIR_dec_int_41_address0),
    .b_FIR_dec_int_41_ce0(grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_b_FIR_dec_int_41_ce0),
    .b_FIR_dec_int_41_q0(b_FIR_dec_int_41_q0)
);

FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_69_2 grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start),
    .ap_done(grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_done),
    .ap_idle(grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_idle),
    .ap_ready(grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_ready),
    .H_filter_FIR_int_41_address0(grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_address0),
    .H_filter_FIR_int_41_ce0(grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_ce0),
    .H_filter_FIR_int_41_we0(grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_we0),
    .H_filter_FIR_int_41_d0(grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_d0),
    .H_filter_FIR_int_41_address1(grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_address1),
    .H_filter_FIR_int_41_ce1(grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_ce1),
    .H_filter_FIR_int_41_q1(H_filter_FIR_int_41_q1)
);

FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_83_1 grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start),
    .ap_done(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_done),
    .ap_idle(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_idle),
    .ap_ready(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_ready),
    .sext_ln83(x_n_1_reg_447),
    .b_FIR_dec_int_40_address0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_b_FIR_dec_int_40_address0),
    .b_FIR_dec_int_40_ce0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_b_FIR_dec_int_40_ce0),
    .b_FIR_dec_int_40_q0(b_FIR_dec_int_40_q0),
    .H_filter_FIR_dec_40_address0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_address0),
    .H_filter_FIR_dec_40_ce0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_ce0),
    .H_filter_FIR_dec_40_we0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_we0),
    .H_filter_FIR_dec_40_d0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_d0),
    .H_filter_FIR_dec_40_address1(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_address1),
    .H_filter_FIR_dec_40_ce1(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_ce1),
    .H_filter_FIR_dec_40_q1(H_filter_FIR_dec_40_q1)
);

FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_83_11 grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start),
    .ap_done(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_done),
    .ap_idle(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_idle),
    .ap_ready(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_ready),
    .sext_ln84(x_n_reg_488),
    .H_filter_FIR_kernel_address0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_address0),
    .H_filter_FIR_kernel_ce0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_ce0),
    .H_filter_FIR_kernel_we0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_we0),
    .H_filter_FIR_kernel_d0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_d0),
    .H_filter_FIR_kernel_address1(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_address1),
    .H_filter_FIR_kernel_ce1(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_ce1),
    .H_filter_FIR_kernel_q1(H_filter_FIR_kernel_q1)
);

FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_83_12 grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start),
    .ap_done(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_done),
    .ap_idle(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_idle),
    .ap_ready(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_ready),
    .sext_ln83_1(y_3_reg_493),
    .b_FIR_dec_int_40_address0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_b_FIR_dec_int_40_address0),
    .b_FIR_dec_int_40_ce0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_b_FIR_dec_int_40_ce0),
    .b_FIR_dec_int_40_q0(b_FIR_dec_int_40_q0),
    .H_filter_FIR_int_40_address0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_address0),
    .H_filter_FIR_int_40_ce0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_ce0),
    .H_filter_FIR_int_40_we0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_we0),
    .H_filter_FIR_int_40_d0(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_d0),
    .H_filter_FIR_int_40_address1(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_address1),
    .H_filter_FIR_int_40_ce1(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_ce1),
    .H_filter_FIR_int_40_q1(H_filter_FIR_int_40_q1)
);

FIR_HLS_mac_muladd_16s_9ns_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_9ns_32s_32_4_1_U31(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sext_ln81_fu_241_p0),
    .din1(grp_fu_424_p1),
    .din2(H_filter_FIR_dec_40_q0),
    .ce(grp_fu_424_ce),
    .dout(grp_fu_424_p3)
);

FIR_HLS_mac_muladd_16s_9ns_30s_30_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
mac_muladd_16s_9ns_30s_30_4_1_U32(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(y_3_fu_375_p4),
    .din1(grp_fu_433_p1),
    .din2(trunc_ln81_reg_503),
    .ce(grp_fu_433_ce),
    .dout(grp_fu_433_p3)
);

FIR_HLS_regslice_both #(
    .DataWidth( 16 ))
regslice_both_input_r_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TDATA),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_U_ack_in),
    .data_out(input_r_TDATA_int_regslice),
    .vld_out(input_r_TVALID_int_regslice),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_U_apdone_blk)
);

FIR_HLS_regslice_both #(
    .DataWidth( 16 ))
regslice_both_output_r_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_r_TDATA_int_regslice),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(output_r_TREADY_int_regslice),
    .data_out(output_r_TDATA),
    .vld_out(regslice_both_output_r_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start_reg <= 1'b1;
        end else if ((grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_ready == 1'b1)) begin
            grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start_reg <= 1'b1;
        end else if ((grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_ready == 1'b1)) begin
            grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start_reg <= 1'b1;
        end else if ((grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_ready == 1'b1)) begin
            grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start_reg <= 1'b1;
        end else if ((grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_ready == 1'b1)) begin
            grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start_reg <= 1'b1;
        end else if ((grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_ready == 1'b1)) begin
            grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_FIR_filtertest_2_fu_176_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state2) | ((grp_FIR_filtertest_2_fu_176_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((grp_FIR_filtertest_2_fu_176_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
            grp_FIR_filtertest_2_fu_176_ap_start_reg <= 1'b1;
        end else if ((grp_FIR_filtertest_2_fu_176_ap_ready == 1'b1)) begin
            grp_FIR_filtertest_2_fu_176_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((output_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state18_on_subcall_done)) & (mod_value_load_reg_453 == 2'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        data_out_load_reg_163 <= {{grp_fu_433_p3[29:16]}};
    end else if (((grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        data_out_load_reg_163 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_y_3_out;
    end else if (((grp_FIR_filtertest_2_fu_176_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        data_out_load_reg_163 <= trunc_ln39_fu_251_p1;
    end else if (((grp_FIR_filtertest_2_fu_176_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        data_out_load_reg_163 <= trunc_ln45_fu_290_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_FIR_filtertest_2_fu_176_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        mod_value <= 2'd3;
    end else if (((grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        mod_value <= 2'd2;
    end else if (((grp_FIR_filtertest_2_fu_176_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        mod_value <= 2'd0;
    end else if ((~((output_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state18_on_subcall_done)) & (mod_value_load_reg_453 == 2'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        mod_value <= 2'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        H_filter_FIR_kernel_load_reg_483 <= H_filter_FIR_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        mod_value_load_reg_453 <= mod_value;
        x_n_1_reg_447 <= input_r_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        trunc_ln81_reg_503 <= trunc_ln81_fu_395_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        x_n_reg_488 <= x_n_fu_333_p2;
        y2 <= {{add_ln81_fu_370_p2[31:16]}};
        y_3_reg_493 <= {{add_ln81_fu_370_p2[31:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state7_on_subcall_done) & (1'b1 == ap_CS_fsm_state7))) begin
        y1_phase1 <= grp_FIR_filtertest_2_fu_176_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_FIR_filtertest_2_fu_176_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        y1_phase2 <= grp_FIR_filtertest_2_fu_176_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_FIR_filtertest_2_fu_176_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        y1_phase3 <= grp_FIR_filtertest_2_fu_176_ap_return;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        H_filter_FIR_dec_40_address0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_address0;
    end else begin
        H_filter_FIR_dec_40_address0 = 3'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        H_filter_FIR_dec_40_ce0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_ce0;
    end else begin
        H_filter_FIR_dec_40_ce0 = H_filter_FIR_dec_40_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        H_filter_FIR_dec_40_ce0_local = 1'b1;
    end else begin
        H_filter_FIR_dec_40_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        H_filter_FIR_dec_41_ce0 = grp_FIR_filtertest_2_fu_176_FIR_delays_ce0;
    end else begin
        H_filter_FIR_dec_41_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        H_filter_FIR_dec_41_ce1 = grp_FIR_filtertest_2_fu_176_FIR_delays_ce1;
    end else begin
        H_filter_FIR_dec_41_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        H_filter_FIR_dec_41_we0 = grp_FIR_filtertest_2_fu_176_FIR_delays_we0;
    end else begin
        H_filter_FIR_dec_41_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        H_filter_FIR_dec_42_ce0 = grp_FIR_filtertest_2_fu_176_FIR_delays_ce0;
    end else begin
        H_filter_FIR_dec_42_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        H_filter_FIR_dec_42_ce1 = grp_FIR_filtertest_2_fu_176_FIR_delays_ce1;
    end else begin
        H_filter_FIR_dec_42_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        H_filter_FIR_dec_42_we0 = grp_FIR_filtertest_2_fu_176_FIR_delays_we0;
    end else begin
        H_filter_FIR_dec_42_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        H_filter_FIR_dec_43_ce0 = grp_FIR_filtertest_2_fu_176_FIR_delays_ce0;
    end else begin
        H_filter_FIR_dec_43_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        H_filter_FIR_dec_43_ce1 = grp_FIR_filtertest_2_fu_176_FIR_delays_ce1;
    end else begin
        H_filter_FIR_dec_43_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        H_filter_FIR_dec_43_we0 = grp_FIR_filtertest_2_fu_176_FIR_delays_we0;
    end else begin
        H_filter_FIR_dec_43_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((mod_value_load_reg_453 == 2'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        H_filter_FIR_int_40_address0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_address0;
    end else begin
        H_filter_FIR_int_40_address0 = 3'd0;
    end
end

always @ (*) begin
    if (((mod_value_load_reg_453 == 2'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        H_filter_FIR_int_40_ce0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_ce0;
    end else begin
        H_filter_FIR_int_40_ce0 = H_filter_FIR_int_40_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        H_filter_FIR_int_40_ce0_local = 1'b1;
    end else begin
        H_filter_FIR_int_40_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        H_filter_FIR_int_41_address0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        H_filter_FIR_int_41_address0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_H_filter_FIR_int_41_address0;
    end else begin
        H_filter_FIR_int_41_address0 = 3'd4;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        H_filter_FIR_int_41_ce0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        H_filter_FIR_int_41_ce0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_H_filter_FIR_int_41_ce0;
    end else begin
        H_filter_FIR_int_41_ce0 = H_filter_FIR_int_41_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        H_filter_FIR_int_41_ce0_local = 1'b1;
    end else begin
        H_filter_FIR_int_41_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        H_filter_FIR_int_41_ce1 = grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_ce1;
    end else begin
        H_filter_FIR_int_41_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        H_filter_FIR_int_41_d0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_d0;
    end else begin
        H_filter_FIR_int_41_d0 = shl_ln_fu_261_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        H_filter_FIR_int_41_we0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_we0;
    end else begin
        H_filter_FIR_int_41_we0 = (1'b0 | H_filter_FIR_int_41_we0_out);
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        H_filter_FIR_int_41_we0_local = 1'b1;
    end else begin
        H_filter_FIR_int_41_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        H_filter_FIR_int_42_ce0 = grp_FIR_filtertest_2_fu_176_FIR_delays_ce0;
    end else begin
        H_filter_FIR_int_42_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        H_filter_FIR_int_42_ce1 = grp_FIR_filtertest_2_fu_176_FIR_delays_ce1;
    end else begin
        H_filter_FIR_int_42_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        H_filter_FIR_int_42_we0 = grp_FIR_filtertest_2_fu_176_FIR_delays_we0;
    end else begin
        H_filter_FIR_int_42_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        H_filter_FIR_int_43_ce0 = grp_FIR_filtertest_2_fu_176_FIR_delays_ce0;
    end else begin
        H_filter_FIR_int_43_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        H_filter_FIR_int_43_ce1 = grp_FIR_filtertest_2_fu_176_FIR_delays_ce1;
    end else begin
        H_filter_FIR_int_43_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        H_filter_FIR_int_43_we0 = grp_FIR_filtertest_2_fu_176_FIR_delays_we0;
    end else begin
        H_filter_FIR_int_43_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        H_filter_FIR_kernel_address0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_address0;
    end else begin
        H_filter_FIR_kernel_address0 = 7'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        H_filter_FIR_kernel_ce0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_ce0;
    end else begin
        H_filter_FIR_kernel_ce0 = H_filter_FIR_kernel_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        H_filter_FIR_kernel_ce0_local = 1'b1;
    end else begin
        H_filter_FIR_kernel_ce0_local = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_FIR_filtertest_2_fu_176_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_FIR_filtertest_2_fu_176_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state16_on_subcall_done)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if (((output_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state18_on_subcall_done))) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state19)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((input_r_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_FIR_filtertest_2_fu_176_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_FIR_filtertest_2_fu_176_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state7_on_subcall_done)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((mod_value_load_reg_453 == 2'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_phi_mux_data_out_load_phi_fu_166_p8 = {{grp_fu_433_p3[29:16]}};
    end else begin
        ap_phi_mux_data_out_load_phi_fu_166_p8 = data_out_load_reg_163;
    end
end

always @ (*) begin
    if (((mod_value_load_reg_453 == 2'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        b_FIR_dec_int_40_address0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_b_FIR_dec_int_40_address0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        b_FIR_dec_int_40_address0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_b_FIR_dec_int_40_address0;
    end else begin
        b_FIR_dec_int_40_address0 = 'bx;
    end
end

always @ (*) begin
    if (((mod_value_load_reg_453 == 2'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        b_FIR_dec_int_40_ce0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_b_FIR_dec_int_40_ce0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        b_FIR_dec_int_40_ce0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_b_FIR_dec_int_40_ce0;
    end else begin
        b_FIR_dec_int_40_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        b_FIR_dec_int_41_address0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_b_FIR_dec_int_41_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        b_FIR_dec_int_41_address0 = grp_FIR_filtertest_2_fu_176_FIR_coe_address0;
    end else begin
        b_FIR_dec_int_41_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        b_FIR_dec_int_41_ce0 = grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_b_FIR_dec_int_41_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        b_FIR_dec_int_41_ce0 = grp_FIR_filtertest_2_fu_176_FIR_coe_ce0;
    end else begin
        b_FIR_dec_int_41_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        b_FIR_dec_int_42_ce0 = grp_FIR_filtertest_2_fu_176_FIR_coe_ce0;
    end else begin
        b_FIR_dec_int_42_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state12))) begin
        b_FIR_dec_int_43_ce0 = grp_FIR_filtertest_2_fu_176_FIR_coe_ce0;
    end else begin
        b_FIR_dec_int_43_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_FIR_filtertest_2_fu_176_FIR_coe_q0 = b_FIR_dec_int_41_q0;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_FIR_filtertest_2_fu_176_FIR_coe_q0 = b_FIR_dec_int_43_q0;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_FIR_filtertest_2_fu_176_FIR_coe_q0 = b_FIR_dec_int_42_q0;
    end else begin
        grp_FIR_filtertest_2_fu_176_FIR_coe_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_FIR_filtertest_2_fu_176_FIR_delays_q0 = H_filter_FIR_int_43_q0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_FIR_filtertest_2_fu_176_FIR_delays_q0 = H_filter_FIR_dec_41_q0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_FIR_filtertest_2_fu_176_FIR_delays_q0 = H_filter_FIR_dec_43_q0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_FIR_filtertest_2_fu_176_FIR_delays_q0 = H_filter_FIR_int_42_q0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_FIR_filtertest_2_fu_176_FIR_delays_q0 = H_filter_FIR_dec_42_q0;
    end else begin
        grp_FIR_filtertest_2_fu_176_FIR_delays_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_FIR_filtertest_2_fu_176_FIR_delays_q1 = H_filter_FIR_int_43_q1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_FIR_filtertest_2_fu_176_FIR_delays_q1 = H_filter_FIR_dec_41_q1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_FIR_filtertest_2_fu_176_FIR_delays_q1 = H_filter_FIR_dec_43_q1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_FIR_filtertest_2_fu_176_FIR_delays_q1 = H_filter_FIR_int_42_q1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_FIR_filtertest_2_fu_176_FIR_delays_q1 = H_filter_FIR_dec_42_q1;
    end else begin
        grp_FIR_filtertest_2_fu_176_FIR_delays_q1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_FIR_filtertest_2_fu_176_x_n = y2;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_FIR_filtertest_2_fu_176_x_n = x_n_1_reg_447;
    end else begin
        grp_FIR_filtertest_2_fu_176_x_n = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | ((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_fu_424_ce = 1'b1;
    end else begin
        grp_fu_424_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state15) | (~((output_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state18_on_subcall_done)) & (1'b1 == ap_CS_fsm_state18)) | ((1'b0 == ap_block_state16_on_subcall_done) & (1'b1 == ap_CS_fsm_state16)))) begin
        grp_fu_433_ce = 1'b1;
    end else begin
        grp_fu_433_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        input_r_TDATA_blk_n = input_r_TVALID_int_regslice;
    end else begin
        input_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((input_r_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        input_r_TREADY_int_regslice = 1'b1;
    end else begin
        input_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        output_r_TDATA_blk_n = output_r_TREADY_int_regslice;
    end else begin
        output_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((output_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state18_on_subcall_done)) & (1'b1 == ap_CS_fsm_state18))) begin
        output_r_TVALID_int_regslice = 1'b1;
    end else begin
        output_r_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((input_r_TVALID_int_regslice == 1'b1) & (mod_value_load_load_fu_233_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else if (((input_r_TVALID_int_regslice == 1'b1) & (mod_value_load_load_fu_233_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((input_r_TVALID_int_regslice == 1'b1) & (mod_value_load_load_fu_233_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((input_r_TVALID_int_regslice == 1'b1) & (mod_value_load_load_fu_233_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_FIR_filtertest_2_fu_176_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_FIR_filtertest_2_fu_176_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b0 == ap_block_state7_on_subcall_done) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_FIR_filtertest_2_fu_176_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((grp_FIR_filtertest_2_fu_176_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((1'b0 == ap_block_state16_on_subcall_done) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if ((~((output_r_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state18_on_subcall_done)) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((1'b0 == ap_block_state19) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign H_filter_FIR_int_41_we0_out = H_filter_FIR_int_41_we0_local;

assign add_ln24_1_fu_327_p2 = (y1_phase3 + y_1_fu_300_p4);

assign add_ln24_fu_321_p2 = (y1_phase2 + y1_phase1);

assign add_ln81_fu_370_p2 = ($signed(sext_ln81_4_fu_366_p1) + $signed(H_filter_FIR_kernel_load_reg_483));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state16_on_subcall_done = ((grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_done == 1'b0) | (grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state18_on_subcall_done = ((grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_done == 1'b0) & (mod_value_load_reg_453 == 2'd0));
end

always @ (*) begin
    ap_block_state19 = ((output_r_TREADY_int_regslice == 1'b0) | (regslice_both_output_r_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_block_state7_on_subcall_done = ((grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_done == 1'b0) | (grp_FIR_filtertest_2_fu_176_ap_done == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start = grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start_reg;

assign grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start = grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start_reg;

assign grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start = grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start_reg;

assign grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start = grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start_reg;

assign grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start = grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start_reg;

assign grp_FIR_filtertest_2_fu_176_ap_start = grp_FIR_filtertest_2_fu_176_ap_start_reg;

assign grp_fu_424_p1 = 25'd436;

assign grp_fu_433_p1 = 25'd436;

assign input_r_TREADY = regslice_both_input_r_U_ack_in;

assign mod_value_load_load_fu_233_p1 = mod_value;

assign output_r_TDATA_int_regslice = {{ap_phi_mux_data_out_load_phi_fu_166_p8}, {2'd0}};

assign output_r_TVALID = regslice_both_output_r_U_vld_out;

assign p_shl_fu_340_p3 = {{x_n_fu_333_p2}, {7'd0}};

assign sext_ln81_3_fu_356_p1 = $signed(tmp_fu_348_p3);

assign sext_ln81_4_fu_366_p1 = $signed(sub_ln81_fu_360_p2);

assign sext_ln81_fu_241_p0 = input_r_TDATA_int_regslice;

assign shl_ln_fu_261_p3 = {{y2}, {16'd0}};

assign sub_ln81_fu_360_p2 = ($signed(p_shl_fu_340_p3) - $signed(sext_ln81_3_fu_356_p1));

assign tmp_fu_348_p3 = {{x_n_fu_333_p2}, {2'd0}};

assign trunc_ln39_fu_251_p1 = grp_FIR_filtertest_2_fu_176_ap_return[13:0];

assign trunc_ln45_fu_290_p1 = grp_FIR_filtertest_2_fu_176_ap_return[13:0];

assign trunc_ln81_fu_395_p1 = H_filter_FIR_int_40_q0[29:0];

assign x_n_fu_333_p2 = (add_ln24_1_fu_327_p2 + add_ln24_fu_321_p2);

assign y_1_fu_300_p4 = {{grp_fu_424_p3[31:16]}};

assign y_3_fu_375_p4 = {{add_ln81_fu_370_p2[31:16]}};

endmodule //FIR_HLS
