-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FIR_HLS_FIR_filter_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    FIR_delays_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    FIR_delays_ce0 : OUT STD_LOGIC;
    FIR_delays_we0 : OUT STD_LOGIC;
    FIR_delays_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    FIR_delays_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    FIR_delays_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    FIR_delays_ce1 : OUT STD_LOGIC;
    FIR_delays_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    FIR_coe_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    FIR_coe_ce0 : OUT STD_LOGIC;
    FIR_coe_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    x_n : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of FIR_HLS_FIR_filter_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal y_reg_118 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_start : STD_LOGIC;
    signal grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_done : STD_LOGIC;
    signal grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_idle : STD_LOGIC;
    signal grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_ready : STD_LOGIC;
    signal grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_coe_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_coe_ce0 : STD_LOGIC;
    signal grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_ce0 : STD_LOGIC;
    signal grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_we0 : STD_LOGIC;
    signal grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_ce1 : STD_LOGIC;
    signal grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal FIR_coe_ce0_local : STD_LOGIC;
    signal FIR_delays_ce0_local : STD_LOGIC;
    signal sext_ln39_fu_65_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln39_2_fu_69_p0 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln39_fu_73_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal shl_ln_fu_79_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln39_fu_87_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component FIR_HLS_FIR_filter_2_Pipeline_VITIS_LOOP_41_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        FIR_coe_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        FIR_coe_ce0 : OUT STD_LOGIC;
        FIR_coe_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        FIR_delays_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        FIR_delays_ce0 : OUT STD_LOGIC;
        FIR_delays_we0 : OUT STD_LOGIC;
        FIR_delays_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        FIR_delays_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        FIR_delays_ce1 : OUT STD_LOGIC;
        FIR_delays_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        sext_ln39 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component FIR_HLS_mul_16s_15s_31_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;



begin
    grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56 : component FIR_HLS_FIR_filter_2_Pipeline_VITIS_LOOP_41_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_start,
        ap_done => grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_done,
        ap_idle => grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_idle,
        ap_ready => grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_ready,
        FIR_coe_address0 => grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_coe_address0,
        FIR_coe_ce0 => grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_coe_ce0,
        FIR_coe_q0 => FIR_coe_q0,
        FIR_delays_address0 => grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_address0,
        FIR_delays_ce0 => grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_ce0,
        FIR_delays_we0 => grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_we0,
        FIR_delays_d0 => grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_d0,
        FIR_delays_address1 => grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_address1,
        FIR_delays_ce1 => grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_ce1,
        FIR_delays_q1 => FIR_delays_q1,
        sext_ln39 => x_n);

    mul_16s_15s_31_1_1_U6 : component FIR_HLS_mul_16s_15s_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 31)
    port map (
        din0 => sext_ln39_fu_65_p0,
        din1 => sext_ln39_2_fu_69_p0,
        dout => mul_ln39_fu_73_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_ready = ap_const_logic_1)) then 
                    grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                y_reg_118 <= add_ln39_fu_87_p2(31 downto 16);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_done, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;

    FIR_coe_address0_assign_proc : process(grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_coe_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FIR_coe_address0 <= grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_coe_address0;
        else 
            FIR_coe_address0 <= ap_const_lv64_0(3 - 1 downto 0);
        end if; 
    end process;


    FIR_coe_ce0_assign_proc : process(grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_coe_ce0, ap_CS_fsm_state4, FIR_coe_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FIR_coe_ce0 <= grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_coe_ce0;
        else 
            FIR_coe_ce0 <= FIR_coe_ce0_local;
        end if; 
    end process;


    FIR_coe_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            FIR_coe_ce0_local <= ap_const_logic_1;
        else 
            FIR_coe_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    FIR_delays_address0_assign_proc : process(grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FIR_delays_address0 <= grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_address0;
        else 
            FIR_delays_address0 <= ap_const_lv64_0(3 - 1 downto 0);
        end if; 
    end process;

    FIR_delays_address1 <= grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_address1;

    FIR_delays_ce0_assign_proc : process(grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_ce0, ap_CS_fsm_state4, FIR_delays_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FIR_delays_ce0 <= grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_ce0;
        else 
            FIR_delays_ce0 <= FIR_delays_ce0_local;
        end if; 
    end process;


    FIR_delays_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            FIR_delays_ce0_local <= ap_const_logic_1;
        else 
            FIR_delays_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    FIR_delays_ce1_assign_proc : process(grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FIR_delays_ce1 <= grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_ce1;
        else 
            FIR_delays_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    FIR_delays_d0 <= grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_d0;

    FIR_delays_we0_assign_proc : process(grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FIR_delays_we0 <= grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_FIR_delays_we0;
        else 
            FIR_delays_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln39_fu_87_p2 <= std_logic_vector(unsigned(FIR_delays_q0) + unsigned(shl_ln_fu_79_p3));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_done)
    begin
        if ((grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_done, ap_CS_fsm_state4)
    begin
        if ((((grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_done, ap_CS_fsm_state4)
    begin
        if (((grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= y_reg_118;
    grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_start <= grp_FIR_filter_2_Pipeline_VITIS_LOOP_41_1_fu_56_ap_start_reg;
    sext_ln39_2_fu_69_p0 <= FIR_coe_q0;
    sext_ln39_fu_65_p0 <= x_n;
    shl_ln_fu_79_p3 <= (mul_ln39_fu_73_p2 & ap_const_lv1_0);
end behav;
