-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FIR_HLS_FIR_filter_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    FIR_delays_read : IN STD_LOGIC_VECTOR (31 downto 0);
    FIR_delays_read_14 : IN STD_LOGIC_VECTOR (31 downto 0);
    FIR_delays_read_15 : IN STD_LOGIC_VECTOR (31 downto 0);
    FIR_delays_read_16 : IN STD_LOGIC_VECTOR (31 downto 0);
    FIR_delays_read_17 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_n : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of FIR_HLS_FIR_filter_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv43_7FFFFFFFBFD : STD_LOGIC_VECTOR (42 downto 0) := "1111111111111111111111111111111101111111101";
    constant ap_const_lv44_FFFFFFFFBFD : STD_LOGIC_VECTOR (43 downto 0) := "11111111111111111111111111111111101111111101";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal x_n_read_reg_637 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal FIR_delays_read_1_reg_642 : STD_LOGIC_VECTOR (31 downto 0);
    signal FIR_delays_read_2_reg_647 : STD_LOGIC_VECTOR (31 downto 0);
    signal FIR_delays_read_3_reg_657 : STD_LOGIC_VECTOR (31 downto 0);
    signal FIR_delays_read_4_reg_667 : STD_LOGIC_VECTOR (31 downto 0);
    signal FIR_delays_read_9_reg_673 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_reg_681 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln45_fu_140_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal mul_ln45_1_fu_145_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_1_fu_150_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_2_fu_162_p3 : STD_LOGIC_VECTOR (36 downto 0);
    signal sext_ln45_fu_158_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal sext_ln45_1_fu_170_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal tmp_3_fu_180_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal sub_ln45_fu_174_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal sext_ln45_3_fu_188_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal tmp_4_fu_198_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal sub_ln45_1_fu_192_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal sext_ln45_4_fu_206_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal add_ln45_5_fu_210_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal FIR_accu32_fu_216_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_fu_226_p3 : STD_LOGIC_VECTOR (40 downto 0);
    signal sext_ln45_2_fu_238_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln45_6_fu_234_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal mul_ln45_fu_140_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal add_ln45_fu_243_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal tmp_9_fu_266_p3 : STD_LOGIC_VECTOR (42 downto 0);
    signal tmp_10_fu_277_p3 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_11_fu_288_p3 : STD_LOGIC_VECTOR (41 downto 0);
    signal sext_ln45_12_fu_284_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal sext_ln45_13_fu_295_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_12_fu_305_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal add_ln45_6_fu_299_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal sext_ln45_14_fu_312_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_13_fu_322_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal sub_ln45_2_fu_316_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal sext_ln45_15_fu_329_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_14_fu_339_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln45_7_fu_333_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal sext_ln45_16_fu_346_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal add_ln45_8_fu_350_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal sext_ln45_10_fu_273_p1 : STD_LOGIC_VECTOR (46 downto 0);
    signal sext_ln45_5_fu_356_p1 : STD_LOGIC_VECTOR (46 downto 0);
    signal add_ln45_1_fu_360_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal tmp_5_fu_366_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_15_fu_384_p3 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_16_fu_395_p3 : STD_LOGIC_VECTOR (41 downto 0);
    signal sext_ln45_17_fu_391_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal sext_ln45_18_fu_402_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_17_fu_412_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal add_ln45_9_fu_406_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal sext_ln45_19_fu_419_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_18_fu_429_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal sub_ln45_3_fu_423_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal sext_ln45_20_fu_436_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_19_fu_446_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln45_10_fu_440_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal sext_ln45_21_fu_453_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal add_ln45_11_fu_457_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal and_ln45_1_fu_376_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal sext_ln45_7_fu_463_p1 : STD_LOGIC_VECTOR (46 downto 0);
    signal add_ln45_2_fu_467_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal tmp_6_fu_473_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln45_1_fu_145_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal and_ln45_2_fu_483_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal sext_ln45_9_fu_495_p1 : STD_LOGIC_VECTOR (46 downto 0);
    signal add_ln45_3_fu_499_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal tmp_7_fu_505_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_20_fu_523_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_21_fu_534_p3 : STD_LOGIC_VECTOR (36 downto 0);
    signal sext_ln45_22_fu_530_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal sext_ln45_23_fu_541_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal tmp_22_fu_551_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal sub_ln45_4_fu_545_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal sext_ln45_24_fu_558_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal tmp_23_fu_568_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal sub_ln45_5_fu_562_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal sext_ln45_25_fu_575_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal add_ln45_12_fu_579_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal and_ln45_3_fu_515_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal sext_ln45_11_fu_585_p1 : STD_LOGIC_VECTOR (46 downto 0);
    signal add_ln45_4_fu_589_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal FIR_delays_write_assign_fu_259_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component FIR_HLS_mul_32s_12s_43_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        dout : OUT STD_LOGIC_VECTOR (42 downto 0) );
    end component;


    component FIR_HLS_mul_32s_12s_44_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        dout : OUT STD_LOGIC_VECTOR (43 downto 0) );
    end component;



begin
    mul_32s_12s_43_1_1_U20 : component FIR_HLS_mul_32s_12s_43_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 12,
        dout_WIDTH => 43)
    port map (
        din0 => sext_ln45_2_fu_238_p0,
        din1 => mul_ln45_fu_140_p1,
        dout => mul_ln45_fu_140_p2);

    mul_32s_12s_44_1_1_U21 : component FIR_HLS_mul_32s_12s_44_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 12,
        dout_WIDTH => 44)
    port map (
        din0 => FIR_delays_read_4_reg_667,
        din1 => mul_ln45_1_fu_145_p1,
        dout => mul_ln45_1_fu_145_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                FIR_delays_read_1_reg_642 <= FIR_delays_read_17;
                FIR_delays_read_2_reg_647 <= FIR_delays_read_16;
                FIR_delays_read_3_reg_657 <= FIR_delays_read_15;
                FIR_delays_read_4_reg_667 <= FIR_delays_read_14;
                FIR_delays_read_9_reg_673 <= FIR_delays_read;
                tmp_8_reg_681 <= add_ln45_fu_243_p2(42 downto 15);
                x_n_read_reg_637 <= x_n;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    FIR_accu32_fu_216_p4 <= add_ln45_5_fu_210_p2(40 downto 15);
    FIR_delays_write_assign_fu_259_p3 <= (x_n_read_reg_637 & ap_const_lv16_0);
    add_ln45_10_fu_440_p2 <= std_logic_vector(unsigned(sub_ln45_3_fu_423_p2) + unsigned(sext_ln45_20_fu_436_p1));
    add_ln45_11_fu_457_p2 <= std_logic_vector(unsigned(add_ln45_10_fu_440_p2) + unsigned(sext_ln45_21_fu_453_p1));
    add_ln45_12_fu_579_p2 <= std_logic_vector(unsigned(sub_ln45_5_fu_562_p2) + unsigned(sext_ln45_25_fu_575_p1));
    add_ln45_1_fu_360_p2 <= std_logic_vector(signed(sext_ln45_10_fu_273_p1) + signed(sext_ln45_5_fu_356_p1));
    add_ln45_2_fu_467_p2 <= std_logic_vector(unsigned(and_ln45_1_fu_376_p3) + unsigned(sext_ln45_7_fu_463_p1));
    add_ln45_3_fu_499_p2 <= std_logic_vector(unsigned(and_ln45_2_fu_483_p3) + unsigned(sext_ln45_9_fu_495_p1));
    add_ln45_4_fu_589_p2 <= std_logic_vector(unsigned(and_ln45_3_fu_515_p3) + unsigned(sext_ln45_11_fu_585_p1));
    add_ln45_5_fu_210_p2 <= std_logic_vector(unsigned(sub_ln45_1_fu_192_p2) + unsigned(sext_ln45_4_fu_206_p1));
    add_ln45_6_fu_299_p2 <= std_logic_vector(signed(sext_ln45_12_fu_284_p1) + signed(sext_ln45_13_fu_295_p1));
    add_ln45_7_fu_333_p2 <= std_logic_vector(unsigned(sub_ln45_2_fu_316_p2) + unsigned(sext_ln45_15_fu_329_p1));
    add_ln45_8_fu_350_p2 <= std_logic_vector(unsigned(add_ln45_7_fu_333_p2) + unsigned(sext_ln45_16_fu_346_p1));
    add_ln45_9_fu_406_p2 <= std_logic_vector(signed(sext_ln45_17_fu_391_p1) + signed(sext_ln45_18_fu_402_p1));
    add_ln45_fu_243_p2 <= std_logic_vector(signed(sext_ln45_6_fu_234_p1) + signed(mul_ln45_fu_140_p2));
    and_ln45_1_fu_376_p3 <= (tmp_5_fu_366_p4 & ap_const_lv15_0);
    and_ln45_2_fu_483_p3 <= (tmp_6_fu_473_p4 & ap_const_lv15_0);
    and_ln45_3_fu_515_p3 <= (tmp_7_fu_505_p4 & ap_const_lv15_0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= add_ln45_4_fu_589_p2(46 downto 31);
    ap_return_1 <= FIR_delays_read_4_reg_667;
    ap_return_2 <= FIR_delays_read_3_reg_657;
    ap_return_3 <= FIR_delays_read_2_reg_647;
    ap_return_4 <= FIR_delays_read_1_reg_642;
    ap_return_5 <= FIR_delays_write_assign_fu_259_p3;
    mul_ln45_1_fu_145_p1 <= ap_const_lv44_FFFFFFFFBFD(12 - 1 downto 0);
    mul_ln45_fu_140_p1 <= ap_const_lv43_7FFFFFFFBFD(12 - 1 downto 0);
        sext_ln45_10_fu_273_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_9_fu_266_p3),47));

        sext_ln45_11_fu_585_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln45_12_fu_579_p2),47));

        sext_ln45_12_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_10_fu_277_p3),46));

        sext_ln45_13_fu_295_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_11_fu_288_p3),46));

        sext_ln45_14_fu_312_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_12_fu_305_p3),46));

        sext_ln45_15_fu_329_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_13_fu_322_p3),46));

        sext_ln45_16_fu_346_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_14_fu_339_p3),46));

        sext_ln45_17_fu_391_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_15_fu_384_p3),46));

        sext_ln45_18_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_16_fu_395_p3),46));

        sext_ln45_19_fu_419_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_17_fu_412_p3),46));

        sext_ln45_1_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_162_p3),41));

        sext_ln45_20_fu_436_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_18_fu_429_p3),46));

        sext_ln45_21_fu_453_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_19_fu_446_p3),46));

        sext_ln45_22_fu_530_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_20_fu_523_p3),41));

        sext_ln45_23_fu_541_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_21_fu_534_p3),41));

        sext_ln45_24_fu_558_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_22_fu_551_p3),41));

        sext_ln45_25_fu_575_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_23_fu_568_p3),41));

    sext_ln45_2_fu_238_p0 <= FIR_delays_read_17;
        sext_ln45_3_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_180_p3),41));

        sext_ln45_4_fu_206_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_4_fu_198_p3),41));

        sext_ln45_5_fu_356_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln45_8_fu_350_p2),47));

        sext_ln45_6_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_226_p3),43));

        sext_ln45_7_fu_463_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln45_11_fu_457_p2),47));

        sext_ln45_9_fu_495_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln45_1_fu_145_p2),47));

        sext_ln45_fu_158_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_150_p3),41));

    sub_ln45_1_fu_192_p2 <= std_logic_vector(unsigned(sub_ln45_fu_174_p2) - unsigned(sext_ln45_3_fu_188_p1));
    sub_ln45_2_fu_316_p2 <= std_logic_vector(unsigned(add_ln45_6_fu_299_p2) - unsigned(sext_ln45_14_fu_312_p1));
    sub_ln45_3_fu_423_p2 <= std_logic_vector(unsigned(add_ln45_9_fu_406_p2) - unsigned(sext_ln45_19_fu_419_p1));
    sub_ln45_4_fu_545_p2 <= std_logic_vector(signed(sext_ln45_22_fu_530_p1) - signed(sext_ln45_23_fu_541_p1));
    sub_ln45_5_fu_562_p2 <= std_logic_vector(unsigned(sub_ln45_4_fu_545_p2) - unsigned(sext_ln45_24_fu_558_p1));
    sub_ln45_fu_174_p2 <= std_logic_vector(signed(sext_ln45_fu_158_p1) - signed(sext_ln45_1_fu_170_p1));
    tmp_10_fu_277_p3 <= (FIR_delays_read_2_reg_647 & ap_const_lv12_0);
    tmp_11_fu_288_p3 <= (FIR_delays_read_2_reg_647 & ap_const_lv10_0);
    tmp_12_fu_305_p3 <= (FIR_delays_read_2_reg_647 & ap_const_lv8_0);
    tmp_13_fu_322_p3 <= (FIR_delays_read_2_reg_647 & ap_const_lv6_0);
    tmp_14_fu_339_p3 <= (FIR_delays_read_2_reg_647 & ap_const_lv1_0);
    tmp_15_fu_384_p3 <= (FIR_delays_read_3_reg_657 & ap_const_lv12_0);
    tmp_16_fu_395_p3 <= (FIR_delays_read_3_reg_657 & ap_const_lv10_0);
    tmp_17_fu_412_p3 <= (FIR_delays_read_3_reg_657 & ap_const_lv8_0);
    tmp_18_fu_429_p3 <= (FIR_delays_read_3_reg_657 & ap_const_lv6_0);
    tmp_19_fu_446_p3 <= (FIR_delays_read_3_reg_657 & ap_const_lv1_0);
    tmp_1_fu_150_p3 <= (x_n & ap_const_lv24_0);
    tmp_20_fu_523_p3 <= (FIR_delays_read_9_reg_673 & ap_const_lv8_0);
    tmp_21_fu_534_p3 <= (FIR_delays_read_9_reg_673 & ap_const_lv5_0);
    tmp_22_fu_551_p3 <= (FIR_delays_read_9_reg_673 & ap_const_lv3_0);
    tmp_23_fu_568_p3 <= (FIR_delays_read_9_reg_673 & ap_const_lv1_0);
    tmp_2_fu_162_p3 <= (x_n & ap_const_lv21_0);
    tmp_3_fu_180_p3 <= (x_n & ap_const_lv19_0);
    tmp_4_fu_198_p3 <= (x_n & ap_const_lv17_0);
    tmp_5_fu_366_p4 <= add_ln45_1_fu_360_p2(46 downto 15);
    tmp_6_fu_473_p4 <= add_ln45_2_fu_467_p2(46 downto 15);
    tmp_7_fu_505_p4 <= add_ln45_3_fu_499_p2(46 downto 15);
    tmp_9_fu_266_p3 <= (tmp_8_reg_681 & ap_const_lv15_0);
    tmp_fu_226_p3 <= (FIR_accu32_fu_216_p4 & ap_const_lv15_0);
end behav;
