-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FIR_HLS is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    input_r_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    input_r_TVALID : IN STD_LOGIC;
    input_r_TREADY : OUT STD_LOGIC;
    output_r_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_r_TVALID : OUT STD_LOGIC;
    output_r_TREADY : IN STD_LOGIC );
end;


architecture behav of FIR_HLS is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "FIR_HLS_FIR_HLS,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.870000,HLS_SYN_LAT=51,HLS_SYN_TPT=none,HLS_SYN_MEM=3,HLS_SYN_DSP=0,HLS_SYN_FF=1034,HLS_SYN_LUT=1561,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (18 downto 0) := "0000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (18 downto 0) := "0000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (18 downto 0) := "0000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (18 downto 0) := "0000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (18 downto 0) := "0000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (18 downto 0) := "0000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (18 downto 0) := "0001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (18 downto 0) := "0010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (18 downto 0) := "0100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (18 downto 0) := "1000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv25_1B4 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000110110100";

    signal ap_rst_n_inv : STD_LOGIC;
    signal mod_value : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal y2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal b_FIR_dec_int_40_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal b_FIR_dec_int_40_ce0 : STD_LOGIC;
    signal b_FIR_dec_int_40_q0 : STD_LOGIC_VECTOR (13 downto 0);
    signal H_filter_FIR_dec_40_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal H_filter_FIR_dec_40_ce0 : STD_LOGIC;
    signal H_filter_FIR_dec_40_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_dec_40_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal y1_phase1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal y1_phase2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal y1_phase3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal H_filter_FIR_kernel_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal H_filter_FIR_kernel_ce0 : STD_LOGIC;
    signal H_filter_FIR_kernel_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_kernel_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_int_40_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal H_filter_FIR_int_40_ce0 : STD_LOGIC;
    signal H_filter_FIR_int_40_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_int_40_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_dec_43_ce0 : STD_LOGIC;
    signal H_filter_FIR_dec_43_we0 : STD_LOGIC;
    signal H_filter_FIR_dec_43_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_dec_43_ce1 : STD_LOGIC;
    signal H_filter_FIR_dec_43_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_FIR_dec_int_43_ce0 : STD_LOGIC;
    signal b_FIR_dec_int_43_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal H_filter_FIR_int_41_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal H_filter_FIR_int_41_ce0 : STD_LOGIC;
    signal H_filter_FIR_int_41_we0 : STD_LOGIC;
    signal H_filter_FIR_int_41_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_int_41_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_int_41_ce1 : STD_LOGIC;
    signal H_filter_FIR_int_41_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_FIR_dec_int_41_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal b_FIR_dec_int_41_ce0 : STD_LOGIC;
    signal b_FIR_dec_int_41_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal H_filter_FIR_dec_42_ce0 : STD_LOGIC;
    signal H_filter_FIR_dec_42_we0 : STD_LOGIC;
    signal H_filter_FIR_dec_42_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_dec_42_ce1 : STD_LOGIC;
    signal H_filter_FIR_dec_42_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_FIR_dec_int_42_ce0 : STD_LOGIC;
    signal b_FIR_dec_int_42_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal H_filter_FIR_int_42_ce0 : STD_LOGIC;
    signal H_filter_FIR_int_42_we0 : STD_LOGIC;
    signal H_filter_FIR_int_42_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_int_42_ce1 : STD_LOGIC;
    signal H_filter_FIR_int_42_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_dec_41_ce0 : STD_LOGIC;
    signal H_filter_FIR_dec_41_we0 : STD_LOGIC;
    signal H_filter_FIR_dec_41_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_dec_41_ce1 : STD_LOGIC;
    signal H_filter_FIR_dec_41_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_int_43_ce0 : STD_LOGIC;
    signal H_filter_FIR_int_43_we0 : STD_LOGIC;
    signal H_filter_FIR_int_43_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_int_43_ce1 : STD_LOGIC;
    signal H_filter_FIR_int_43_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal output_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal x_n_1_reg_447 : STD_LOGIC_VECTOR (15 downto 0);
    signal mod_value_load_load_fu_233_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal mod_value_load_reg_453 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln39_fu_251_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal trunc_ln45_fu_290_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal H_filter_FIR_kernel_load_reg_483 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_n_fu_333_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_n_reg_488 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal y_3_fu_375_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_3_reg_493 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln81_fu_395_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal trunc_ln81_reg_503 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal grp_FIR_filtertest_2_fu_176_ap_start : STD_LOGIC;
    signal grp_FIR_filtertest_2_fu_176_ap_done : STD_LOGIC;
    signal grp_FIR_filtertest_2_fu_176_ap_idle : STD_LOGIC;
    signal grp_FIR_filtertest_2_fu_176_ap_ready : STD_LOGIC;
    signal grp_FIR_filtertest_2_fu_176_FIR_delays_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_filtertest_2_fu_176_FIR_delays_ce0 : STD_LOGIC;
    signal grp_FIR_filtertest_2_fu_176_FIR_delays_we0 : STD_LOGIC;
    signal grp_FIR_filtertest_2_fu_176_FIR_delays_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FIR_filtertest_2_fu_176_FIR_delays_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FIR_filtertest_2_fu_176_FIR_delays_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_filtertest_2_fu_176_FIR_delays_ce1 : STD_LOGIC;
    signal grp_FIR_filtertest_2_fu_176_FIR_delays_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FIR_filtertest_2_fu_176_FIR_coe_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_filtertest_2_fu_176_FIR_coe_ce0 : STD_LOGIC;
    signal grp_FIR_filtertest_2_fu_176_FIR_coe_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_FIR_filtertest_2_fu_176_x_n : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filtertest_2_fu_176_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_done : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_idle : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_ready : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_y_3_out : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_y_3_out_ap_vld : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_H_filter_FIR_int_41_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_H_filter_FIR_int_41_ce0 : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_b_FIR_dec_int_41_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_b_FIR_dec_int_41_ce0 : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_done : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_idle : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_ready : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_ce0 : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_we0 : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_ce1 : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_done : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_idle : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_ready : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_b_FIR_dec_int_40_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_b_FIR_dec_int_40_ce0 : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_ce0 : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_we0 : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_ce1 : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_done : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_idle : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_ready : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_ce0 : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_we0 : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_ce1 : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_done : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_idle : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_ready : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_b_FIR_dec_int_40_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_b_FIR_dec_int_40_ce0 : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_ce0 : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_we0 : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_ce1 : STD_LOGIC;
    signal ap_phi_mux_data_out_load_phi_fu_166_p8 : STD_LOGIC_VECTOR (13 downto 0);
    signal data_out_load_reg_163 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_block_state18_on_subcall_done : BOOLEAN;
    signal grp_FIR_filtertest_2_fu_176_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start_reg : STD_LOGIC := '0';
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal H_filter_FIR_int_41_we0_out : STD_LOGIC;
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start_reg : STD_LOGIC := '0';
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start_reg : STD_LOGIC := '0';
    signal grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal ap_block_state7_on_subcall_done : BOOLEAN;
    signal H_filter_FIR_int_41_we0_local : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal shl_ln_fu_261_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_int_41_ce0_local : STD_LOGIC;
    signal H_filter_FIR_dec_40_ce0_local : STD_LOGIC;
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal H_filter_FIR_kernel_ce0_local : STD_LOGIC;
    signal H_filter_FIR_int_40_ce0_local : STD_LOGIC;
    signal sext_ln81_fu_241_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_424_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_1_fu_300_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln24_1_fu_327_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln24_fu_321_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_348_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_shl_fu_340_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln81_3_fu_356_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sub_ln81_fu_360_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln81_4_fu_366_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln81_fu_370_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_433_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_424_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_433_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_424_ce : STD_LOGIC;
    signal grp_fu_433_ce : STD_LOGIC;
    signal ap_block_state16_on_subcall_done : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal regslice_both_output_r_U_apdone_blk : STD_LOGIC;
    signal ap_block_state19 : BOOLEAN;
    signal regslice_both_input_r_U_apdone_blk : STD_LOGIC;
    signal input_r_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal input_r_TVALID_int_regslice : STD_LOGIC;
    signal input_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_input_r_U_ack_in : STD_LOGIC;
    signal output_r_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal output_r_TVALID_int_regslice : STD_LOGIC;
    signal output_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_output_r_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component FIR_HLS_FIR_filtertest_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        FIR_delays_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        FIR_delays_ce0 : OUT STD_LOGIC;
        FIR_delays_we0 : OUT STD_LOGIC;
        FIR_delays_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        FIR_delays_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        FIR_delays_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        FIR_delays_ce1 : OUT STD_LOGIC;
        FIR_delays_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        FIR_coe_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        FIR_coe_ce0 : OUT STD_LOGIC;
        FIR_coe_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        x_n : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_65_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        y_3_out : OUT STD_LOGIC_VECTOR (13 downto 0);
        y_3_out_ap_vld : OUT STD_LOGIC;
        H_filter_FIR_int_41_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        H_filter_FIR_int_41_ce0 : OUT STD_LOGIC;
        H_filter_FIR_int_41_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        b_FIR_dec_int_41_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        b_FIR_dec_int_41_ce0 : OUT STD_LOGIC;
        b_FIR_dec_int_41_q0 : IN STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_69_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        H_filter_FIR_int_41_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        H_filter_FIR_int_41_ce0 : OUT STD_LOGIC;
        H_filter_FIR_int_41_we0 : OUT STD_LOGIC;
        H_filter_FIR_int_41_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        H_filter_FIR_int_41_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        H_filter_FIR_int_41_ce1 : OUT STD_LOGIC;
        H_filter_FIR_int_41_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_83_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sext_ln83 : IN STD_LOGIC_VECTOR (15 downto 0);
        b_FIR_dec_int_40_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        b_FIR_dec_int_40_ce0 : OUT STD_LOGIC;
        b_FIR_dec_int_40_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
        H_filter_FIR_dec_40_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        H_filter_FIR_dec_40_ce0 : OUT STD_LOGIC;
        H_filter_FIR_dec_40_we0 : OUT STD_LOGIC;
        H_filter_FIR_dec_40_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        H_filter_FIR_dec_40_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        H_filter_FIR_dec_40_ce1 : OUT STD_LOGIC;
        H_filter_FIR_dec_40_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_83_11 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sext_ln84 : IN STD_LOGIC_VECTOR (15 downto 0);
        H_filter_FIR_kernel_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        H_filter_FIR_kernel_ce0 : OUT STD_LOGIC;
        H_filter_FIR_kernel_we0 : OUT STD_LOGIC;
        H_filter_FIR_kernel_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        H_filter_FIR_kernel_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        H_filter_FIR_kernel_ce1 : OUT STD_LOGIC;
        H_filter_FIR_kernel_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_83_12 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sext_ln83_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        b_FIR_dec_int_40_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        b_FIR_dec_int_40_ce0 : OUT STD_LOGIC;
        b_FIR_dec_int_40_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
        H_filter_FIR_int_40_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        H_filter_FIR_int_40_ce0 : OUT STD_LOGIC;
        H_filter_FIR_int_40_we0 : OUT STD_LOGIC;
        H_filter_FIR_int_40_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        H_filter_FIR_int_40_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        H_filter_FIR_int_40_ce1 : OUT STD_LOGIC;
        H_filter_FIR_int_40_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_HLS_mac_muladd_16s_9ns_32s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_HLS_mac_muladd_16s_9ns_30s_30_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        din2 : IN STD_LOGIC_VECTOR (29 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component FIR_HLS_b_FIR_dec_int_40_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (13 downto 0) );
    end component;


    component FIR_HLS_H_filter_FIR_dec_40_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_HLS_H_filter_FIR_kernel_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_HLS_H_filter_FIR_dec_43_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_HLS_b_FIR_dec_int_43_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component FIR_HLS_b_FIR_dec_int_41_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component FIR_HLS_b_FIR_dec_int_42_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component FIR_HLS_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    b_FIR_dec_int_40_U : component FIR_HLS_b_FIR_dec_int_40_ROM_AUTO_1R
    generic map (
        DataWidth => 14,
        AddressRange => 6,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => b_FIR_dec_int_40_address0,
        ce0 => b_FIR_dec_int_40_ce0,
        q0 => b_FIR_dec_int_40_q0);

    H_filter_FIR_dec_40_U : component FIR_HLS_H_filter_FIR_dec_40_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 6,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => H_filter_FIR_dec_40_address0,
        ce0 => H_filter_FIR_dec_40_ce0,
        we0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_we0,
        d0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_d0,
        q0 => H_filter_FIR_dec_40_q0,
        address1 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_address1,
        ce1 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_ce1,
        q1 => H_filter_FIR_dec_40_q1);

    H_filter_FIR_kernel_U : component FIR_HLS_H_filter_FIR_kernel_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 117,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => H_filter_FIR_kernel_address0,
        ce0 => H_filter_FIR_kernel_ce0,
        we0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_we0,
        d0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_d0,
        q0 => H_filter_FIR_kernel_q0,
        address1 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_address1,
        ce1 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_ce1,
        q1 => H_filter_FIR_kernel_q1);

    H_filter_FIR_int_40_U : component FIR_HLS_H_filter_FIR_dec_40_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 6,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => H_filter_FIR_int_40_address0,
        ce0 => H_filter_FIR_int_40_ce0,
        we0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_we0,
        d0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_d0,
        q0 => H_filter_FIR_int_40_q0,
        address1 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_address1,
        ce1 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_ce1,
        q1 => H_filter_FIR_int_40_q1);

    H_filter_FIR_dec_43_U : component FIR_HLS_H_filter_FIR_dec_43_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => grp_FIR_filtertest_2_fu_176_FIR_delays_address0,
        ce0 => H_filter_FIR_dec_43_ce0,
        we0 => H_filter_FIR_dec_43_we0,
        d0 => grp_FIR_filtertest_2_fu_176_FIR_delays_d0,
        q0 => H_filter_FIR_dec_43_q0,
        address1 => grp_FIR_filtertest_2_fu_176_FIR_delays_address1,
        ce1 => H_filter_FIR_dec_43_ce1,
        q1 => H_filter_FIR_dec_43_q1);

    b_FIR_dec_int_43_U : component FIR_HLS_b_FIR_dec_int_43_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => grp_FIR_filtertest_2_fu_176_FIR_coe_address0,
        ce0 => b_FIR_dec_int_43_ce0,
        q0 => b_FIR_dec_int_43_q0);

    H_filter_FIR_int_41_U : component FIR_HLS_H_filter_FIR_dec_43_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => H_filter_FIR_int_41_address0,
        ce0 => H_filter_FIR_int_41_ce0,
        we0 => H_filter_FIR_int_41_we0,
        d0 => H_filter_FIR_int_41_d0,
        q0 => H_filter_FIR_int_41_q0,
        address1 => grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_address1,
        ce1 => H_filter_FIR_int_41_ce1,
        q1 => H_filter_FIR_int_41_q1);

    b_FIR_dec_int_41_U : component FIR_HLS_b_FIR_dec_int_41_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => b_FIR_dec_int_41_address0,
        ce0 => b_FIR_dec_int_41_ce0,
        q0 => b_FIR_dec_int_41_q0);

    H_filter_FIR_dec_42_U : component FIR_HLS_H_filter_FIR_dec_43_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => grp_FIR_filtertest_2_fu_176_FIR_delays_address0,
        ce0 => H_filter_FIR_dec_42_ce0,
        we0 => H_filter_FIR_dec_42_we0,
        d0 => grp_FIR_filtertest_2_fu_176_FIR_delays_d0,
        q0 => H_filter_FIR_dec_42_q0,
        address1 => grp_FIR_filtertest_2_fu_176_FIR_delays_address1,
        ce1 => H_filter_FIR_dec_42_ce1,
        q1 => H_filter_FIR_dec_42_q1);

    b_FIR_dec_int_42_U : component FIR_HLS_b_FIR_dec_int_42_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => grp_FIR_filtertest_2_fu_176_FIR_coe_address0,
        ce0 => b_FIR_dec_int_42_ce0,
        q0 => b_FIR_dec_int_42_q0);

    H_filter_FIR_int_42_U : component FIR_HLS_H_filter_FIR_dec_43_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => grp_FIR_filtertest_2_fu_176_FIR_delays_address0,
        ce0 => H_filter_FIR_int_42_ce0,
        we0 => H_filter_FIR_int_42_we0,
        d0 => grp_FIR_filtertest_2_fu_176_FIR_delays_d0,
        q0 => H_filter_FIR_int_42_q0,
        address1 => grp_FIR_filtertest_2_fu_176_FIR_delays_address1,
        ce1 => H_filter_FIR_int_42_ce1,
        q1 => H_filter_FIR_int_42_q1);

    H_filter_FIR_dec_41_U : component FIR_HLS_H_filter_FIR_dec_43_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => grp_FIR_filtertest_2_fu_176_FIR_delays_address0,
        ce0 => H_filter_FIR_dec_41_ce0,
        we0 => H_filter_FIR_dec_41_we0,
        d0 => grp_FIR_filtertest_2_fu_176_FIR_delays_d0,
        q0 => H_filter_FIR_dec_41_q0,
        address1 => grp_FIR_filtertest_2_fu_176_FIR_delays_address1,
        ce1 => H_filter_FIR_dec_41_ce1,
        q1 => H_filter_FIR_dec_41_q1);

    H_filter_FIR_int_43_U : component FIR_HLS_H_filter_FIR_dec_43_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => grp_FIR_filtertest_2_fu_176_FIR_delays_address0,
        ce0 => H_filter_FIR_int_43_ce0,
        we0 => H_filter_FIR_int_43_we0,
        d0 => grp_FIR_filtertest_2_fu_176_FIR_delays_d0,
        q0 => H_filter_FIR_int_43_q0,
        address1 => grp_FIR_filtertest_2_fu_176_FIR_delays_address1,
        ce1 => H_filter_FIR_int_43_ce1,
        q1 => H_filter_FIR_int_43_q1);

    grp_FIR_filtertest_2_fu_176 : component FIR_HLS_FIR_filtertest_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_FIR_filtertest_2_fu_176_ap_start,
        ap_done => grp_FIR_filtertest_2_fu_176_ap_done,
        ap_idle => grp_FIR_filtertest_2_fu_176_ap_idle,
        ap_ready => grp_FIR_filtertest_2_fu_176_ap_ready,
        FIR_delays_address0 => grp_FIR_filtertest_2_fu_176_FIR_delays_address0,
        FIR_delays_ce0 => grp_FIR_filtertest_2_fu_176_FIR_delays_ce0,
        FIR_delays_we0 => grp_FIR_filtertest_2_fu_176_FIR_delays_we0,
        FIR_delays_d0 => grp_FIR_filtertest_2_fu_176_FIR_delays_d0,
        FIR_delays_q0 => grp_FIR_filtertest_2_fu_176_FIR_delays_q0,
        FIR_delays_address1 => grp_FIR_filtertest_2_fu_176_FIR_delays_address1,
        FIR_delays_ce1 => grp_FIR_filtertest_2_fu_176_FIR_delays_ce1,
        FIR_delays_q1 => grp_FIR_filtertest_2_fu_176_FIR_delays_q1,
        FIR_coe_address0 => grp_FIR_filtertest_2_fu_176_FIR_coe_address0,
        FIR_coe_ce0 => grp_FIR_filtertest_2_fu_176_FIR_coe_ce0,
        FIR_coe_q0 => grp_FIR_filtertest_2_fu_176_FIR_coe_q0,
        x_n => grp_FIR_filtertest_2_fu_176_x_n,
        ap_return => grp_FIR_filtertest_2_fu_176_ap_return);

    grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191 : component FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_65_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start,
        ap_done => grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_done,
        ap_idle => grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_idle,
        ap_ready => grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_ready,
        y_3_out => grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_y_3_out,
        y_3_out_ap_vld => grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_y_3_out_ap_vld,
        H_filter_FIR_int_41_address0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_H_filter_FIR_int_41_address0,
        H_filter_FIR_int_41_ce0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_H_filter_FIR_int_41_ce0,
        H_filter_FIR_int_41_q0 => H_filter_FIR_int_41_q0,
        b_FIR_dec_int_41_address0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_b_FIR_dec_int_41_address0,
        b_FIR_dec_int_41_ce0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_b_FIR_dec_int_41_ce0,
        b_FIR_dec_int_41_q0 => b_FIR_dec_int_41_q0);

    grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200 : component FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_69_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start,
        ap_done => grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_done,
        ap_idle => grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_idle,
        ap_ready => grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_ready,
        H_filter_FIR_int_41_address0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_address0,
        H_filter_FIR_int_41_ce0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_ce0,
        H_filter_FIR_int_41_we0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_we0,
        H_filter_FIR_int_41_d0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_d0,
        H_filter_FIR_int_41_address1 => grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_address1,
        H_filter_FIR_int_41_ce1 => grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_ce1,
        H_filter_FIR_int_41_q1 => H_filter_FIR_int_41_q1);

    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206 : component FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_83_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start,
        ap_done => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_done,
        ap_idle => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_idle,
        ap_ready => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_ready,
        sext_ln83 => x_n_1_reg_447,
        b_FIR_dec_int_40_address0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_b_FIR_dec_int_40_address0,
        b_FIR_dec_int_40_ce0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_b_FIR_dec_int_40_ce0,
        b_FIR_dec_int_40_q0 => b_FIR_dec_int_40_q0,
        H_filter_FIR_dec_40_address0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_address0,
        H_filter_FIR_dec_40_ce0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_ce0,
        H_filter_FIR_dec_40_we0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_we0,
        H_filter_FIR_dec_40_d0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_d0,
        H_filter_FIR_dec_40_address1 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_address1,
        H_filter_FIR_dec_40_ce1 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_ce1,
        H_filter_FIR_dec_40_q1 => H_filter_FIR_dec_40_q1);

    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215 : component FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_83_11
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start,
        ap_done => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_done,
        ap_idle => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_idle,
        ap_ready => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_ready,
        sext_ln84 => x_n_reg_488,
        H_filter_FIR_kernel_address0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_address0,
        H_filter_FIR_kernel_ce0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_ce0,
        H_filter_FIR_kernel_we0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_we0,
        H_filter_FIR_kernel_d0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_d0,
        H_filter_FIR_kernel_address1 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_address1,
        H_filter_FIR_kernel_ce1 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_ce1,
        H_filter_FIR_kernel_q1 => H_filter_FIR_kernel_q1);

    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224 : component FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_83_12
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start,
        ap_done => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_done,
        ap_idle => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_idle,
        ap_ready => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_ready,
        sext_ln83_1 => y_3_reg_493,
        b_FIR_dec_int_40_address0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_b_FIR_dec_int_40_address0,
        b_FIR_dec_int_40_ce0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_b_FIR_dec_int_40_ce0,
        b_FIR_dec_int_40_q0 => b_FIR_dec_int_40_q0,
        H_filter_FIR_int_40_address0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_address0,
        H_filter_FIR_int_40_ce0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_ce0,
        H_filter_FIR_int_40_we0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_we0,
        H_filter_FIR_int_40_d0 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_d0,
        H_filter_FIR_int_40_address1 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_address1,
        H_filter_FIR_int_40_ce1 => grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_ce1,
        H_filter_FIR_int_40_q1 => H_filter_FIR_int_40_q1);

    mac_muladd_16s_9ns_32s_32_4_1_U31 : component FIR_HLS_mac_muladd_16s_9ns_32s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln81_fu_241_p0,
        din1 => grp_fu_424_p1,
        din2 => H_filter_FIR_dec_40_q0,
        ce => grp_fu_424_ce,
        dout => grp_fu_424_p3);

    mac_muladd_16s_9ns_30s_30_4_1_U32 : component FIR_HLS_mac_muladd_16s_9ns_30s_30_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        din2_WIDTH => 30,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => y_3_fu_375_p4,
        din1 => grp_fu_433_p1,
        din2 => trunc_ln81_reg_503,
        ce => grp_fu_433_ce,
        dout => grp_fu_433_p3);

    regslice_both_input_r_U : component FIR_HLS_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TDATA,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_U_ack_in,
        data_out => input_r_TDATA_int_regslice,
        vld_out => input_r_TVALID_int_regslice,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_U_apdone_blk);

    regslice_both_output_r_U : component FIR_HLS_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => output_r_TDATA_int_regslice,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => output_r_TREADY_int_regslice,
        data_out => output_r_TDATA,
        vld_out => regslice_both_output_r_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_ready = ap_const_logic_1)) then 
                    grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_ready = ap_const_logic_1)) then 
                    grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_ready = ap_const_logic_1)) then 
                    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
                    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_ready = ap_const_logic_1)) then 
                    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_ready = ap_const_logic_1)) then 
                    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_FIR_filtertest_2_fu_176_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_FIR_filtertest_2_fu_176_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
                    grp_FIR_filtertest_2_fu_176_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FIR_filtertest_2_fu_176_ap_ready = ap_const_logic_1)) then 
                    grp_FIR_filtertest_2_fu_176_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    data_out_load_reg_163_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((output_r_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state18_on_subcall_done))) and (mod_value_load_reg_453 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
                data_out_load_reg_163 <= grp_fu_433_p3(29 downto 16);
            elsif (((grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                data_out_load_reg_163 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_y_3_out;
            elsif (((grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                data_out_load_reg_163 <= trunc_ln39_fu_251_p1;
            elsif (((grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
                data_out_load_reg_163 <= trunc_ln45_fu_290_p1;
            end if; 
        end if;
    end process;

    mod_value_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                mod_value <= ap_const_lv2_3;
            elsif (((grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                mod_value <= ap_const_lv2_2;
            elsif (((grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
                mod_value <= ap_const_lv2_0;
            elsif ((not(((output_r_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state18_on_subcall_done))) and (mod_value_load_reg_453 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
                mod_value <= ap_const_lv2_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                H_filter_FIR_kernel_load_reg_483 <= H_filter_FIR_kernel_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                mod_value_load_reg_453 <= mod_value;
                x_n_1_reg_447 <= input_r_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                trunc_ln81_reg_503 <= trunc_ln81_fu_395_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                x_n_reg_488 <= x_n_fu_333_p2;
                y2 <= add_ln81_fu_370_p2(31 downto 16);
                y_3_reg_493 <= add_ln81_fu_370_p2(31 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state7_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                y1_phase1 <= grp_FIR_filtertest_2_fu_176_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                y1_phase2 <= grp_FIR_filtertest_2_fu_176_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                y1_phase3 <= grp_FIR_filtertest_2_fu_176_ap_return;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state18, ap_CS_fsm_state19, mod_value_load_load_fu_233_p1, ap_CS_fsm_state4, ap_CS_fsm_state12, ap_CS_fsm_state16, grp_FIR_filtertest_2_fu_176_ap_done, grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_done, ap_CS_fsm_state9, ap_block_state18_on_subcall_done, ap_CS_fsm_state3, ap_CS_fsm_state11, ap_CS_fsm_state7, ap_block_state7_on_subcall_done, ap_block_state16_on_subcall_done, ap_block_state19, input_r_TVALID_int_regslice, output_r_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (mod_value_load_load_fu_233_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                elsif (((input_r_TVALID_int_regslice = ap_const_logic_1) and (mod_value_load_load_fu_233_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                elsif (((input_r_TVALID_int_regslice = ap_const_logic_1) and (mod_value_load_load_fu_233_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                elsif (((input_r_TVALID_int_regslice = ap_const_logic_1) and (mod_value_load_load_fu_233_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state18;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_boolean_0 = ap_block_state7_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state18;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                if (((grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state18;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                if (((ap_const_boolean_0 = ap_block_state16_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state16))) then
                    ap_NS_fsm <= ap_ST_fsm_state17;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                if ((not(((output_r_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state18_on_subcall_done))) and (ap_const_logic_1 = ap_CS_fsm_state18))) then
                    ap_NS_fsm <= ap_ST_fsm_state19;
                else
                    ap_NS_fsm <= ap_ST_fsm_state18;
                end if;
            when ap_ST_fsm_state19 => 
                if (((ap_const_boolean_0 = ap_block_state19) and (ap_const_logic_1 = ap_CS_fsm_state19))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state19;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXX";
        end case;
    end process;

    H_filter_FIR_dec_40_address0_assign_proc : process(ap_CS_fsm_state16, grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_address0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            H_filter_FIR_dec_40_address0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_address0;
        else 
            H_filter_FIR_dec_40_address0 <= ap_const_lv3_0;
        end if; 
    end process;


    H_filter_FIR_dec_40_ce0_assign_proc : process(ap_CS_fsm_state16, grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_ce0, H_filter_FIR_dec_40_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            H_filter_FIR_dec_40_ce0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_H_filter_FIR_dec_40_ce0;
        else 
            H_filter_FIR_dec_40_ce0 <= H_filter_FIR_dec_40_ce0_local;
        end if; 
    end process;


    H_filter_FIR_dec_40_ce0_local_assign_proc : process(ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            H_filter_FIR_dec_40_ce0_local <= ap_const_logic_1;
        else 
            H_filter_FIR_dec_40_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_dec_41_ce0_assign_proc : process(grp_FIR_filtertest_2_fu_176_FIR_delays_ce0, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            H_filter_FIR_dec_41_ce0 <= grp_FIR_filtertest_2_fu_176_FIR_delays_ce0;
        else 
            H_filter_FIR_dec_41_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_dec_41_ce1_assign_proc : process(grp_FIR_filtertest_2_fu_176_FIR_delays_ce1, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            H_filter_FIR_dec_41_ce1 <= grp_FIR_filtertest_2_fu_176_FIR_delays_ce1;
        else 
            H_filter_FIR_dec_41_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_dec_41_we0_assign_proc : process(grp_FIR_filtertest_2_fu_176_FIR_delays_we0, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            H_filter_FIR_dec_41_we0 <= grp_FIR_filtertest_2_fu_176_FIR_delays_we0;
        else 
            H_filter_FIR_dec_41_we0 <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_dec_42_ce0_assign_proc : process(grp_FIR_filtertest_2_fu_176_FIR_delays_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            H_filter_FIR_dec_42_ce0 <= grp_FIR_filtertest_2_fu_176_FIR_delays_ce0;
        else 
            H_filter_FIR_dec_42_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_dec_42_ce1_assign_proc : process(grp_FIR_filtertest_2_fu_176_FIR_delays_ce1, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            H_filter_FIR_dec_42_ce1 <= grp_FIR_filtertest_2_fu_176_FIR_delays_ce1;
        else 
            H_filter_FIR_dec_42_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_dec_42_we0_assign_proc : process(grp_FIR_filtertest_2_fu_176_FIR_delays_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            H_filter_FIR_dec_42_we0 <= grp_FIR_filtertest_2_fu_176_FIR_delays_we0;
        else 
            H_filter_FIR_dec_42_we0 <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_dec_43_ce0_assign_proc : process(grp_FIR_filtertest_2_fu_176_FIR_delays_ce0, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            H_filter_FIR_dec_43_ce0 <= grp_FIR_filtertest_2_fu_176_FIR_delays_ce0;
        else 
            H_filter_FIR_dec_43_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_dec_43_ce1_assign_proc : process(grp_FIR_filtertest_2_fu_176_FIR_delays_ce1, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            H_filter_FIR_dec_43_ce1 <= grp_FIR_filtertest_2_fu_176_FIR_delays_ce1;
        else 
            H_filter_FIR_dec_43_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_dec_43_we0_assign_proc : process(grp_FIR_filtertest_2_fu_176_FIR_delays_we0, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            H_filter_FIR_dec_43_we0 <= grp_FIR_filtertest_2_fu_176_FIR_delays_we0;
        else 
            H_filter_FIR_dec_43_we0 <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_int_40_address0_assign_proc : process(ap_CS_fsm_state18, mod_value_load_reg_453, grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_address0)
    begin
        if (((mod_value_load_reg_453 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            H_filter_FIR_int_40_address0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_address0;
        else 
            H_filter_FIR_int_40_address0 <= ap_const_lv3_0;
        end if; 
    end process;


    H_filter_FIR_int_40_ce0_assign_proc : process(ap_CS_fsm_state18, mod_value_load_reg_453, grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_ce0, H_filter_FIR_int_40_ce0_local)
    begin
        if (((mod_value_load_reg_453 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            H_filter_FIR_int_40_ce0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_H_filter_FIR_int_40_ce0;
        else 
            H_filter_FIR_int_40_ce0 <= H_filter_FIR_int_40_ce0_local;
        end if; 
    end process;


    H_filter_FIR_int_40_ce0_local_assign_proc : process(ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            H_filter_FIR_int_40_ce0_local <= ap_const_logic_1;
        else 
            H_filter_FIR_int_40_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_int_41_address0_assign_proc : process(grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_H_filter_FIR_int_41_address0, grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_address0, ap_CS_fsm_state9, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            H_filter_FIR_int_41_address0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            H_filter_FIR_int_41_address0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_H_filter_FIR_int_41_address0;
        else 
            H_filter_FIR_int_41_address0 <= ap_const_lv3_4;
        end if; 
    end process;


    H_filter_FIR_int_41_ce0_assign_proc : process(grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_H_filter_FIR_int_41_ce0, grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_ce0, ap_CS_fsm_state9, ap_CS_fsm_state7, H_filter_FIR_int_41_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            H_filter_FIR_int_41_ce0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            H_filter_FIR_int_41_ce0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_H_filter_FIR_int_41_ce0;
        else 
            H_filter_FIR_int_41_ce0 <= H_filter_FIR_int_41_ce0_local;
        end if; 
    end process;


    H_filter_FIR_int_41_ce0_local_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            H_filter_FIR_int_41_ce0_local <= ap_const_logic_1;
        else 
            H_filter_FIR_int_41_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_int_41_ce1_assign_proc : process(grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_ce1, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            H_filter_FIR_int_41_ce1 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_ce1;
        else 
            H_filter_FIR_int_41_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_int_41_d0_assign_proc : process(grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_d0, ap_CS_fsm_state9, shl_ln_fu_261_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            H_filter_FIR_int_41_d0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_d0;
        else 
            H_filter_FIR_int_41_d0 <= shl_ln_fu_261_p3;
        end if; 
    end process;


    H_filter_FIR_int_41_we0_assign_proc : process(grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_we0, ap_CS_fsm_state9, H_filter_FIR_int_41_we0_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            H_filter_FIR_int_41_we0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_H_filter_FIR_int_41_we0;
        else 
            H_filter_FIR_int_41_we0 <= (ap_const_logic_0 or H_filter_FIR_int_41_we0_out);
        end if; 
    end process;


    H_filter_FIR_int_41_we0_local_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            H_filter_FIR_int_41_we0_local <= ap_const_logic_1;
        else 
            H_filter_FIR_int_41_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_filter_FIR_int_41_we0_out <= H_filter_FIR_int_41_we0_local;

    H_filter_FIR_int_42_ce0_assign_proc : process(ap_CS_fsm_state4, grp_FIR_filtertest_2_fu_176_FIR_delays_ce0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            H_filter_FIR_int_42_ce0 <= grp_FIR_filtertest_2_fu_176_FIR_delays_ce0;
        else 
            H_filter_FIR_int_42_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_int_42_ce1_assign_proc : process(ap_CS_fsm_state4, grp_FIR_filtertest_2_fu_176_FIR_delays_ce1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            H_filter_FIR_int_42_ce1 <= grp_FIR_filtertest_2_fu_176_FIR_delays_ce1;
        else 
            H_filter_FIR_int_42_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_int_42_we0_assign_proc : process(ap_CS_fsm_state4, grp_FIR_filtertest_2_fu_176_FIR_delays_we0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            H_filter_FIR_int_42_we0 <= grp_FIR_filtertest_2_fu_176_FIR_delays_we0;
        else 
            H_filter_FIR_int_42_we0 <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_int_43_ce0_assign_proc : process(ap_CS_fsm_state12, grp_FIR_filtertest_2_fu_176_FIR_delays_ce0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            H_filter_FIR_int_43_ce0 <= grp_FIR_filtertest_2_fu_176_FIR_delays_ce0;
        else 
            H_filter_FIR_int_43_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_int_43_ce1_assign_proc : process(ap_CS_fsm_state12, grp_FIR_filtertest_2_fu_176_FIR_delays_ce1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            H_filter_FIR_int_43_ce1 <= grp_FIR_filtertest_2_fu_176_FIR_delays_ce1;
        else 
            H_filter_FIR_int_43_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_int_43_we0_assign_proc : process(ap_CS_fsm_state12, grp_FIR_filtertest_2_fu_176_FIR_delays_we0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            H_filter_FIR_int_43_we0 <= grp_FIR_filtertest_2_fu_176_FIR_delays_we0;
        else 
            H_filter_FIR_int_43_we0 <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_kernel_address0_assign_proc : process(ap_CS_fsm_state16, grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_address0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            H_filter_FIR_kernel_address0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_address0;
        else 
            H_filter_FIR_kernel_address0 <= ap_const_lv7_0;
        end if; 
    end process;


    H_filter_FIR_kernel_ce0_assign_proc : process(ap_CS_fsm_state16, grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_ce0, H_filter_FIR_kernel_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            H_filter_FIR_kernel_ce0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_H_filter_FIR_kernel_ce0;
        else 
            H_filter_FIR_kernel_ce0 <= H_filter_FIR_kernel_ce0_local;
        end if; 
    end process;


    H_filter_FIR_kernel_ce0_local_assign_proc : process(ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            H_filter_FIR_kernel_ce0_local <= ap_const_logic_1;
        else 
            H_filter_FIR_kernel_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln24_1_fu_327_p2 <= std_logic_vector(unsigned(y1_phase3) + unsigned(y_1_fu_300_p4));
    add_ln24_fu_321_p2 <= std_logic_vector(unsigned(y1_phase2) + unsigned(y1_phase1));
    add_ln81_fu_370_p2 <= std_logic_vector(signed(sext_ln81_4_fu_366_p1) + signed(H_filter_FIR_kernel_load_reg_483));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(grp_FIR_filtertest_2_fu_176_ap_done)
    begin
        if ((grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state12_blk_assign_proc : process(grp_FIR_filtertest_2_fu_176_ap_done)
    begin
        if ((grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;

    ap_ST_fsm_state16_blk_assign_proc : process(ap_block_state16_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state16_on_subcall_done)) then 
            ap_ST_fsm_state16_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state16_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state17_blk <= ap_const_logic_0;

    ap_ST_fsm_state18_blk_assign_proc : process(ap_block_state18_on_subcall_done, output_r_TREADY_int_regslice)
    begin
        if (((output_r_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state18_on_subcall_done))) then 
            ap_ST_fsm_state18_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state18_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state19_blk_assign_proc : process(ap_block_state19)
    begin
        if ((ap_const_boolean_1 = ap_block_state19)) then 
            ap_ST_fsm_state19_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state19_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(input_r_TVALID_int_regslice)
    begin
        if ((input_r_TVALID_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_FIR_filtertest_2_fu_176_ap_done)
    begin
        if ((grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(grp_FIR_filtertest_2_fu_176_ap_done)
    begin
        if ((grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(ap_block_state7_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state7_on_subcall_done)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_done)
    begin
        if ((grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state16_on_subcall_done_assign_proc : process(grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_done, grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_done)
    begin
                ap_block_state16_on_subcall_done <= ((grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_done = ap_const_logic_0) or (grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_done = ap_const_logic_0));
    end process;


    ap_block_state18_on_subcall_done_assign_proc : process(mod_value_load_reg_453, grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_done)
    begin
                ap_block_state18_on_subcall_done <= ((grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_done = ap_const_logic_0) and (mod_value_load_reg_453 = ap_const_lv2_0));
    end process;


    ap_block_state19_assign_proc : process(regslice_both_output_r_U_apdone_blk, output_r_TREADY_int_regslice)
    begin
                ap_block_state19 <= ((output_r_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_output_r_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_block_state7_on_subcall_done_assign_proc : process(grp_FIR_filtertest_2_fu_176_ap_done, grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_done)
    begin
                ap_block_state7_on_subcall_done <= ((grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_done = ap_const_logic_0) or (grp_FIR_filtertest_2_fu_176_ap_done = ap_const_logic_0));
    end process;


    ap_phi_mux_data_out_load_phi_fu_166_p8_assign_proc : process(ap_CS_fsm_state18, mod_value_load_reg_453, data_out_load_reg_163, grp_fu_433_p3)
    begin
        if (((mod_value_load_reg_453 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            ap_phi_mux_data_out_load_phi_fu_166_p8 <= grp_fu_433_p3(29 downto 16);
        else 
            ap_phi_mux_data_out_load_phi_fu_166_p8 <= data_out_load_reg_163;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    b_FIR_dec_int_40_address0_assign_proc : process(ap_CS_fsm_state18, mod_value_load_reg_453, ap_CS_fsm_state16, grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_b_FIR_dec_int_40_address0, grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_b_FIR_dec_int_40_address0)
    begin
        if (((mod_value_load_reg_453 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            b_FIR_dec_int_40_address0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_b_FIR_dec_int_40_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            b_FIR_dec_int_40_address0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_b_FIR_dec_int_40_address0;
        else 
            b_FIR_dec_int_40_address0 <= "XXX";
        end if; 
    end process;


    b_FIR_dec_int_40_ce0_assign_proc : process(ap_CS_fsm_state18, mod_value_load_reg_453, ap_CS_fsm_state16, grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_b_FIR_dec_int_40_ce0, grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_b_FIR_dec_int_40_ce0)
    begin
        if (((mod_value_load_reg_453 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            b_FIR_dec_int_40_ce0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_b_FIR_dec_int_40_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            b_FIR_dec_int_40_ce0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_b_FIR_dec_int_40_ce0;
        else 
            b_FIR_dec_int_40_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    b_FIR_dec_int_41_address0_assign_proc : process(grp_FIR_filtertest_2_fu_176_FIR_coe_address0, grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_b_FIR_dec_int_41_address0, ap_CS_fsm_state11, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            b_FIR_dec_int_41_address0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_b_FIR_dec_int_41_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            b_FIR_dec_int_41_address0 <= grp_FIR_filtertest_2_fu_176_FIR_coe_address0;
        else 
            b_FIR_dec_int_41_address0 <= "XXX";
        end if; 
    end process;


    b_FIR_dec_int_41_ce0_assign_proc : process(grp_FIR_filtertest_2_fu_176_FIR_coe_ce0, grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_b_FIR_dec_int_41_ce0, ap_CS_fsm_state11, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            b_FIR_dec_int_41_ce0 <= grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_b_FIR_dec_int_41_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            b_FIR_dec_int_41_ce0 <= grp_FIR_filtertest_2_fu_176_FIR_coe_ce0;
        else 
            b_FIR_dec_int_41_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    b_FIR_dec_int_42_ce0_assign_proc : process(ap_CS_fsm_state4, grp_FIR_filtertest_2_fu_176_FIR_coe_ce0, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            b_FIR_dec_int_42_ce0 <= grp_FIR_filtertest_2_fu_176_FIR_coe_ce0;
        else 
            b_FIR_dec_int_42_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    b_FIR_dec_int_43_ce0_assign_proc : process(ap_CS_fsm_state12, grp_FIR_filtertest_2_fu_176_FIR_coe_ce0, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            b_FIR_dec_int_43_ce0 <= grp_FIR_filtertest_2_fu_176_FIR_coe_ce0;
        else 
            b_FIR_dec_int_43_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start <= grp_FIR_HLS_Pipeline_VITIS_LOOP_65_1_fu_191_ap_start_reg;
    grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start <= grp_FIR_HLS_Pipeline_VITIS_LOOP_69_2_fu_200_ap_start_reg;
    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start <= grp_FIR_HLS_Pipeline_VITIS_LOOP_83_11_fu_215_ap_start_reg;
    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start <= grp_FIR_HLS_Pipeline_VITIS_LOOP_83_12_fu_224_ap_start_reg;
    grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start <= grp_FIR_HLS_Pipeline_VITIS_LOOP_83_1_fu_206_ap_start_reg;

    grp_FIR_filtertest_2_fu_176_FIR_coe_q0_assign_proc : process(b_FIR_dec_int_43_q0, b_FIR_dec_int_41_q0, b_FIR_dec_int_42_q0, ap_CS_fsm_state4, ap_CS_fsm_state12, ap_CS_fsm_state3, ap_CS_fsm_state11, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_FIR_filtertest_2_fu_176_FIR_coe_q0 <= b_FIR_dec_int_41_q0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            grp_FIR_filtertest_2_fu_176_FIR_coe_q0 <= b_FIR_dec_int_43_q0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            grp_FIR_filtertest_2_fu_176_FIR_coe_q0 <= b_FIR_dec_int_42_q0;
        else 
            grp_FIR_filtertest_2_fu_176_FIR_coe_q0 <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_FIR_filtertest_2_fu_176_FIR_delays_q0_assign_proc : process(H_filter_FIR_dec_43_q0, H_filter_FIR_dec_42_q0, H_filter_FIR_int_42_q0, H_filter_FIR_dec_41_q0, H_filter_FIR_int_43_q0, ap_CS_fsm_state4, ap_CS_fsm_state12, ap_CS_fsm_state3, ap_CS_fsm_state11, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_FIR_filtertest_2_fu_176_FIR_delays_q0 <= H_filter_FIR_int_43_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_FIR_filtertest_2_fu_176_FIR_delays_q0 <= H_filter_FIR_dec_41_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_FIR_filtertest_2_fu_176_FIR_delays_q0 <= H_filter_FIR_dec_43_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_FIR_filtertest_2_fu_176_FIR_delays_q0 <= H_filter_FIR_int_42_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_FIR_filtertest_2_fu_176_FIR_delays_q0 <= H_filter_FIR_dec_42_q0;
        else 
            grp_FIR_filtertest_2_fu_176_FIR_delays_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_FIR_filtertest_2_fu_176_FIR_delays_q1_assign_proc : process(H_filter_FIR_dec_43_q1, H_filter_FIR_dec_42_q1, H_filter_FIR_int_42_q1, H_filter_FIR_dec_41_q1, H_filter_FIR_int_43_q1, ap_CS_fsm_state4, ap_CS_fsm_state12, ap_CS_fsm_state3, ap_CS_fsm_state11, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_FIR_filtertest_2_fu_176_FIR_delays_q1 <= H_filter_FIR_int_43_q1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_FIR_filtertest_2_fu_176_FIR_delays_q1 <= H_filter_FIR_dec_41_q1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_FIR_filtertest_2_fu_176_FIR_delays_q1 <= H_filter_FIR_dec_43_q1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_FIR_filtertest_2_fu_176_FIR_delays_q1 <= H_filter_FIR_int_42_q1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_FIR_filtertest_2_fu_176_FIR_delays_q1 <= H_filter_FIR_dec_42_q1;
        else 
            grp_FIR_filtertest_2_fu_176_FIR_delays_q1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_FIR_filtertest_2_fu_176_ap_start <= grp_FIR_filtertest_2_fu_176_ap_start_reg;

    grp_FIR_filtertest_2_fu_176_x_n_assign_proc : process(y2, x_n_1_reg_447, ap_CS_fsm_state4, ap_CS_fsm_state12, ap_CS_fsm_state3, ap_CS_fsm_state11, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            grp_FIR_filtertest_2_fu_176_x_n <= y2;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            grp_FIR_filtertest_2_fu_176_x_n <= x_n_1_reg_447;
        else 
            grp_FIR_filtertest_2_fu_176_x_n <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_424_ce_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state13, input_r_TVALID_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or ((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_fu_424_ce <= ap_const_logic_1;
        else 
            grp_fu_424_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_424_p1 <= ap_const_lv25_1B4(9 - 1 downto 0);

    grp_fu_433_ce_assign_proc : process(ap_CS_fsm_state18, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_block_state18_on_subcall_done, ap_CS_fsm_state17, ap_block_state16_on_subcall_done, output_r_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state15) or (not(((output_r_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state18_on_subcall_done))) and (ap_const_logic_1 = ap_CS_fsm_state18)) or ((ap_const_boolean_0 = ap_block_state16_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state16)))) then 
            grp_fu_433_ce <= ap_const_logic_1;
        else 
            grp_fu_433_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_433_p1 <= ap_const_lv25_1B4(9 - 1 downto 0);

    input_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, input_r_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            input_r_TDATA_blk_n <= input_r_TVALID_int_regslice;
        else 
            input_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    input_r_TREADY <= regslice_both_input_r_U_ack_in;

    input_r_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, input_r_TVALID_int_regslice)
    begin
        if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_r_TREADY_int_regslice <= ap_const_logic_1;
        else 
            input_r_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    mod_value_load_load_fu_233_p1 <= mod_value;

    output_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state18, ap_CS_fsm_state19, output_r_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            output_r_TDATA_blk_n <= output_r_TREADY_int_regslice;
        else 
            output_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    output_r_TDATA_int_regslice <= (ap_phi_mux_data_out_load_phi_fu_166_p8 & ap_const_lv2_0);
    output_r_TVALID <= regslice_both_output_r_U_vld_out;

    output_r_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state18, ap_block_state18_on_subcall_done, output_r_TREADY_int_regslice)
    begin
        if ((not(((output_r_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state18_on_subcall_done))) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            output_r_TVALID_int_regslice <= ap_const_logic_1;
        else 
            output_r_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    p_shl_fu_340_p3 <= (x_n_fu_333_p2 & ap_const_lv7_0);
        sext_ln81_3_fu_356_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_348_p3),23));

        sext_ln81_4_fu_366_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln81_fu_360_p2),32));

    sext_ln81_fu_241_p0 <= input_r_TDATA_int_regslice;
    shl_ln_fu_261_p3 <= (y2 & ap_const_lv16_0);
    sub_ln81_fu_360_p2 <= std_logic_vector(unsigned(p_shl_fu_340_p3) - unsigned(sext_ln81_3_fu_356_p1));
    tmp_fu_348_p3 <= (x_n_fu_333_p2 & ap_const_lv2_0);
    trunc_ln39_fu_251_p1 <= grp_FIR_filtertest_2_fu_176_ap_return(14 - 1 downto 0);
    trunc_ln45_fu_290_p1 <= grp_FIR_filtertest_2_fu_176_ap_return(14 - 1 downto 0);
    trunc_ln81_fu_395_p1 <= H_filter_FIR_int_40_q0(30 - 1 downto 0);
    x_n_fu_333_p2 <= std_logic_vector(unsigned(add_ln24_1_fu_327_p2) + unsigned(add_ln24_fu_321_p2));
    y_1_fu_300_p4 <= grp_fu_424_p3(31 downto 16);
    y_3_fu_375_p4 <= add_ln81_fu_370_p2(31 downto 16);
end behav;
